/**
 * generated by Xtext 2.38.0
 */
package dut.control.kermloc.kerMLOC.impl;

import dut.control.kermloc.kerMLOC.BasicFeaturePrefix;
import dut.control.kermloc.kerMLOC.FeatureDirection;
import dut.control.kermloc.kerMLOC.KerMLOCPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Basic Feature Prefix</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link dut.control.kermloc.kerMLOC.impl.BasicFeaturePrefixImpl#getDirection <em>Direction</em>}</li>
 *   <li>{@link dut.control.kermloc.kerMLOC.impl.BasicFeaturePrefixImpl#isIsDerived <em>Is Derived</em>}</li>
 *   <li>{@link dut.control.kermloc.kerMLOC.impl.BasicFeaturePrefixImpl#isIsAbstract <em>Is Abstract</em>}</li>
 *   <li>{@link dut.control.kermloc.kerMLOC.impl.BasicFeaturePrefixImpl#isIsComposite <em>Is Composite</em>}</li>
 *   <li>{@link dut.control.kermloc.kerMLOC.impl.BasicFeaturePrefixImpl#isIsPortion <em>Is Portion</em>}</li>
 *   <li>{@link dut.control.kermloc.kerMLOC.impl.BasicFeaturePrefixImpl#isIsVariable <em>Is Variable</em>}</li>
 *   <li>{@link dut.control.kermloc.kerMLOC.impl.BasicFeaturePrefixImpl#isIsConstantBasic <em>Is Constant Basic</em>}</li>
 * </ul>
 *
 * @generated
 */
public class BasicFeaturePrefixImpl extends MinimalEObjectImpl.Container implements BasicFeaturePrefix
{
  /**
   * The default value of the '{@link #getDirection() <em>Direction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDirection()
   * @generated
   * @ordered
   */
  protected static final FeatureDirection DIRECTION_EDEFAULT = FeatureDirection.NULL;

  /**
   * The cached value of the '{@link #getDirection() <em>Direction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDirection()
   * @generated
   * @ordered
   */
  protected FeatureDirection direction = DIRECTION_EDEFAULT;

  /**
   * The default value of the '{@link #isIsDerived() <em>Is Derived</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsDerived()
   * @generated
   * @ordered
   */
  protected static final boolean IS_DERIVED_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsDerived() <em>Is Derived</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsDerived()
   * @generated
   * @ordered
   */
  protected boolean isDerived = IS_DERIVED_EDEFAULT;

  /**
   * The default value of the '{@link #isIsAbstract() <em>Is Abstract</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsAbstract()
   * @generated
   * @ordered
   */
  protected static final boolean IS_ABSTRACT_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsAbstract() <em>Is Abstract</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsAbstract()
   * @generated
   * @ordered
   */
  protected boolean isAbstract = IS_ABSTRACT_EDEFAULT;

  /**
   * The default value of the '{@link #isIsComposite() <em>Is Composite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsComposite()
   * @generated
   * @ordered
   */
  protected static final boolean IS_COMPOSITE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsComposite() <em>Is Composite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsComposite()
   * @generated
   * @ordered
   */
  protected boolean isComposite = IS_COMPOSITE_EDEFAULT;

  /**
   * The default value of the '{@link #isIsPortion() <em>Is Portion</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsPortion()
   * @generated
   * @ordered
   */
  protected static final boolean IS_PORTION_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsPortion() <em>Is Portion</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsPortion()
   * @generated
   * @ordered
   */
  protected boolean isPortion = IS_PORTION_EDEFAULT;

  /**
   * The default value of the '{@link #isIsVariable() <em>Is Variable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsVariable()
   * @generated
   * @ordered
   */
  protected static final boolean IS_VARIABLE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsVariable() <em>Is Variable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsVariable()
   * @generated
   * @ordered
   */
  protected boolean isVariable = IS_VARIABLE_EDEFAULT;

  /**
   * The default value of the '{@link #isIsConstantBasic() <em>Is Constant Basic</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsConstantBasic()
   * @generated
   * @ordered
   */
  protected static final boolean IS_CONSTANT_BASIC_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsConstantBasic() <em>Is Constant Basic</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsConstantBasic()
   * @generated
   * @ordered
   */
  protected boolean isConstantBasic = IS_CONSTANT_BASIC_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BasicFeaturePrefixImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return KerMLOCPackage.eINSTANCE.getBasicFeaturePrefix();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FeatureDirection getDirection()
  {
    return direction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDirection(FeatureDirection newDirection)
  {
    FeatureDirection oldDirection = direction;
    direction = newDirection == null ? DIRECTION_EDEFAULT : newDirection;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KerMLOCPackage.BASIC_FEATURE_PREFIX__DIRECTION, oldDirection, direction));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsDerived()
  {
    return isDerived;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsDerived(boolean newIsDerived)
  {
    boolean oldIsDerived = isDerived;
    isDerived = newIsDerived;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KerMLOCPackage.BASIC_FEATURE_PREFIX__IS_DERIVED, oldIsDerived, isDerived));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsAbstract()
  {
    return isAbstract;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsAbstract(boolean newIsAbstract)
  {
    boolean oldIsAbstract = isAbstract;
    isAbstract = newIsAbstract;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KerMLOCPackage.BASIC_FEATURE_PREFIX__IS_ABSTRACT, oldIsAbstract, isAbstract));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsComposite()
  {
    return isComposite;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsComposite(boolean newIsComposite)
  {
    boolean oldIsComposite = isComposite;
    isComposite = newIsComposite;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KerMLOCPackage.BASIC_FEATURE_PREFIX__IS_COMPOSITE, oldIsComposite, isComposite));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsPortion()
  {
    return isPortion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsPortion(boolean newIsPortion)
  {
    boolean oldIsPortion = isPortion;
    isPortion = newIsPortion;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KerMLOCPackage.BASIC_FEATURE_PREFIX__IS_PORTION, oldIsPortion, isPortion));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsVariable()
  {
    return isVariable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsVariable(boolean newIsVariable)
  {
    boolean oldIsVariable = isVariable;
    isVariable = newIsVariable;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KerMLOCPackage.BASIC_FEATURE_PREFIX__IS_VARIABLE, oldIsVariable, isVariable));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsConstantBasic()
  {
    return isConstantBasic;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsConstantBasic(boolean newIsConstantBasic)
  {
    boolean oldIsConstantBasic = isConstantBasic;
    isConstantBasic = newIsConstantBasic;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KerMLOCPackage.BASIC_FEATURE_PREFIX__IS_CONSTANT_BASIC, oldIsConstantBasic, isConstantBasic));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case KerMLOCPackage.BASIC_FEATURE_PREFIX__DIRECTION:
        return getDirection();
      case KerMLOCPackage.BASIC_FEATURE_PREFIX__IS_DERIVED:
        return isIsDerived();
      case KerMLOCPackage.BASIC_FEATURE_PREFIX__IS_ABSTRACT:
        return isIsAbstract();
      case KerMLOCPackage.BASIC_FEATURE_PREFIX__IS_COMPOSITE:
        return isIsComposite();
      case KerMLOCPackage.BASIC_FEATURE_PREFIX__IS_PORTION:
        return isIsPortion();
      case KerMLOCPackage.BASIC_FEATURE_PREFIX__IS_VARIABLE:
        return isIsVariable();
      case KerMLOCPackage.BASIC_FEATURE_PREFIX__IS_CONSTANT_BASIC:
        return isIsConstantBasic();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case KerMLOCPackage.BASIC_FEATURE_PREFIX__DIRECTION:
        setDirection((FeatureDirection)newValue);
        return;
      case KerMLOCPackage.BASIC_FEATURE_PREFIX__IS_DERIVED:
        setIsDerived((Boolean)newValue);
        return;
      case KerMLOCPackage.BASIC_FEATURE_PREFIX__IS_ABSTRACT:
        setIsAbstract((Boolean)newValue);
        return;
      case KerMLOCPackage.BASIC_FEATURE_PREFIX__IS_COMPOSITE:
        setIsComposite((Boolean)newValue);
        return;
      case KerMLOCPackage.BASIC_FEATURE_PREFIX__IS_PORTION:
        setIsPortion((Boolean)newValue);
        return;
      case KerMLOCPackage.BASIC_FEATURE_PREFIX__IS_VARIABLE:
        setIsVariable((Boolean)newValue);
        return;
      case KerMLOCPackage.BASIC_FEATURE_PREFIX__IS_CONSTANT_BASIC:
        setIsConstantBasic((Boolean)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case KerMLOCPackage.BASIC_FEATURE_PREFIX__DIRECTION:
        setDirection(DIRECTION_EDEFAULT);
        return;
      case KerMLOCPackage.BASIC_FEATURE_PREFIX__IS_DERIVED:
        setIsDerived(IS_DERIVED_EDEFAULT);
        return;
      case KerMLOCPackage.BASIC_FEATURE_PREFIX__IS_ABSTRACT:
        setIsAbstract(IS_ABSTRACT_EDEFAULT);
        return;
      case KerMLOCPackage.BASIC_FEATURE_PREFIX__IS_COMPOSITE:
        setIsComposite(IS_COMPOSITE_EDEFAULT);
        return;
      case KerMLOCPackage.BASIC_FEATURE_PREFIX__IS_PORTION:
        setIsPortion(IS_PORTION_EDEFAULT);
        return;
      case KerMLOCPackage.BASIC_FEATURE_PREFIX__IS_VARIABLE:
        setIsVariable(IS_VARIABLE_EDEFAULT);
        return;
      case KerMLOCPackage.BASIC_FEATURE_PREFIX__IS_CONSTANT_BASIC:
        setIsConstantBasic(IS_CONSTANT_BASIC_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case KerMLOCPackage.BASIC_FEATURE_PREFIX__DIRECTION:
        return direction != DIRECTION_EDEFAULT;
      case KerMLOCPackage.BASIC_FEATURE_PREFIX__IS_DERIVED:
        return isDerived != IS_DERIVED_EDEFAULT;
      case KerMLOCPackage.BASIC_FEATURE_PREFIX__IS_ABSTRACT:
        return isAbstract != IS_ABSTRACT_EDEFAULT;
      case KerMLOCPackage.BASIC_FEATURE_PREFIX__IS_COMPOSITE:
        return isComposite != IS_COMPOSITE_EDEFAULT;
      case KerMLOCPackage.BASIC_FEATURE_PREFIX__IS_PORTION:
        return isPortion != IS_PORTION_EDEFAULT;
      case KerMLOCPackage.BASIC_FEATURE_PREFIX__IS_VARIABLE:
        return isVariable != IS_VARIABLE_EDEFAULT;
      case KerMLOCPackage.BASIC_FEATURE_PREFIX__IS_CONSTANT_BASIC:
        return isConstantBasic != IS_CONSTANT_BASIC_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (direction: ");
    result.append(direction);
    result.append(", isDerived: ");
    result.append(isDerived);
    result.append(", isAbstract: ");
    result.append(isAbstract);
    result.append(", isComposite: ");
    result.append(isComposite);
    result.append(", isPortion: ");
    result.append(isPortion);
    result.append(", isVariable: ");
    result.append(isVariable);
    result.append(", isConstantBasic: ");
    result.append(isConstantBasic);
    result.append(')');
    return result.toString();
  }

} //BasicFeaturePrefixImpl
