/**
 * generated by Xtext 2.38.0
 */
package dut.control.kermloc.kerMLOC.impl;

import dut.control.kermloc.kerMLOC.BinaryConnectorDeclaration;
import dut.control.kermloc.kerMLOC.ConnectorEnd;
import dut.control.kermloc.kerMLOC.KerMLOCPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Binary Connector Declaration</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link dut.control.kermloc.kerMLOC.impl.BinaryConnectorDeclarationImpl#getConnectorPartBinary <em>Connector Part Binary</em>}</li>
 * </ul>
 *
 * @generated
 */
public class BinaryConnectorDeclarationImpl extends FeatureDeclarationImpl implements BinaryConnectorDeclaration
{
  /**
   * The cached value of the '{@link #getConnectorPartBinary() <em>Connector Part Binary</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConnectorPartBinary()
   * @generated
   * @ordered
   */
  protected EList<ConnectorEnd> connectorPartBinary;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BinaryConnectorDeclarationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return KerMLOCPackage.eINSTANCE.getBinaryConnectorDeclaration();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ConnectorEnd> getConnectorPartBinary()
  {
    if (connectorPartBinary == null)
    {
      connectorPartBinary = new EObjectContainmentEList<ConnectorEnd>(ConnectorEnd.class, this, KerMLOCPackage.BINARY_CONNECTOR_DECLARATION__CONNECTOR_PART_BINARY);
    }
    return connectorPartBinary;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case KerMLOCPackage.BINARY_CONNECTOR_DECLARATION__CONNECTOR_PART_BINARY:
        return ((InternalEList<?>)getConnectorPartBinary()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case KerMLOCPackage.BINARY_CONNECTOR_DECLARATION__CONNECTOR_PART_BINARY:
        return getConnectorPartBinary();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case KerMLOCPackage.BINARY_CONNECTOR_DECLARATION__CONNECTOR_PART_BINARY:
        getConnectorPartBinary().clear();
        getConnectorPartBinary().addAll((Collection<? extends ConnectorEnd>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case KerMLOCPackage.BINARY_CONNECTOR_DECLARATION__CONNECTOR_PART_BINARY:
        getConnectorPartBinary().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case KerMLOCPackage.BINARY_CONNECTOR_DECLARATION__CONNECTOR_PART_BINARY:
        return connectorPartBinary != null && !connectorPartBinary.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //BinaryConnectorDeclarationImpl
