/**
 * generated by Xtext 2.38.0
 */
package dut.control.kermloc.kerMLOC.impl;

import dut.control.kermloc.kerMLOC.Disjoining;
import dut.control.kermloc.kerMLOC.Identification;
import dut.control.kermloc.kerMLOC.KerMLOCPackage;
import dut.control.kermloc.kerMLOC.MemberPrefix;
import dut.control.kermloc.kerMLOC.RelationshipBodyElement;
import dut.control.kermloc.kerMLOC.VisibilityIndicator;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Disjoining</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link dut.control.kermloc.kerMLOC.impl.DisjoiningImpl#getVisibility <em>Visibility</em>}</li>
 *   <li>{@link dut.control.kermloc.kerMLOC.impl.DisjoiningImpl#isIsVariant <em>Is Variant</em>}</li>
 *   <li>{@link dut.control.kermloc.kerMLOC.impl.DisjoiningImpl#getDeclaredShortName <em>Declared Short Name</em>}</li>
 *   <li>{@link dut.control.kermloc.kerMLOC.impl.DisjoiningImpl#getDeclaredName <em>Declared Name</em>}</li>
 *   <li>{@link dut.control.kermloc.kerMLOC.impl.DisjoiningImpl#isIsDisjoining <em>Is Disjoining</em>}</li>
 *   <li>{@link dut.control.kermloc.kerMLOC.impl.DisjoiningImpl#getTypeDisjoined <em>Type Disjoined</em>}</li>
 *   <li>{@link dut.control.kermloc.kerMLOC.impl.DisjoiningImpl#getDisjoiningType <em>Disjoining Type</em>}</li>
 *   <li>{@link dut.control.kermloc.kerMLOC.impl.DisjoiningImpl#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DisjoiningImpl extends NonFeatureElementImpl implements Disjoining
{
  /**
   * The default value of the '{@link #getVisibility() <em>Visibility</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVisibility()
   * @generated
   * @ordered
   */
  protected static final VisibilityIndicator VISIBILITY_EDEFAULT = VisibilityIndicator.NULL;

  /**
   * The cached value of the '{@link #getVisibility() <em>Visibility</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVisibility()
   * @generated
   * @ordered
   */
  protected VisibilityIndicator visibility = VISIBILITY_EDEFAULT;

  /**
   * The default value of the '{@link #isIsVariant() <em>Is Variant</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsVariant()
   * @generated
   * @ordered
   */
  protected static final boolean IS_VARIANT_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsVariant() <em>Is Variant</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsVariant()
   * @generated
   * @ordered
   */
  protected boolean isVariant = IS_VARIANT_EDEFAULT;

  /**
   * The default value of the '{@link #getDeclaredShortName() <em>Declared Short Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDeclaredShortName()
   * @generated
   * @ordered
   */
  protected static final String DECLARED_SHORT_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDeclaredShortName() <em>Declared Short Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDeclaredShortName()
   * @generated
   * @ordered
   */
  protected String declaredShortName = DECLARED_SHORT_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getDeclaredName() <em>Declared Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDeclaredName()
   * @generated
   * @ordered
   */
  protected static final String DECLARED_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDeclaredName() <em>Declared Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDeclaredName()
   * @generated
   * @ordered
   */
  protected String declaredName = DECLARED_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #isIsDisjoining() <em>Is Disjoining</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsDisjoining()
   * @generated
   * @ordered
   */
  protected static final boolean IS_DISJOINING_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsDisjoining() <em>Is Disjoining</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsDisjoining()
   * @generated
   * @ordered
   */
  protected boolean isDisjoining = IS_DISJOINING_EDEFAULT;

  /**
   * The default value of the '{@link #getTypeDisjoined() <em>Type Disjoined</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypeDisjoined()
   * @generated
   * @ordered
   */
  protected static final String TYPE_DISJOINED_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTypeDisjoined() <em>Type Disjoined</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypeDisjoined()
   * @generated
   * @ordered
   */
  protected String typeDisjoined = TYPE_DISJOINED_EDEFAULT;

  /**
   * The default value of the '{@link #getDisjoiningType() <em>Disjoining Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDisjoiningType()
   * @generated
   * @ordered
   */
  protected static final String DISJOINING_TYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDisjoiningType() <em>Disjoining Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDisjoiningType()
   * @generated
   * @ordered
   */
  protected String disjoiningType = DISJOINING_TYPE_EDEFAULT;

  /**
   * The cached value of the '{@link #getElements() <em>Elements</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getElements()
   * @generated
   * @ordered
   */
  protected EList<RelationshipBodyElement> elements;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DisjoiningImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return KerMLOCPackage.eINSTANCE.getDisjoining();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VisibilityIndicator getVisibility()
  {
    return visibility;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVisibility(VisibilityIndicator newVisibility)
  {
    VisibilityIndicator oldVisibility = visibility;
    visibility = newVisibility == null ? VISIBILITY_EDEFAULT : newVisibility;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KerMLOCPackage.DISJOINING__VISIBILITY, oldVisibility, visibility));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsVariant()
  {
    return isVariant;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsVariant(boolean newIsVariant)
  {
    boolean oldIsVariant = isVariant;
    isVariant = newIsVariant;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KerMLOCPackage.DISJOINING__IS_VARIANT, oldIsVariant, isVariant));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDeclaredShortName()
  {
    return declaredShortName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDeclaredShortName(String newDeclaredShortName)
  {
    String oldDeclaredShortName = declaredShortName;
    declaredShortName = newDeclaredShortName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KerMLOCPackage.DISJOINING__DECLARED_SHORT_NAME, oldDeclaredShortName, declaredShortName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDeclaredName()
  {
    return declaredName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDeclaredName(String newDeclaredName)
  {
    String oldDeclaredName = declaredName;
    declaredName = newDeclaredName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KerMLOCPackage.DISJOINING__DECLARED_NAME, oldDeclaredName, declaredName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsDisjoining()
  {
    return isDisjoining;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsDisjoining(boolean newIsDisjoining)
  {
    boolean oldIsDisjoining = isDisjoining;
    isDisjoining = newIsDisjoining;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KerMLOCPackage.DISJOINING__IS_DISJOINING, oldIsDisjoining, isDisjoining));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTypeDisjoined()
  {
    return typeDisjoined;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTypeDisjoined(String newTypeDisjoined)
  {
    String oldTypeDisjoined = typeDisjoined;
    typeDisjoined = newTypeDisjoined;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KerMLOCPackage.DISJOINING__TYPE_DISJOINED, oldTypeDisjoined, typeDisjoined));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDisjoiningType()
  {
    return disjoiningType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDisjoiningType(String newDisjoiningType)
  {
    String oldDisjoiningType = disjoiningType;
    disjoiningType = newDisjoiningType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KerMLOCPackage.DISJOINING__DISJOINING_TYPE, oldDisjoiningType, disjoiningType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<RelationshipBodyElement> getElements()
  {
    if (elements == null)
    {
      elements = new EObjectContainmentEList<RelationshipBodyElement>(RelationshipBodyElement.class, this, KerMLOCPackage.DISJOINING__ELEMENTS);
    }
    return elements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case KerMLOCPackage.DISJOINING__ELEMENTS:
        return ((InternalEList<?>)getElements()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case KerMLOCPackage.DISJOINING__VISIBILITY:
        return getVisibility();
      case KerMLOCPackage.DISJOINING__IS_VARIANT:
        return isIsVariant();
      case KerMLOCPackage.DISJOINING__DECLARED_SHORT_NAME:
        return getDeclaredShortName();
      case KerMLOCPackage.DISJOINING__DECLARED_NAME:
        return getDeclaredName();
      case KerMLOCPackage.DISJOINING__IS_DISJOINING:
        return isIsDisjoining();
      case KerMLOCPackage.DISJOINING__TYPE_DISJOINED:
        return getTypeDisjoined();
      case KerMLOCPackage.DISJOINING__DISJOINING_TYPE:
        return getDisjoiningType();
      case KerMLOCPackage.DISJOINING__ELEMENTS:
        return getElements();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case KerMLOCPackage.DISJOINING__VISIBILITY:
        setVisibility((VisibilityIndicator)newValue);
        return;
      case KerMLOCPackage.DISJOINING__IS_VARIANT:
        setIsVariant((Boolean)newValue);
        return;
      case KerMLOCPackage.DISJOINING__DECLARED_SHORT_NAME:
        setDeclaredShortName((String)newValue);
        return;
      case KerMLOCPackage.DISJOINING__DECLARED_NAME:
        setDeclaredName((String)newValue);
        return;
      case KerMLOCPackage.DISJOINING__IS_DISJOINING:
        setIsDisjoining((Boolean)newValue);
        return;
      case KerMLOCPackage.DISJOINING__TYPE_DISJOINED:
        setTypeDisjoined((String)newValue);
        return;
      case KerMLOCPackage.DISJOINING__DISJOINING_TYPE:
        setDisjoiningType((String)newValue);
        return;
      case KerMLOCPackage.DISJOINING__ELEMENTS:
        getElements().clear();
        getElements().addAll((Collection<? extends RelationshipBodyElement>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case KerMLOCPackage.DISJOINING__VISIBILITY:
        setVisibility(VISIBILITY_EDEFAULT);
        return;
      case KerMLOCPackage.DISJOINING__IS_VARIANT:
        setIsVariant(IS_VARIANT_EDEFAULT);
        return;
      case KerMLOCPackage.DISJOINING__DECLARED_SHORT_NAME:
        setDeclaredShortName(DECLARED_SHORT_NAME_EDEFAULT);
        return;
      case KerMLOCPackage.DISJOINING__DECLARED_NAME:
        setDeclaredName(DECLARED_NAME_EDEFAULT);
        return;
      case KerMLOCPackage.DISJOINING__IS_DISJOINING:
        setIsDisjoining(IS_DISJOINING_EDEFAULT);
        return;
      case KerMLOCPackage.DISJOINING__TYPE_DISJOINED:
        setTypeDisjoined(TYPE_DISJOINED_EDEFAULT);
        return;
      case KerMLOCPackage.DISJOINING__DISJOINING_TYPE:
        setDisjoiningType(DISJOINING_TYPE_EDEFAULT);
        return;
      case KerMLOCPackage.DISJOINING__ELEMENTS:
        getElements().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case KerMLOCPackage.DISJOINING__VISIBILITY:
        return visibility != VISIBILITY_EDEFAULT;
      case KerMLOCPackage.DISJOINING__IS_VARIANT:
        return isVariant != IS_VARIANT_EDEFAULT;
      case KerMLOCPackage.DISJOINING__DECLARED_SHORT_NAME:
        return DECLARED_SHORT_NAME_EDEFAULT == null ? declaredShortName != null : !DECLARED_SHORT_NAME_EDEFAULT.equals(declaredShortName);
      case KerMLOCPackage.DISJOINING__DECLARED_NAME:
        return DECLARED_NAME_EDEFAULT == null ? declaredName != null : !DECLARED_NAME_EDEFAULT.equals(declaredName);
      case KerMLOCPackage.DISJOINING__IS_DISJOINING:
        return isDisjoining != IS_DISJOINING_EDEFAULT;
      case KerMLOCPackage.DISJOINING__TYPE_DISJOINED:
        return TYPE_DISJOINED_EDEFAULT == null ? typeDisjoined != null : !TYPE_DISJOINED_EDEFAULT.equals(typeDisjoined);
      case KerMLOCPackage.DISJOINING__DISJOINING_TYPE:
        return DISJOINING_TYPE_EDEFAULT == null ? disjoiningType != null : !DISJOINING_TYPE_EDEFAULT.equals(disjoiningType);
      case KerMLOCPackage.DISJOINING__ELEMENTS:
        return elements != null && !elements.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eBaseStructuralFeatureID(int derivedFeatureID, Class<?> baseClass)
  {
    if (baseClass == MemberPrefix.class)
    {
      switch (derivedFeatureID)
      {
        case KerMLOCPackage.DISJOINING__VISIBILITY: return KerMLOCPackage.MEMBER_PREFIX__VISIBILITY;
        case KerMLOCPackage.DISJOINING__IS_VARIANT: return KerMLOCPackage.MEMBER_PREFIX__IS_VARIANT;
        default: return -1;
      }
    }
    if (baseClass == Identification.class)
    {
      switch (derivedFeatureID)
      {
        case KerMLOCPackage.DISJOINING__DECLARED_SHORT_NAME: return KerMLOCPackage.IDENTIFICATION__DECLARED_SHORT_NAME;
        case KerMLOCPackage.DISJOINING__DECLARED_NAME: return KerMLOCPackage.IDENTIFICATION__DECLARED_NAME;
        default: return -1;
      }
    }
    return super.eBaseStructuralFeatureID(derivedFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eDerivedStructuralFeatureID(int baseFeatureID, Class<?> baseClass)
  {
    if (baseClass == MemberPrefix.class)
    {
      switch (baseFeatureID)
      {
        case KerMLOCPackage.MEMBER_PREFIX__VISIBILITY: return KerMLOCPackage.DISJOINING__VISIBILITY;
        case KerMLOCPackage.MEMBER_PREFIX__IS_VARIANT: return KerMLOCPackage.DISJOINING__IS_VARIANT;
        default: return -1;
      }
    }
    if (baseClass == Identification.class)
    {
      switch (baseFeatureID)
      {
        case KerMLOCPackage.IDENTIFICATION__DECLARED_SHORT_NAME: return KerMLOCPackage.DISJOINING__DECLARED_SHORT_NAME;
        case KerMLOCPackage.IDENTIFICATION__DECLARED_NAME: return KerMLOCPackage.DISJOINING__DECLARED_NAME;
        default: return -1;
      }
    }
    return super.eDerivedStructuralFeatureID(baseFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (visibility: ");
    result.append(visibility);
    result.append(", isVariant: ");
    result.append(isVariant);
    result.append(", declaredShortName: ");
    result.append(declaredShortName);
    result.append(", declaredName: ");
    result.append(declaredName);
    result.append(", isDisjoining: ");
    result.append(isDisjoining);
    result.append(", typeDisjoined: ");
    result.append(typeDisjoined);
    result.append(", disjoiningType: ");
    result.append(disjoiningType);
    result.append(')');
    return result.toString();
  }

} //DisjoiningImpl
