/**
 * generated by Xtext 2.38.0
 */
package dut.control.moloc.mOloc.util;

import dut.control.moloc.mOloc.*;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see dut.control.moloc.mOloc.MOlocPackage
 * @generated
 */
public class MOlocAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static MOlocPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MOlocAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = MOlocPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MOlocSwitch<Adapter> modelSwitch =
    new MOlocSwitch<Adapter>()
    {
      @Override
      public Adapter caseStored_definition(Stored_definition object)
      {
        return createStored_definitionAdapter();
      }
      @Override
      public Adapter caseClass_definition(Class_definition object)
      {
        return createClass_definitionAdapter();
      }
      @Override
      public Adapter caseclass_prefixes(class_prefixes object)
      {
        return createclass_prefixesAdapter();
      }
      @Override
      public Adapter caseclass_specifier(class_specifier object)
      {
        return createclass_specifierAdapter();
      }
      @Override
      public Adapter caselong_class_specifier(long_class_specifier object)
      {
        return createlong_class_specifierAdapter();
      }
      @Override
      public Adapter caseshort_class_specifier(short_class_specifier object)
      {
        return createshort_class_specifierAdapter();
      }
      @Override
      public Adapter caseder_class_specifier(der_class_specifier object)
      {
        return createder_class_specifierAdapter();
      }
      @Override
      public Adapter caseclass_name(class_name object)
      {
        return createclass_nameAdapter();
      }
      @Override
      public Adapter caseclass_modification(class_modification object)
      {
        return createclass_modificationAdapter();
      }
      @Override
      public Adapter casedescription_string(description_string object)
      {
        return createdescription_stringAdapter();
      }
      @Override
      public Adapter casecomposition(composition object)
      {
        return createcompositionAdapter();
      }
      @Override
      public Adapter casetype_specifier(type_specifier object)
      {
        return createtype_specifierAdapter();
      }
      @Override
      public Adapter caseenum_list(enum_list object)
      {
        return createenum_listAdapter();
      }
      @Override
      public Adapter caseEnumerationLiteral(EnumerationLiteral object)
      {
        return createEnumerationLiteralAdapter();
      }
      @Override
      public Adapter casedescription(description object)
      {
        return createdescriptionAdapter();
      }
      @Override
      public Adapter caseArgument(Argument object)
      {
        return createArgumentAdapter();
      }
      @Override
      public Adapter caseelement_modification(element_modification object)
      {
        return createelement_modificationAdapter();
      }
      @Override
      public Adapter caseelement_replaceable(element_replaceable object)
      {
        return createelement_replaceableAdapter();
      }
      @Override
      public Adapter caseshort_class_definition(short_class_definition object)
      {
        return createshort_class_definitionAdapter();
      }
      @Override
      public Adapter casecomponent_clause1(component_clause1 object)
      {
        return createcomponent_clause1Adapter();
      }
      @Override
      public Adapter casetype_prefix(type_prefix object)
      {
        return createtype_prefixAdapter();
      }
      @Override
      public Adapter casecomponent_declaration1(component_declaration1 object)
      {
        return createcomponent_declaration1Adapter();
      }
      @Override
      public Adapter casedeclaration(declaration object)
      {
        return createdeclarationAdapter();
      }
      @Override
      public Adapter casearray_subscripts(array_subscripts object)
      {
        return createarray_subscriptsAdapter();
      }
      @Override
      public Adapter caseUnfinished2(Unfinished2 object)
      {
        return createUnfinished2Adapter();
      }
      @Override
      public Adapter casemodification(modification object)
      {
        return createmodificationAdapter();
      }
      @Override
      public Adapter caseconstraining_clause(constraining_clause object)
      {
        return createconstraining_clauseAdapter();
      }
      @Override
      public Adapter caseElement(Element object)
      {
        return createElementAdapter();
      }
      @Override
      public Adapter caseImportClause(ImportClause object)
      {
        return createImportClauseAdapter();
      }
      @Override
      public Adapter caseExtendsClause(ExtendsClause object)
      {
        return createExtendsClauseAdapter();
      }
      @Override
      public Adapter caseBreak(Break object)
      {
        return createBreakAdapter();
      }
      @Override
      public Adapter caseGeneralClause(GeneralClause object)
      {
        return createGeneralClauseAdapter();
      }
      @Override
      public Adapter caseComponent_declaration(Component_declaration object)
      {
        return createComponent_declarationAdapter();
      }
      @Override
      public Adapter caseExternalElement(ExternalElement object)
      {
        return createExternalElementAdapter();
      }
      @Override
      public Adapter caseNULLElement(NULLElement object)
      {
        return createNULLElementAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.Stored_definition <em>Stored definition</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.Stored_definition
   * @generated
   */
  public Adapter createStored_definitionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.Class_definition <em>Class definition</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.Class_definition
   * @generated
   */
  public Adapter createClass_definitionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.class_prefixes <em>class prefixes</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.class_prefixes
   * @generated
   */
  public Adapter createclass_prefixesAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.class_specifier <em>class specifier</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.class_specifier
   * @generated
   */
  public Adapter createclass_specifierAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.long_class_specifier <em>long class specifier</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.long_class_specifier
   * @generated
   */
  public Adapter createlong_class_specifierAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.short_class_specifier <em>short class specifier</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.short_class_specifier
   * @generated
   */
  public Adapter createshort_class_specifierAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.der_class_specifier <em>der class specifier</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.der_class_specifier
   * @generated
   */
  public Adapter createder_class_specifierAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.class_name <em>class name</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.class_name
   * @generated
   */
  public Adapter createclass_nameAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.class_modification <em>class modification</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.class_modification
   * @generated
   */
  public Adapter createclass_modificationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.description_string <em>description string</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.description_string
   * @generated
   */
  public Adapter createdescription_stringAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.composition <em>composition</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.composition
   * @generated
   */
  public Adapter createcompositionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.type_specifier <em>type specifier</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.type_specifier
   * @generated
   */
  public Adapter createtype_specifierAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.enum_list <em>enum list</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.enum_list
   * @generated
   */
  public Adapter createenum_listAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.EnumerationLiteral <em>Enumeration Literal</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.EnumerationLiteral
   * @generated
   */
  public Adapter createEnumerationLiteralAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.description <em>description</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.description
   * @generated
   */
  public Adapter createdescriptionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.Argument <em>Argument</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.Argument
   * @generated
   */
  public Adapter createArgumentAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.element_modification <em>element modification</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.element_modification
   * @generated
   */
  public Adapter createelement_modificationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.element_replaceable <em>element replaceable</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.element_replaceable
   * @generated
   */
  public Adapter createelement_replaceableAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.short_class_definition <em>short class definition</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.short_class_definition
   * @generated
   */
  public Adapter createshort_class_definitionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.component_clause1 <em>component clause1</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.component_clause1
   * @generated
   */
  public Adapter createcomponent_clause1Adapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.type_prefix <em>type prefix</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.type_prefix
   * @generated
   */
  public Adapter createtype_prefixAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.component_declaration1 <em>component declaration1</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.component_declaration1
   * @generated
   */
  public Adapter createcomponent_declaration1Adapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.declaration <em>declaration</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.declaration
   * @generated
   */
  public Adapter createdeclarationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.array_subscripts <em>array subscripts</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.array_subscripts
   * @generated
   */
  public Adapter createarray_subscriptsAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.Unfinished2 <em>Unfinished2</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.Unfinished2
   * @generated
   */
  public Adapter createUnfinished2Adapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.modification <em>modification</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.modification
   * @generated
   */
  public Adapter createmodificationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.constraining_clause <em>constraining clause</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.constraining_clause
   * @generated
   */
  public Adapter createconstraining_clauseAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.Element
   * @generated
   */
  public Adapter createElementAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.ImportClause <em>Import Clause</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.ImportClause
   * @generated
   */
  public Adapter createImportClauseAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.ExtendsClause <em>Extends Clause</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.ExtendsClause
   * @generated
   */
  public Adapter createExtendsClauseAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.Break <em>Break</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.Break
   * @generated
   */
  public Adapter createBreakAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.GeneralClause <em>General Clause</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.GeneralClause
   * @generated
   */
  public Adapter createGeneralClauseAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.Component_declaration <em>Component declaration</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.Component_declaration
   * @generated
   */
  public Adapter createComponent_declarationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.ExternalElement <em>External Element</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.ExternalElement
   * @generated
   */
  public Adapter createExternalElementAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link dut.control.moloc.mOloc.NULLElement <em>NULL Element</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see dut.control.moloc.mOloc.NULLElement
   * @generated
   */
  public Adapter createNULLElementAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //MOlocAdapterFactory
