/**
 * generated by Xtext 2.38.0
 */
package dut.control.moloc.mOloc.util;

import dut.control.moloc.mOloc.*;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.util.Switch;

/**
 * <!-- begin-user-doc -->
 * The <b>Switch</b> for the model's inheritance hierarchy.
 * It supports the call {@link #doSwitch(EObject) doSwitch(object)}
 * to invoke the <code>caseXXX</code> method for each class of the model,
 * starting with the actual class of the object
 * and proceeding up the inheritance hierarchy
 * until a non-null result is returned,
 * which is the result of the switch.
 * <!-- end-user-doc -->
 * @see dut.control.moloc.mOloc.MOlocPackage
 * @generated
 */
public class MOlocSwitch<T> extends Switch<T>
{
  /**
   * The cached model package
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static MOlocPackage modelPackage;

  /**
   * Creates an instance of the switch.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MOlocSwitch()
  {
    if (modelPackage == null)
    {
      modelPackage = MOlocPackage.eINSTANCE;
    }
  }

  /**
   * Checks whether this is a switch for the given package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param ePackage the package in question.
   * @return whether this is a switch for the given package.
   * @generated
   */
  @Override
  protected boolean isSwitchFor(EPackage ePackage)
  {
    return ePackage == modelPackage;
  }

  /**
   * Calls <code>caseXXX</code> for each class of the model until one returns a non null result; it yields that result.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the first non-null result returned by a <code>caseXXX</code> call.
   * @generated
   */
  @Override
  protected T doSwitch(int classifierID, EObject theEObject)
  {
    switch (classifierID)
    {
      case MOlocPackage.STORED_DEFINITION:
      {
        Stored_definition stored_definition = (Stored_definition)theEObject;
        T result = caseStored_definition(stored_definition);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.CLASS_DEFINITION:
      {
        Class_definition class_definition = (Class_definition)theEObject;
        T result = caseClass_definition(class_definition);
        if (result == null) result = caseclass_prefixes(class_definition);
        if (result == null) result = caseclass_specifier(class_definition);
        if (result == null) result = caselong_class_specifier(class_definition);
        if (result == null) result = caseshort_class_specifier(class_definition);
        if (result == null) result = caseder_class_specifier(class_definition);
        if (result == null) result = caseclass_name(class_definition);
        if (result == null) result = casecomposition(class_definition);
        if (result == null) result = casetype_specifier(class_definition);
        if (result == null) result = casearray_subscripts(class_definition);
        if (result == null) result = caseenum_list(class_definition);
        if (result == null) result = casedescription(class_definition);
        if (result == null) result = caseclass_modification(class_definition);
        if (result == null) result = casedescription_string(class_definition);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.CLASS_PREFIXES:
      {
        class_prefixes class_prefixes = (class_prefixes)theEObject;
        T result = caseclass_prefixes(class_prefixes);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.CLASS_SPECIFIER:
      {
        class_specifier class_specifier = (class_specifier)theEObject;
        T result = caseclass_specifier(class_specifier);
        if (result == null) result = caselong_class_specifier(class_specifier);
        if (result == null) result = caseshort_class_specifier(class_specifier);
        if (result == null) result = caseder_class_specifier(class_specifier);
        if (result == null) result = caseclass_name(class_specifier);
        if (result == null) result = casecomposition(class_specifier);
        if (result == null) result = casetype_specifier(class_specifier);
        if (result == null) result = casearray_subscripts(class_specifier);
        if (result == null) result = caseenum_list(class_specifier);
        if (result == null) result = casedescription(class_specifier);
        if (result == null) result = caseclass_modification(class_specifier);
        if (result == null) result = casedescription_string(class_specifier);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.LONG_CLASS_SPECIFIER:
      {
        long_class_specifier long_class_specifier = (long_class_specifier)theEObject;
        T result = caselong_class_specifier(long_class_specifier);
        if (result == null) result = caseclass_name(long_class_specifier);
        if (result == null) result = caseclass_modification(long_class_specifier);
        if (result == null) result = casedescription_string(long_class_specifier);
        if (result == null) result = casecomposition(long_class_specifier);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.SHORT_CLASS_SPECIFIER:
      {
        short_class_specifier short_class_specifier = (short_class_specifier)theEObject;
        T result = caseshort_class_specifier(short_class_specifier);
        if (result == null) result = caseclass_name(short_class_specifier);
        if (result == null) result = casetype_specifier(short_class_specifier);
        if (result == null) result = casearray_subscripts(short_class_specifier);
        if (result == null) result = caseenum_list(short_class_specifier);
        if (result == null) result = casedescription(short_class_specifier);
        if (result == null) result = caseclass_modification(short_class_specifier);
        if (result == null) result = casedescription_string(short_class_specifier);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.DER_CLASS_SPECIFIER:
      {
        der_class_specifier der_class_specifier = (der_class_specifier)theEObject;
        T result = caseder_class_specifier(der_class_specifier);
        if (result == null) result = caseclass_name(der_class_specifier);
        if (result == null) result = casetype_specifier(der_class_specifier);
        if (result == null) result = casedescription(der_class_specifier);
        if (result == null) result = casedescription_string(der_class_specifier);
        if (result == null) result = caseclass_modification(der_class_specifier);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.CLASS_NAME:
      {
        class_name class_name = (class_name)theEObject;
        T result = caseclass_name(class_name);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.CLASS_MODIFICATION:
      {
        class_modification class_modification = (class_modification)theEObject;
        T result = caseclass_modification(class_modification);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.DESCRIPTION_STRING:
      {
        description_string description_string = (description_string)theEObject;
        T result = casedescription_string(description_string);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.COMPOSITION:
      {
        composition composition = (composition)theEObject;
        T result = casecomposition(composition);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.TYPE_SPECIFIER:
      {
        type_specifier type_specifier = (type_specifier)theEObject;
        T result = casetype_specifier(type_specifier);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.ENUM_LIST:
      {
        enum_list enum_list = (enum_list)theEObject;
        T result = caseenum_list(enum_list);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.ENUMERATION_LITERAL:
      {
        EnumerationLiteral enumerationLiteral = (EnumerationLiteral)theEObject;
        T result = caseEnumerationLiteral(enumerationLiteral);
        if (result == null) result = casedescription(enumerationLiteral);
        if (result == null) result = casedescription_string(enumerationLiteral);
        if (result == null) result = caseclass_modification(enumerationLiteral);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.DESCRIPTION:
      {
        description description = (description)theEObject;
        T result = casedescription(description);
        if (result == null) result = casedescription_string(description);
        if (result == null) result = caseclass_modification(description);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.ARGUMENT:
      {
        Argument argument = (Argument)theEObject;
        T result = caseArgument(argument);
        if (result == null) result = caseshort_class_definition(argument);
        if (result == null) result = casecomponent_clause1(argument);
        if (result == null) result = caseelement_modification(argument);
        if (result == null) result = caseconstraining(argument);
        if (result == null) result = caseclass_prefixes(argument);
        if (result == null) result = caseshort_class_specifier(argument);
        if (result == null) result = casetype_prefix(argument);
        if (result == null) result = casecomponent_declaration1(argument);
        if (result == null) result = caseclass_name(argument);
        if (result == null) result = casetype_specifier(argument);
        if (result == null) result = caseenum_list(argument);
        if (result == null) result = casedescription(argument);
        if (result == null) result = casedeclaration(argument);
        if (result == null) result = casearray_subscripts(argument);
        if (result == null) result = casedescription_string(argument);
        if (result == null) result = casemodification(argument);
        if (result == null) result = caseclass_modification(argument);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.ELEMENT_MODIFICATION:
      {
        element_modification element_modification = (element_modification)theEObject;
        T result = caseelement_modification(element_modification);
        if (result == null) result = casemodification(element_modification);
        if (result == null) result = casedescription_string(element_modification);
        if (result == null) result = caseclass_modification(element_modification);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.SHORT_CLASS_DEFINITION:
      {
        short_class_definition short_class_definition = (short_class_definition)theEObject;
        T result = caseshort_class_definition(short_class_definition);
        if (result == null) result = caseclass_prefixes(short_class_definition);
        if (result == null) result = caseshort_class_specifier(short_class_definition);
        if (result == null) result = caseclass_name(short_class_definition);
        if (result == null) result = casetype_specifier(short_class_definition);
        if (result == null) result = casearray_subscripts(short_class_definition);
        if (result == null) result = caseenum_list(short_class_definition);
        if (result == null) result = casedescription(short_class_definition);
        if (result == null) result = caseclass_modification(short_class_definition);
        if (result == null) result = casedescription_string(short_class_definition);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.COMPONENT_CLAUSE1:
      {
        component_clause1 component_clause1 = (component_clause1)theEObject;
        T result = casecomponent_clause1(component_clause1);
        if (result == null) result = casetype_prefix(component_clause1);
        if (result == null) result = casetype_specifier(component_clause1);
        if (result == null) result = casecomponent_declaration1(component_clause1);
        if (result == null) result = casedeclaration(component_clause1);
        if (result == null) result = casedescription(component_clause1);
        if (result == null) result = casearray_subscripts(component_clause1);
        if (result == null) result = casemodification(component_clause1);
        if (result == null) result = casedescription_string(component_clause1);
        if (result == null) result = caseclass_modification(component_clause1);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.TYPE_PREFIX:
      {
        type_prefix type_prefix = (type_prefix)theEObject;
        T result = casetype_prefix(type_prefix);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.COMPONENT_DECLARATION1:
      {
        component_declaration1 component_declaration1 = (component_declaration1)theEObject;
        T result = casecomponent_declaration1(component_declaration1);
        if (result == null) result = casedeclaration(component_declaration1);
        if (result == null) result = casedescription(component_declaration1);
        if (result == null) result = casearray_subscripts(component_declaration1);
        if (result == null) result = casemodification(component_declaration1);
        if (result == null) result = casedescription_string(component_declaration1);
        if (result == null) result = caseclass_modification(component_declaration1);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.DECLARATION:
      {
        declaration declaration = (declaration)theEObject;
        T result = casedeclaration(declaration);
        if (result == null) result = casearray_subscripts(declaration);
        if (result == null) result = casemodification(declaration);
        if (result == null) result = caseclass_modification(declaration);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.ARRAY_SUBSCRIPTS:
      {
        array_subscripts array_subscripts = (array_subscripts)theEObject;
        T result = casearray_subscripts(array_subscripts);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.MODIFICATION:
      {
        modification modification = (modification)theEObject;
        T result = casemodification(modification);
        if (result == null) result = caseclass_modification(modification);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.CONSTRAINING:
      {
        constraining constraining = (constraining)theEObject;
        T result = caseconstraining(constraining);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.CONSTRAINING_CLAUSE:
      {
        ConstrainingClause constrainingClause = (ConstrainingClause)theEObject;
        T result = caseConstrainingClause(constrainingClause);
        if (result == null) result = casetype_specifier(constrainingClause);
        if (result == null) result = caseclass_modification(constrainingClause);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.ELEMENT:
      {
        Element element = (Element)theEObject;
        T result = caseElement(element);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.IMPORT_CLAUSE:
      {
        ImportClause importClause = (ImportClause)theEObject;
        T result = caseImportClause(importClause);
        if (result == null) result = caseElement(importClause);
        if (result == null) result = casedescription(importClause);
        if (result == null) result = casedescription_string(importClause);
        if (result == null) result = caseclass_modification(importClause);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.EXTENDS_CLAUSE:
      {
        ExtendsClause extendsClause = (ExtendsClause)theEObject;
        T result = caseExtendsClause(extendsClause);
        if (result == null) result = caseElement(extendsClause);
        if (result == null) result = casetype_specifier(extendsClause);
        if (result == null) result = caseclass_modification(extendsClause);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.BREAK:
      {
        Break break_ = (Break)theEObject;
        T result = caseBreak(break_);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.GENERAL_CLAUSE:
      {
        GeneralClause generalClause = (GeneralClause)theEObject;
        T result = caseGeneralClause(generalClause);
        if (result == null) result = caseElement(generalClause);
        if (result == null) result = caseclass_prefixes(generalClause);
        if (result == null) result = caseclass_specifier(generalClause);
        if (result == null) result = casetype_prefix(generalClause);
        if (result == null) result = caseconstraining(generalClause);
        if (result == null) result = caselong_class_specifier(generalClause);
        if (result == null) result = caseshort_class_specifier(generalClause);
        if (result == null) result = caseder_class_specifier(generalClause);
        if (result == null) result = caseclass_name(generalClause);
        if (result == null) result = casecomposition(generalClause);
        if (result == null) result = casetype_specifier(generalClause);
        if (result == null) result = casearray_subscripts(generalClause);
        if (result == null) result = caseenum_list(generalClause);
        if (result == null) result = casedescription(generalClause);
        if (result == null) result = caseclass_modification(generalClause);
        if (result == null) result = casedescription_string(generalClause);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.COMPONENT_DECLARATION:
      {
        Component_declaration component_declaration = (Component_declaration)theEObject;
        T result = caseComponent_declaration(component_declaration);
        if (result == null) result = casedeclaration(component_declaration);
        if (result == null) result = casedescription(component_declaration);
        if (result == null) result = casearray_subscripts(component_declaration);
        if (result == null) result = casemodification(component_declaration);
        if (result == null) result = casedescription_string(component_declaration);
        if (result == null) result = caseclass_modification(component_declaration);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.EXTERNAL_ELEMENT:
      {
        ExternalElement externalElement = (ExternalElement)theEObject;
        T result = caseExternalElement(externalElement);
        if (result == null) result = caseElement(externalElement);
        if (result == null) result = caseclass_modification(externalElement);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.ANNOTATION_CLAUSE:
      {
        AnnotationClause annotationClause = (AnnotationClause)theEObject;
        T result = caseAnnotationClause(annotationClause);
        if (result == null) result = caseElement(annotationClause);
        if (result == null) result = caseclass_modification(annotationClause);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.EQUATION_SECTION:
      {
        EquationSection equationSection = (EquationSection)theEObject;
        T result = caseEquationSection(equationSection);
        if (result == null) result = caseElement(equationSection);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.EQUATION:
      {
        Equation equation = (Equation)theEObject;
        T result = caseEquation(equation);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.SIMPLE_EQUATION:
      {
        SimpleEquation simpleEquation = (SimpleEquation)theEObject;
        T result = caseSimpleEquation(simpleEquation);
        if (result == null) result = caseEquation(simpleEquation);
        if (result == null) result = casedescription(simpleEquation);
        if (result == null) result = casedescription_string(simpleEquation);
        if (result == null) result = caseclass_modification(simpleEquation);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.IF_EQUATION:
      {
        IfEquation ifEquation = (IfEquation)theEObject;
        T result = caseIfEquation(ifEquation);
        if (result == null) result = caseEquation(ifEquation);
        if (result == null) result = casedescription(ifEquation);
        if (result == null) result = casedescription_string(ifEquation);
        if (result == null) result = caseclass_modification(ifEquation);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.FOR_EQUATION:
      {
        ForEquation forEquation = (ForEquation)theEObject;
        T result = caseForEquation(forEquation);
        if (result == null) result = caseEquation(forEquation);
        if (result == null) result = casedescription(forEquation);
        if (result == null) result = casedescription_string(forEquation);
        if (result == null) result = caseclass_modification(forEquation);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.CONNECT_EQUATION:
      {
        ConnectEquation connectEquation = (ConnectEquation)theEObject;
        T result = caseConnectEquation(connectEquation);
        if (result == null) result = caseEquation(connectEquation);
        if (result == null) result = casedescription(connectEquation);
        if (result == null) result = casedescription_string(connectEquation);
        if (result == null) result = caseclass_modification(connectEquation);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.WHEN_EQUATION:
      {
        WhenEquation whenEquation = (WhenEquation)theEObject;
        T result = caseWhenEquation(whenEquation);
        if (result == null) result = caseEquation(whenEquation);
        if (result == null) result = casedescription(whenEquation);
        if (result == null) result = casedescription_string(whenEquation);
        if (result == null) result = caseclass_modification(whenEquation);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.FUNCTION_EQUATION:
      {
        FunctionEquation functionEquation = (FunctionEquation)theEObject;
        T result = caseFunctionEquation(functionEquation);
        if (result == null) result = caseEquation(functionEquation);
        if (result == null) result = casedescription(functionEquation);
        if (result == null) result = casedescription_string(functionEquation);
        if (result == null) result = caseclass_modification(functionEquation);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.ALGORITHM_SECTION:
      {
        AlgorithmSection algorithmSection = (AlgorithmSection)theEObject;
        T result = caseAlgorithmSection(algorithmSection);
        if (result == null) result = caseElement(algorithmSection);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.STATEMENT:
      {
        Statement statement = (Statement)theEObject;
        T result = caseStatement(statement);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.FUNCTION_STATEMENT:
      {
        FunctionStatement functionStatement = (FunctionStatement)theEObject;
        T result = caseFunctionStatement(functionStatement);
        if (result == null) result = caseStatement(functionStatement);
        if (result == null) result = casedescription(functionStatement);
        if (result == null) result = casedescription_string(functionStatement);
        if (result == null) result = caseclass_modification(functionStatement);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.BREAK_STATEMENT:
      {
        BreakStatement breakStatement = (BreakStatement)theEObject;
        T result = caseBreakStatement(breakStatement);
        if (result == null) result = caseStatement(breakStatement);
        if (result == null) result = casedescription(breakStatement);
        if (result == null) result = casedescription_string(breakStatement);
        if (result == null) result = caseclass_modification(breakStatement);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.RETURN_STATEMENT:
      {
        ReturnStatement returnStatement = (ReturnStatement)theEObject;
        T result = caseReturnStatement(returnStatement);
        if (result == null) result = caseStatement(returnStatement);
        if (result == null) result = casedescription(returnStatement);
        if (result == null) result = casedescription_string(returnStatement);
        if (result == null) result = caseclass_modification(returnStatement);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.IF_STATEMENT:
      {
        IfStatement ifStatement = (IfStatement)theEObject;
        T result = caseIfStatement(ifStatement);
        if (result == null) result = caseStatement(ifStatement);
        if (result == null) result = casedescription(ifStatement);
        if (result == null) result = casedescription_string(ifStatement);
        if (result == null) result = caseclass_modification(ifStatement);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.FOR_STATEMENT:
      {
        ForStatement forStatement = (ForStatement)theEObject;
        T result = caseForStatement(forStatement);
        if (result == null) result = caseStatement(forStatement);
        if (result == null) result = casedescription(forStatement);
        if (result == null) result = casedescription_string(forStatement);
        if (result == null) result = caseclass_modification(forStatement);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.WHEN_STATEMENT:
      {
        WhenStatement whenStatement = (WhenStatement)theEObject;
        T result = caseWhenStatement(whenStatement);
        if (result == null) result = caseStatement(whenStatement);
        if (result == null) result = casedescription(whenStatement);
        if (result == null) result = casedescription_string(whenStatement);
        if (result == null) result = caseclass_modification(whenStatement);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MOlocPackage.WHILE_STATEMENT:
      {
        WhileStatement whileStatement = (WhileStatement)theEObject;
        T result = caseWhileStatement(whileStatement);
        if (result == null) result = caseStatement(whileStatement);
        if (result == null) result = casedescription(whileStatement);
        if (result == null) result = casedescription_string(whileStatement);
        if (result == null) result = caseclass_modification(whileStatement);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      default: return defaultCase(theEObject);
    }
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Stored definition</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Stored definition</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseStored_definition(Stored_definition object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Class definition</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Class definition</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseClass_definition(Class_definition object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>class prefixes</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>class prefixes</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseclass_prefixes(class_prefixes object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>class specifier</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>class specifier</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseclass_specifier(class_specifier object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>long class specifier</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>long class specifier</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caselong_class_specifier(long_class_specifier object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>short class specifier</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>short class specifier</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseshort_class_specifier(short_class_specifier object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>der class specifier</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>der class specifier</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseder_class_specifier(der_class_specifier object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>class name</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>class name</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseclass_name(class_name object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>class modification</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>class modification</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseclass_modification(class_modification object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>description string</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>description string</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casedescription_string(description_string object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>composition</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>composition</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casecomposition(composition object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>type specifier</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>type specifier</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casetype_specifier(type_specifier object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>enum list</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>enum list</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseenum_list(enum_list object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Enumeration Literal</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Enumeration Literal</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEnumerationLiteral(EnumerationLiteral object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>description</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>description</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casedescription(description object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Argument</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Argument</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseArgument(Argument object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>element modification</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>element modification</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseelement_modification(element_modification object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>short class definition</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>short class definition</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseshort_class_definition(short_class_definition object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>component clause1</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>component clause1</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casecomponent_clause1(component_clause1 object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>type prefix</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>type prefix</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casetype_prefix(type_prefix object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>component declaration1</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>component declaration1</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casecomponent_declaration1(component_declaration1 object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>declaration</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>declaration</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casedeclaration(declaration object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>array subscripts</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>array subscripts</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casearray_subscripts(array_subscripts object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>modification</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>modification</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casemodification(modification object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>constraining</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>constraining</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseconstraining(constraining object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Constraining Clause</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Constraining Clause</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseConstrainingClause(ConstrainingClause object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Element</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Element</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseElement(Element object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Import Clause</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Import Clause</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseImportClause(ImportClause object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Extends Clause</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Extends Clause</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExtendsClause(ExtendsClause object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Break</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Break</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBreak(Break object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>General Clause</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>General Clause</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseGeneralClause(GeneralClause object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Component declaration</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Component declaration</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseComponent_declaration(Component_declaration object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>External Element</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>External Element</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExternalElement(ExternalElement object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Annotation Clause</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Annotation Clause</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAnnotationClause(AnnotationClause object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Equation Section</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Equation Section</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEquationSection(EquationSection object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Equation</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Equation</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEquation(Equation object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Simple Equation</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Simple Equation</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSimpleEquation(SimpleEquation object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>If Equation</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>If Equation</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseIfEquation(IfEquation object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>For Equation</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>For Equation</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseForEquation(ForEquation object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Connect Equation</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Connect Equation</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseConnectEquation(ConnectEquation object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>When Equation</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>When Equation</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseWhenEquation(WhenEquation object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Function Equation</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Function Equation</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseFunctionEquation(FunctionEquation object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Algorithm Section</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Algorithm Section</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAlgorithmSection(AlgorithmSection object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Statement</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Statement</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseStatement(Statement object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Function Statement</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Function Statement</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseFunctionStatement(FunctionStatement object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Break Statement</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Break Statement</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBreakStatement(BreakStatement object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Return Statement</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Return Statement</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseReturnStatement(ReturnStatement object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>If Statement</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>If Statement</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseIfStatement(IfStatement object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>For Statement</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>For Statement</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseForStatement(ForStatement object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>When Statement</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>When Statement</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseWhenStatement(WhenStatement object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>While Statement</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>While Statement</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseWhileStatement(WhileStatement object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EObject</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch, but this is the last case anyway.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EObject</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject)
   * @generated
   */
  @Override
  public T defaultCase(EObject object)
  {
    return null;
  }

} //MOlocSwitch
