//grammar dut.control.moloc.MOloc with org.eclipse.xtext.common.Terminals
grammar dut.control.moloc.MOloc hidden(WS, ML_COMMENT, SL_COMMENT)

generate mOloc "http://www.control.dut/moloc/MOloc"

import "http://www.eclipse.org/emf/2002/Ecore" as Ecore

//-----------------------------------------------
// B.2.1 Stored Definition
//-----------------------------------------------

Stored_definition:
	( isWithin?='within' within=Name ';')?
	( classes += Class_definition )*
;

//-----------------------------------------------
// B.2.2 Class Definition
//-----------------------------------------------

Class_definition:
	( isfinal ?= 'final' )?
	( isEncapsulated ?= 'encapsulated' )?
	class_prefixes
	class_specifier
	';'
;

fragment class_prefixes :
	( isPartial ?= 'partial')? 
	( isExpandable ?= 'expandable' )?
	( isPure ?= 'pure' | isPure ?= 'impure' )?
	( isOperator ?= 'operator' )?
	classType=ClassType
;

enum ClassType:
	null='NULLClassType' | Class='class' | Model='model' | Record='record' | Block='block' | Connector='connector' | Type='type' 
	| Package='package' | Function='function'
;

fragment class_specifier:
	long_class_specifier 
	| short_class_specifier 
	| der_class_specifier
;

fragment long_class_specifier:
	( isExtends ?= 'extends' )?
	class_name
	class_modification? 
	description_string
	composition 
	'end' IDENT
;

fragment short_class_specifier:
	class_name 
	'=' 
	( direction=Direction type_specifier class_modification? 
	 | (isEnumeration ?= 'enumeration')? '(' ( enum_list? | isColon ?= ':') ')'
	)
	description
;

fragment der_class_specifier:
	class_name
	'='
	isDer?='def'
	'(' type_specifier ',' derName+=IDENT (',' derName+=IDENT)* ')'
	description
;

fragment class_name:
	className=IDENT 
;

fragment class_modification:
	'(' arguments+=Argument ( ',' arguments+=Argument )* ')'
;

fragment description_string:
	( description = DescriptionString )?
;

DescriptionString:
	STRING ( '+' STRING )*
;

fragment composition:
	( elements += Element )* 
;

enum Direction:
	null='NULLDirection'| input='input' | output='output'
;

fragment type_specifier:
	typeSpecifier = TypeSpecifier
;

TypeSpecifier:
	('.')? Name
;
fragment enum_list:
	enumerationLiteral+=EnumerationLiteral (',' enumerationLiteral+=EnumerationLiteral)*
;

EnumerationLiteral:
	title=IDENT
	description
;

fragment description:
	description_string ( isAnnotation ?= 'annotation' class_modification)?
;

Argument:
	( isRedeclare ?= 'redeclare')?
	( isEach ?= 'each' )?
	( isfinal ?= 'final' )?
//	( short_class_definition 
//	| component_clause1 
//	| element_modification 
//	| element_replaceable
//	)
	short_class_definition
;

fragment element_modification:
	elementName=Name modification description_string
;

fragment element_replaceable:
	( isReplaceable ?= 'replaceable' )? 
	( short_class_definition | component_clause1 )
	( constraining_clause )?
;

fragment short_class_definition:
	class_prefixes short_class_specifier
;

fragment component_clause1:
	type_prefix type_specifier component_declaration1
;

fragment type_prefix:
	( relationshipType = RelationshipType )?
	( parameterType = ParameterType )?
	( directionType = Direction )?
;

enum RelationshipType:
	null='NULLRelationshipType' | flow = 'flow' | stream  = 'stream'
;

enum ParameterType:
	null='NULLParameterType' | discrete = 'discrete' | parameter = 'parameter' | constant = 'constant'
;

fragment component_declaration1:
	declaration description
;

fragment declaration:
	declarationName=IDENT array_subscripts? modification?
;

fragment array_subscripts:
	'[' subscript+=Subscript (',' subscript+=Subscript)* ']'
;

Subscript:
	':' | Expression
;

Unfinished2:
	'Unfinished2' aa=Name
;

fragment modification:
	class_modification ('=' expression=Modification_expression)?
	| '=' expression=Modification_expression
	| ':=' expression=Modification_expression
;

Modification_expression:
	Expression | 'break'
;

fragment constraining_clause:
	elements2+=Unfinished2
;


Element:
	ImportClause 
	| ExtendsClause 
	| GeneralClause 
	| ExternalElement 
;

ImportClause:
	'import' 
	( selfName=IDENT '=' importName=Name
	| importName=Name ( isImportAll?='.*' | '.' ( isImportAll?='*' | '{' objectName+=IDENT ( ',' objectName+=IDENT)* '}'))
	)
	description
	';'
;

ExtendsClause:
	'extends' 
	type_specifier 
	( '(' ( arguments+=Argument | breaks+=Break ) (',' ( arguments+=Argument | breaks+=Break ) )* ')')?
	( isAnnotation?='annotation' class_modification )?
	';'
;

Break:
	'break'
	( connect=NULLElement
	| breakName=IDENT
	)
;

GeneralClause:
	( isRedeclare ?= 'redeclare' )?
	( isfinal ?= 'final' )?
	( isInner ?= 'inner' )?
	( isOuter ?= 'outer' )?
	( isReplaceable ?= 'replaceable' )?
	type_prefix
	//[type_specifier]Decision can match input such as "'.' RULE_IDENT" using multiple alternatives: 1, 2
	type_specifier
	//	typeSpecifier = Name
	array_subscripts?
	component_list+=Component_declaration (',' component_list+=Component_declaration)*
	';'
;

Component_declaration:
	declaration
	('if' condition_attribute=Expression)?
	description
;

ExternalElement:
	{ExternalElement} 
	'external' 
	(language_specification=STRING)?
	//[fatal] rule ruleTerm has non-LL(*) decision due to recursive rule invocations reachable from alts 1,2.
	( ref=Component_reference )?
	( isAnnotation?='annotation' class_modification )?
	';'
;


NULLElement:
	'nullElement'
	nullname=Name
;


Expression:
	Simple_expression
	| 'if' Expression 'then' Expression ( 'elseif' Expression 'then' Expression )* 'else' Expression
;

Simple_expression:
	Logical_expression ( ':' Logical_expression (':' Logical_expression))?
;

Logical_expression:
	Logical_term ('or' Logical_term)*
;

Logical_term:
	Logical_factor ('and' Logical_factor)*
;

Logical_factor:
	'not'? Relation 
;

Relation:
	Arithmetic_expression ( ('<' | '<=' | '>' | '>=' | '==' | '<>') Arithmetic_expression)?
;

//[fatal] rule ruleTerm has non-LL(*) decision due to recursive rule invocations reachable from alts 1,2.
Arithmetic_expression:
	( '+' | '-' | '.+' | '.-' )? Term ( ( '+' | '-' | '.+' | '.-' ) Term)*
;

Term:
	Factor ( ('*' | '/' | '.*' | '.-') Factor)*
;

Factor:
	Primary ( ('^' | '.^') Primary)?
;

Primary:
	UNSIGNED_NUMBER
	| STRING
	| TRUE_FALSE
//	| ( Component_reference | 'der' | 'initial' | 'pure' ) Function_call_args
	| Component_reference
	| '(' Expression? (',' Expression) ')'
	| '[' Expression (',' Expression) ']'
	| '{' ArrayArguments '}'
	| 'end'
;

ArrayArguments:
	Expression (',' ArrayArgumentsNonFirst | 'for' ForIndices)?
;

ArrayArgumentsNonFirst:
	Expression (',' ArrayArgumentsNonFirst)?
;

ForIndices:
	ForIndex (',' ForIndex)*
;

ForIndex:
	IDENT ('in' Expression)?
;

Component_reference:
	'.'? IDENT ('[' Subscript (',' Subscript)* ']')? ('.' IDENT ('[' Subscript (',' Subscript)* ']')?)*
;

Name:
	IDENT ("." IDENT)*
;


// terminals
terminal TRUE_FALSE returns Ecore::EBoolean:
	'true' | 'false'
;
terminal IDENT returns Ecore::EString:
	NON_DIGIT ( DIGIT | NON_DIGIT )* | Q_IDENT
;
terminal UNSIGNED_NUMBER returns Ecore::EFloat:
	UNSIGNED_INTEGER ( "." ( UNSIGNED_INTEGER )? )?
	( ( "e" | "E" ) ( "+" | "-" )? UNSIGNED_INTEGER )?
;
terminal STRING returns Ecore::EString:
	"\"" ( S_CHAR | S_ESCAPE )* "\""
;
terminal ML_COMMENT: '/*'->'*/';
terminal SL_COMMENT: '//' !('\n'|'\r')* ('\r'? '\n')?;
terminal WS: (' ' | '\t' | '\r' | '\n')+;
//terminal ANY_OTHER: .;

// terminal fragments
terminal DIGIT: "0".."9";
terminal UNSIGNED_INTEGER: DIGIT+;
terminal S_ESCAPE: "\\" ("'" | "\"" | "?" | "\\" | "a" | "b" | "f" | "n" | "r" | "t" | "v");
terminal Q_IDENT: "'" ( Q_CHAR | S_ESCAPE )* "'";
terminal NON_DIGIT: "_" | "a".."z" | "A".."Z";
terminal S_CHAR: !( "\"" | "\\");
terminal Q_CHAR: NON_DIGIT | DIGIT | "!" | "#" | "$" | "%" | "&" | "(" | ")" | "*" | "+" | "," |
	"-" | "." | "/" | ":" | ";" | "<" | ">" | "=" | "?" | "@" | "[" | "]" | "^" |
	"{" | "}" | "|" | "~" | " ";