grammar dut.control.moloc.MOloc hidden(WS, ML_COMMENT, SL_COMMENT)

generate mOloc "http://www.control.dut/moloc/MOloc"

import "http://www.eclipse.org/emf/2002/Ecore" as Ecore

Stored_definition:
	( isWithin?='within' within=Name ';')?
	( classes += Class_definition )*
;

Class_definition:
	( isfinal ?= 'final' )?
	class_prefixes
	class_specifier
	';'
;

fragment class_prefixes :
	( isEncapsulated ?= 'encapsulated' )?
	( isPartial ?= 'partial')? 
	( isExpandable ?= 'expandable' )?
	( isPure ?= 'pure' | isPure ?= 'impure' )?
	( isOperator ?= 'operator' )?
	classType=ClassType
;

enum ClassType:
	null='NULLClassType' | Class='class' | Model='model' | Record='record' | Block='block' | Connector='connector' | Type='type' 
	| Package='package' | Function='function'
;

fragment class_specifier:
	long_class_specifier 
	| short_class_specifier 
	| der_class_specifier
;

fragment long_class_specifier:
	( isExtends ?= 'extends' )?
	class_name
	class_modification? 
	description_string
	composition 
	'end' classNameEnd=IDENT
;

fragment short_class_specifier:
	class_name 
	'=' 
	( (direction=Direction)? type_specifier array_subscripts? class_modification? 
	 | isEnumeration?='enumeration' '(' ( enum_list? | isColon ?= ':') ')'
	)
	description
;

fragment der_class_specifier:
	class_name
	'='
	isDer?='der'
	'(' type_specifier ',' derName+=IDENT (',' derName+=IDENT)* ')'
	description
;

fragment class_name:
	className=IDENT 
;

fragment class_modification:
	'(' arguments+=Argument ( ',' arguments+=Argument )* ')'
;

fragment description_string:
	( description = DescriptionString )?
;

DescriptionString:
	STRING ( '+' STRING )*
;

fragment composition:
	( elements += Element )* 
;

enum Direction:
	null='NULLDirection'| input='input' | output='output'
;

fragment type_specifier:
	typeSpecifier = TypeSpecifier
;

TypeSpecifier:
	('.')? Name
;
fragment enum_list:
	enumerationLiteral+=EnumerationLiteral (',' enumerationLiteral+=EnumerationLiteral)*
;

EnumerationLiteral:
	title=IDENT
	description
;

fragment description:
	description_string ( isAnnotation?='annotation' class_modification)?
;

Argument:
	( isRedeclare ?= 'redeclare')?
	( isEach ?= 'each' )?
	( isfinal ?= 'final' )?
	( isReplaceable ?= 'replaceable' )? 
	( short_class_definition 
	| component_clause1 
	| element_modification 
	)
	constraining?
;

fragment element_modification:
	elementName=Name modification? description_string
;

fragment short_class_definition:
	class_prefixes short_class_specifier
;

fragment component_clause1:
	type_prefix type_specifier component_declaration1
;

fragment type_prefix:
	( relationshipType = RelationshipType )?
	( parameterType = ParameterType )?
	( directionType = Direction )?
;

enum RelationshipType:
	null='NULLRelationshipType' | flow = 'flow' | stream  = 'stream'
;

enum ParameterType:
	null='NULLParameterType' | discrete = 'discrete' | parameter = 'parameter' | constant = 'constant'
;

fragment component_declaration1:
	declaration description
;

fragment declaration:
	declarationName=IDENT array_subscripts? modification?
;

fragment array_subscripts:
	subscripts=ArraySubscripts
//	'[' subscript+=Subscript (',' subscript+=Subscript)* ']'
;

ArraySubscripts:
	'[' Subscript ( ',' Subscript )* ']'
;

Subscript:
	':' | Expression
;

fragment modification:
	class_modification ('=' expression=Modification_expression)?
	| '=' expression=Modification_expression
	| ':=' expression=Modification_expression
;

Modification_expression:
	Expression | 'break'
;

fragment constraining:
	constrain=ConstrainingClause
;

ConstrainingClause:
	'constrainedby'
	type_specifier
	class_modification
;

Element:
	ImportClause 
	| ExtendsClause 
	| GeneralClause 
	| ExternalElement 
	| AnnotationClause
	| EquationSection
	| AlgorithmSection
;

ImportClause:
	( isPublic ?= 'public' )?
	( isProtected ?= 'protected' )?
	'import' 
	( selfName=IDENT '=' importName=Name
	| importName=Name ( isImportAll?='.*' | '.' ( isImportAll?='*' | '{' objectName+=IDENT ( ',' objectName+=IDENT)* '}'))?
	)
	description
	';'
;

ExtendsClause:
	( isPublic ?= 'public' )?
	( isProtected ?= 'protected' )?
	'extends' 
	type_specifier 
	( '(' (( arguments+=Argument | breaks+=Break ) (',' ( arguments+=Argument | breaks+=Break ))* )? ')')?
	( 'annotation' class_modification )?
	';'
;

Break:
	'break'
	( connectObject=ConnectEquation
	| breakObject=IDENT
	)
;

GeneralClause:
	( isPublic ?= 'public' )?
	( isProtected ?= 'protected' )?
	( isRedeclare ?= 'redeclare' )?
	( isfinal ?= 'final' )?
	( isInner ?= 'inner' )?
	( isOuter ?= 'outer' )?
	( isReplaceable ?= 'replaceable' )?
	//[type_specifier]Decision can match input such as "'.' RULE_IDENT" using multiple alternatives: 1, 2
	( class_prefixes class_specifier
	| type_prefix type_specifier array_subscripts?
		component_list+=Component_declaration (',' component_list+=Component_declaration)*
	)
	constraining?
//	description?
	';'
;

Component_declaration:
	declaration
	('if' condition_attribute=Expression)?
	description
;

ExternalElement:
	{ExternalElement} 
	'external' 
	(language_specification=STRING)?
	//[fatal] rule ruleTerm has non-LL(*) decision due to recursive rule invocations reachable from alts 1,2.
	( (ref=Component_reference '=')? refValue=IDENT '(' (expressionList=ExpressionList)? ')')?
	( isAnnotation?='annotation' class_modification )?
	';'
;

AnnotationClause:
	'annotation' 
	class_modification 
	';'
;

EquationSection:
	{EquationSection} 
	( isInitial ?= 'initial' )?
	'equation'
	( equations += Equation )*
;

Equation:
	SimpleEquation
	| IfEquation
	| ForEquation
	| ConnectEquation
	| WhenEquation
	| FunctionEquation
;

SimpleEquation:
	left=Simple_expression
	'='
	right=Expression
	description
	';'
;

IfEquation:
	'if'
	condition=Expression
	'then'
	( ifEquations += Equation )*
	( 'elseif' elseCondition+=Expression 
		'then' ( elseifEquations += Equation )*
	)*
	( 'else' ( elseEquations += Equation )*)?
	'end' 'if' 
	description
	';'
;

ForEquation:
	'for'
	forIndices=ForIndices
	'loop'
	( forEquations += Equation )*
	'end' 'for' 
	description
	';'
;

ConnectEquation:
	'connect'
	'(' left=Component_reference ',' right=Component_reference ')'
	description
	';'
;

WhenEquation:
	'when'
	condition=Expression
	'then'
	( whenEquations += Equation )*
	( 'elsewhen' elseCondition+=Expression
		'then' ( elsewhenEquations += Equation )*
	)*
	'end' 'when' 
	description
	';'
;

FunctionEquation:
	component=Component_reference
	function=FunctionCallArgs
	description
	';'
;

AlgorithmSection:
	{AlgorithmSection} 
	( isInitial ?= 'initial' )?
	'algorithm'
	( statements += Statement )*
;

Statement:
	FunctionStatement
	| BreakStatement
	| ReturnStatement
	| IfStatement
	| ForStatement
	| WhenStatement
	| WhileStatement
;

FunctionStatement:
	( component=Component_reference ( ':=' expression=Expression | function=FunctionCallArgs )
	| '(' output=OutputExpressionList ')' ':=' component=Component_reference function=FunctionCallArgs
	)
	description
	';'
;

BreakStatement:
	'break'
	description
	';'
;

ReturnStatement:
	'return'
	description
	';'
;

IfStatement:
	'if'
	condition=Expression
	'then'
	( ifStatements += Statement )*
	( 'elseif' elseCondition+=Expression 
		'then' ( elseifStatements += Statement )*
	)*
	( 'else' ( elseStatements += Statement )*)?
	'end' 'if' 
	description
	';'
;

ForStatement:
	'for'
	forIndices=ForIndices
	'loop'
	( forStatements += Statement )*
	'end' 'for' 
	description
	';'
;

WhenStatement:
	'when'
	condition=Expression
	'then'
	( whenStatements += Statement )*
	( 'elsewhen' elseCondition+=Expression
		'then' ( whenStatements += Statement )*
	)*
	'end' 'when' 
	description
	';'
;

WhileStatement:
	'while'
	condition=Expression
	'loop'
	( whileStatements += Statement )*
	'end' 'while' 
	description
	';'
;

Expression:
	Simple_expression
	| 'if' Expression 'then' Expression ( 'elseif' Expression 'then' Expression )* 'else' Expression
;

Simple_expression:
	Logical_expression ( ':' Logical_expression (':' Logical_expression)?)?
;

Logical_expression:
	Logical_term ('or' Logical_term)*
;

Logical_term:
	Logical_factor ('and' Logical_factor)*
;

Logical_factor:
	'not'? Relation 
;

Relation:
	Arithmetic_expression ( ('<' | '<=' | '>' | '>=' | '==' | '<>') Arithmetic_expression)?
;

//[fatal] rule ruleTerm has non-LL(*) decision due to recursive rule invocations reachable from alts 1,2.
Arithmetic_expression:
	( '+' | '-' | '.+' | '.-' )? Term ( ( '+' | '-' | '.+' | '.-' ) Term)*
;

Term:
	Factor ( ('*' | '/' | '.*' | '.-') Factor)*
;

Factor:
	Primary ( ('^' | '.^') Primary)?
;

Primary:
	UNSIGNED_NUMBER
	| STRING
	| TRUE_FALSE
	| ( Component_reference | 'der' | 'initial' | 'pure' ) FunctionCallArgs
	| ResultReference
	| '(' OutputExpressionList ')'
	| '[' ExpressionList ( ';' ExpressionList )* ']'
	| '{' ArrayArguments '}'
	| 'end'
;

OutputExpressionList:
	Expression? (',' Expression? )*
;

ExpressionList:
	Expression (',' Expression)*
;

ArrayArguments:
	Expression (',' ArrayArgumentsNonFirst | 'for' ForIndices)?
;

ArrayArgumentsNonFirst:
	Expression (',' ArrayArgumentsNonFirst)?
;

ForIndices:
	ForIndex (',' ForIndex)*
;

ForIndex:
	IDENT ('in' Expression)?
;

Component_reference:
	'.'? IDENT ArraySubscripts? ('.' IDENT ArraySubscripts?)*
;

ResultReference:
	Component_reference
	| 'der' '(' Component_reference (',' UNSIGNED_NUMBER)? ')'
;

FunctionCallArgs:
	'(' FunctionArguments? ')'
;

FunctionArguments:
	Expression (',' FunctionArgumentsNonFirst | 'for' ForIndices)?
	| FunctionPartialApplication (',' FunctionArgumentsNonFirst)?
	| NamedArguments
;

FunctionArgumentsNonFirst:
	FunctionArguments (',' FunctionArgumentsNonFirst)?
	| NamedArguments
;

FunctionPartialApplication:
	'function' TypeSpecifier '(' NamedArguments ')'
;

NamedArguments:
	NamedArgument (',' NamedArguments)?
;

NamedArgument:
	IDENT '=' FunctionArgument
;

FunctionArgument:
	Expression | FunctionPartialApplication 
;

Name:
	IDENT ("." IDENT)*
;

// terminals
terminal TRUE_FALSE returns Ecore::EBoolean:
	'true' | 'false'
;

terminal IDENT returns Ecore::EString:
	NON_DIGIT ( DIGIT | NON_DIGIT )* | Q_IDENT
;

terminal UNSIGNED_NUMBER returns Ecore::EFloat:
	UNSIGNED_INTEGER ( "." ( UNSIGNED_INTEGER )? )?
	( ( "e" | "E" ) ( "+" | "-" )? UNSIGNED_INTEGER )?
;

terminal STRING returns Ecore::EString:
	"\"" ( S_CHAR | S_ESCAPE )* "\""
;

terminal ML_COMMENT: '/*'->'*/';
terminal SL_COMMENT: '//' !('\n'|'\r')* ('\r'? '\n')?;
terminal WS: (' ' | '\t' | '\r' | '\n')+;
//terminal ANY_OTHER: .;

// terminal fragments
terminal DIGIT: "0".."9";
terminal UNSIGNED_INTEGER: DIGIT+;
terminal S_ESCAPE: "\\" ("'" | "\"" | "?" | "\\" | "a" | "b" | "f" | "n" | "r" | "t" | "v");
terminal Q_IDENT: "'" ( Q_CHAR | S_ESCAPE )* "'";
terminal NON_DIGIT: "_" | "a".."z" | "A".."Z";
terminal S_CHAR: !( "\"" | "\\");
terminal Q_CHAR: NON_DIGIT | DIGIT | "!" | "#" | "$" | "%" | "&" | "(" | ")" | "*" | "+" | "," |
	"-" | "." | "/" | ":" | ";" | "<" | ">" | "=" | "?" | "@" | "[" | "]" | "^" |
	"{" | "}" | "|" | "~" | " ";