grammar dut.control.sysmloc.SysMLOC hidden(WS, ML_NOTE, SL_NOTE)

import "http://www.eclipse.org/emf/2002/Ecore" as Ecore

generate sysMLOC "http://www.control.dut/sysmloc/SysMLOC"
 
Namespace:
    (packages+=Package)*;

Package:
    'package' 
    declaredName=QualifiedName 
    '{' (elements+=BaseElement)* '}'
;

BaseElement:
    Package 
    | AnnotatingElement 
    | ImportElement
    | DefinitionElement
    | UsageElement
;

// Annotating

AnnotatingElement:
	Comment 
//	| Documentation
//	| TextualRepresentation
//	| MetadataUsage
;

// Importing

ImportElement:
	NamespaceImport
//	| MembershipImport
;

// Definitions

DefinitionElement:
	AttributeDefinition
//	| EnumerationDefinition
//	| OccurrenceDefinition
//	| IndividualDefinition
	| ItemDefinition
//	| MetadataDefinition
	| PartDefinition
	| ConnectionDefinition
	| FlowConnectionDefinition
	| InterfaceDefinition
//	| AllocationDefinition
	| PortDefinition
//	| ActionDefinition
//	| CalculationDefinition
//	| StateDefinition
//	| ConstraintDefinition
//	| RequirementDefinition
//	| ConcernDefinition
//	| CaseDefinition
//	| AnalysisCaseDefinition
//	| VerificationCaseDefinition
//	| UseCaseDefinition
//	| ViewDefinition
//	| ViewpointDefinition
//	| RenderingDefinition
//	| ExtendedDefinition
;

// Usages

UsageElement:
	NonOccurrenceUsageElement 
	| OccurrenceUsageElement
;

NonOccurrenceUsageElement:
	ReferenceUsage
	| AttributeUsage
//	| EnumerationUsage
//	| BindingConnectorAsUsage
//	| SuccessionAsUsage
//	| ExtendedUsage
	
;

OccurrenceUsageElement: 
	StructureUsageElement | BehaviorUsageElement
;

StructureUsageElement:
//	OccurrenceUsage
//	| IndividualUsage
//	| PortionUsage
//	| EventOccurrenceUsage
	ItemUsage
	| PartUsage
//	| ViewUsage
//	| RenderingUsage
	| PortUsage
	| ConnectionUsage
	| InterfaceUsage
//	| AllocationUsage
//	| Message
	| FlowConnectionUsage
//	| SuccessionFlowConnectionUsage
;
//
BehaviorUsageElement:
	ActionUsage
//	| CalculationUsage
//	| StateUsage
//	| ConstraintUsage
//	| RequirementUsage
//	| ConcernUsage
//	| CaseUsage
//	| AnalysisCaseUsage
//	| VerificationCaseUsage
//	| UseCaseUsage
//	| ViewpointUsage
//	| PerformActionUsage
//	| ExhibitStateUsage
//	| IncludeUseCaseUsage
//	| AssertConstraintUsage
//	| SatisfyRequirementUsage
;


NamespaceImport:
    visibility=VisibilityIndicator 'import' declaredName=QualifiedName '::' ( '*' | isRecursive ?= '**' )? ';'
;
    
Comment:
    'doc'? 
    body=REGULAR_COMMENT
;

ReferenceUsage:
    OccurrenceUsagePrefix Usage (';' | '{' (elements+=BaseElement)* '}')
;
    
AttributeDefinition:
	'attribute' 'def' DefinitionDeclaration (';' | '{' (elements+=BaseElement)* '}')
;

AttributeUsage:
    'attribute' Usage (';' | '{' (elements+=BaseElement)* '}')
;

ItemDefinition:
    'item' 'def' DefinitionDeclaration (';' | '{' (elements+=BaseElement)* '}')
;

ItemUsage:
    'item' Usage (';' | '{' (elements+=BaseElement)* '}')
;

PartDefinition:
    'part' 'def' DefinitionDeclaration (';' | '{' (elements+=BaseElement)* '}')
;

PartUsage:
    OccurrenceUsagePrefix 'part' Usage (';' | '{' (elements+=BaseElement)* '}')
;

PortDefinition:
    'port' 'def' DefinitionDeclaration (';' | '{' (elements+=BaseElement)* '}')
;

PortUsage:
    OccurrenceUsagePrefix 'port'? Usage (';' | '{' (elements+=BaseElement)* '}')
;

ConnectionDefinition:
	'connection' 'def' DefinitionDeclaration (';' | '{' (elements+=BaseElement)* '}')
;

ConnectionUsage:
	OccurrenceUsagePrefix 'connection' UsageDeclaration FeatureValue? ( 'connect' ConnectorPart )?  (';' | '{' (elements+=BaseElement)* '}') 
	| OccurrenceUsagePrefix 'connect' ConnectorPart (';' | '{' (elements+=BaseElement)* '}')
;

InterfaceDefinition:
	'interface' 'def' DefinitionDeclaration (';' | '{' (elements += BaseElement)* '}')
;

//InterfaceBody:
//	InterfaceEnd | BaseElement
//;
//
//InterfaceEnd returns PortUsage:
//	isEnd ?= 'end' Usage
//;

InterfaceUsage:
	OccurrenceUsagePrefix 'interface' (UsageDeclaration ('connect' InterfacePart )? | InterfacePart) (';' | '{' (elements+=BaseElement)* '}')
;

FlowConnectionDefinition:
	'flow' 'def' DefinitionDeclaration (';' | '{' (elements+=BaseElement)* '}')
;

FlowConnectionUsage:
	OccurrenceUsagePrefix 'flow' UsageDeclaration FeatureValue?
	( 'of' ItemFeature += Name )?
    ( 'from' FlowEnd += FeatureChainName 'to' FlowEnd += FeatureChainName )?
    (';' | '{' (elements+=BaseElement)* '}')
;

ActionUsage:
    OccurrenceUsagePrefix 'action' declaredName=QualifiedName (';' | '{' (elements+=BaseElement)* '}')
;

// enum

enum VisibilityIndicator:
	public = 'public' | private = 'private'| protected = 'protected'
;

enum FeatureDirection:
	in = 'in' | out = 'out' | inout = 'inout'
;

enum PortionKind:
	snapshot = 'snapshot' | timeslice = 'timeslice'
;

fragment OccurrenceUsagePrefix:
	isEnd ?= 'end'
	| BasicUsagePrefix
//	  ( isIndividual ?= 'individual' )?
//	  ( portionKind = PortionKind )?
;

fragment RefPrefix:
    ( direction = FeatureDirection )?
//    ( isAbstract ?= 'abstract' | isVariation ?= 'variation')?
//    ( isReadOnly ?= 'readonly' )?
//    ( isDerived ?= 'derived' )?
;

fragment BasicUsagePrefix:
	RefPrefix
	( isReference ?= 'ref' )?
;

fragment ConnectorPart:
	connectorEnd += FeatureChainName 'to' connectorEnd += FeatureChainName 
	| '(' connectorEnd += FeatureChainName ','  connectorEnd += FeatureChainName (',' connectorEnd += FeatureChainName)* ')'
;

fragment InterfacePart:
	InterfaceEnd += FeatureChainName 'to' InterfaceEnd += FeatureChainName 
	| '(' InterfaceEnd += FeatureChainName ','  InterfaceEnd += FeatureChainName (',' InterfaceEnd += FeatureChainName)* ')'
;

fragment DefinitionDeclaration:
	(declaredName = Name)? ((':'|':>'|'specializes') superclassifiers+=FeatureChainName (',' superclassifiers+=FeatureChainName)*)?
;

fragment Usage:
	UsageDeclaration FeatureValue?
;

fragment UsageDeclaration:
	FeatureDeclaration?
;

fragment FeatureValue:
	( '=' 
	| isInitial ?= ':='
	| isDefault ?= 'default' ( '=' | isInitial ?= ':=' )?
	)
	valuePart += Expression
;

fragment FeatureDeclaration:
	  declaredName = Name FeatureSpecializationPart?
	| FeatureSpecializationPart
;

fragment FeatureSpecializationPart:
	( -> FeatureSpecialization )+ MultiplicityPart? FeatureSpecialization*
	| MultiplicityPart FeatureSpecialization*
;

fragment MultiplicityPart:
	'[' Multiplicity += DECIMAL_VALUE ( '..' Multiplicity += DECIMAL_VALUE )? ']'
	| ('[' Multiplicity += DECIMAL_VALUE ( '..' Multiplicity += DECIMAL_VALUE )? ']')?
	  ( isOrdered ?= 'ordered' isNonunique ?= 'nonunique'?
	  | isNonunique ?= 'nonunique' isOrdered ?= 'ordered'?
	  )
;

fragment FeatureSpecialization:
	(':'|'defined' 'by') typings+=FeatureChainName (',' typings+=FeatureChainName)*|
	(':>'|'specializes'|'subsets') subsetting+=FeatureChainName (',' subsetting+=FeatureChainName)*|
	('::>'|'references')  references+=FeatureChainName (',' references+=FeatureChainName)*|
	('=>'|'crosses') crosses+=FeatureChainName (',' crosses+=FeatureChainName)*|
	(':>>'|'redefines') redefinitions+=FeatureChainName (',' redefinitions+=FeatureChainName)*
;

/* NAMES */

Name:
	ID | UNRESTRICTED_NAME
;

QualifiedName:
	Name ('::' Name)*
;

FeatureChainName:
	'~'? QualifiedName ('.' Name)*
;

ExpressionName:
	FeatureChainName | NORMAL_VALUE
;

Expression:
	OPERATOR* ExpressionName (OPERATOR ExpressionName?)* | '(' SequenceExpression ')'
;

SequenceExpression:
	Expression (',' Expression)*
;

/* TERMINALS */

terminal OPERATOR:
	'if' | '??' | 'implies' | '|' | 'or' | 'xor' | '&' | 'and' | '==' | '!=' | '===' | '!==' | 'hastype' | 'istype' | '@'|
	'@@' | 'as' | 'meta' | '<' | '>' | '<=' | '>=' | '+' | '-' | '*' | '/' | '%' | '..' | '**' | '^' | '~' | 'not' |
	'true' | 'false';
	
terminal DECIMAL_VALUE returns Ecore::EInt:
	'0'..'9' ('0'..'9')*;

terminal NORMAL_VALUE returns Ecore::EDouble:
	DECIMAL_VALUE ('.' DECIMAL_VALUE)?;

terminal EXP_VALUE:
	NORMAL_VALUE (('e' | 'E') ('+' | '-')? DECIMAL_VALUE)?;

terminal ID:
	('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;

terminal UNRESTRICTED_NAME returns Ecore::EString:
	'\'' ('\\' ('b' | 't' | 'n' | 'f' | 'r' | '"' | "'" | '\\') | !('\\' | '\''))* '\'';

terminal STRING_VALUE returns Ecore::EString:
	'"' ('\\' ('b' | 't' | 'n' | 'f' | 'r' | '"' | "'" | '\\') | !('\\' | '"'))* '"';

terminal REGULAR_COMMENT:
	'/*' -> '*/';

terminal ML_NOTE:
	'//*'-> '*/';

terminal SL_NOTE:
	'//' (!('\n' | '\r') !('\n' | '\r')*)? ('\r'? '\n')?;

terminal WS:
	(' ' | '\t' | '\r' | '\n')+;