/**
 * generated by Xtext 2.38.0
 */
package dut.control.sysmloc.sysMLOC.impl;

import dut.control.sysmloc.sysMLOC.ConnectorPart;
import dut.control.sysmloc.sysMLOC.SysMLOCPackage;

import java.util.Collection;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Connector Part</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.ConnectorPartImpl#getConnectorEnd <em>Connector End</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ConnectorPartImpl extends MinimalEObjectImpl.Container implements ConnectorPart
{
  /**
   * The cached value of the '{@link #getConnectorEnd() <em>Connector End</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConnectorEnd()
   * @generated
   * @ordered
   */
  protected EList<String> connectorEnd;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConnectorPartImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SysMLOCPackage.Literals.CONNECTOR_PART;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getConnectorEnd()
  {
    if (connectorEnd == null)
    {
      connectorEnd = new EDataTypeEList<String>(String.class, this, SysMLOCPackage.CONNECTOR_PART__CONNECTOR_END);
    }
    return connectorEnd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SysMLOCPackage.CONNECTOR_PART__CONNECTOR_END:
        return getConnectorEnd();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SysMLOCPackage.CONNECTOR_PART__CONNECTOR_END:
        getConnectorEnd().clear();
        getConnectorEnd().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SysMLOCPackage.CONNECTOR_PART__CONNECTOR_END:
        getConnectorEnd().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SysMLOCPackage.CONNECTOR_PART__CONNECTOR_END:
        return connectorEnd != null && !connectorEnd.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (connectorEnd: ");
    result.append(connectorEnd);
    result.append(')');
    return result.toString();
  }

} //ConnectorPartImpl
