/**
 * generated by Xtext 2.38.0
 */
package dut.control.sysmloc.sysMLOC.impl;

import dut.control.sysmloc.sysMLOC.ActionBodyElement;
import dut.control.sysmloc.sysMLOC.ActionNodePrefix;
import dut.control.sysmloc.sysMLOC.ActionNodeUsageDeclaration;
import dut.control.sysmloc.sysMLOC.ActionParameterEnd;
import dut.control.sysmloc.sysMLOC.BasicDefinitionPrefix;
import dut.control.sysmloc.sysMLOC.BasicUsagePrefix;
import dut.control.sysmloc.sysMLOC.CrossFeatureChain;
import dut.control.sysmloc.sysMLOC.EmptySuccessionPrefix;
import dut.control.sysmloc.sysMLOC.FeatureDeclaration;
import dut.control.sysmloc.sysMLOC.FeatureDirection;
import dut.control.sysmloc.sysMLOC.FeatureSpecialization;
import dut.control.sysmloc.sysMLOC.FeatureSpecializationPart;
import dut.control.sysmloc.sysMLOC.ForLoopNode;
import dut.control.sysmloc.sysMLOC.ForVariableParameter;
import dut.control.sysmloc.sysMLOC.Identification;
import dut.control.sysmloc.sysMLOC.MemberPrefix;
import dut.control.sysmloc.sysMLOC.MultiplicityPart;
import dut.control.sysmloc.sysMLOC.MultiplicityRange;
import dut.control.sysmloc.sysMLOC.OccurrenceUsagePrefix;
import dut.control.sysmloc.sysMLOC.PortionKind;
import dut.control.sysmloc.sysMLOC.RedefinitionFeatureChain;
import dut.control.sysmloc.sysMLOC.RefPrefix;
import dut.control.sysmloc.sysMLOC.ReferenceFeatureChain;
import dut.control.sysmloc.sysMLOC.SubsettingFeatureChain;
import dut.control.sysmloc.sysMLOC.SysMLOCPackage;
import dut.control.sysmloc.sysMLOC.TypingFeatureTyping;
import dut.control.sysmloc.sysMLOC.UsageDeclaration;
import dut.control.sysmloc.sysMLOC.VisibilityIndicator;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>For Loop Node</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.ForLoopNodeImpl#isIsThen <em>Is Then</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.ForLoopNodeImpl#getThenMultiplicity <em>Then Multiplicity</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.ForLoopNodeImpl#getVisibility <em>Visibility</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.ForLoopNodeImpl#isIsVariant <em>Is Variant</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.ForLoopNodeImpl#isIsAbstract <em>Is Abstract</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.ForLoopNodeImpl#isIsVariation <em>Is Variation</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.ForLoopNodeImpl#getDirection <em>Direction</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.ForLoopNodeImpl#isIsReadOnly <em>Is Read Only</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.ForLoopNodeImpl#isIsDerived <em>Is Derived</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.ForLoopNodeImpl#isIsReference <em>Is Reference</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.ForLoopNodeImpl#isIsEnd <em>Is End</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.ForLoopNodeImpl#isIsIndividual <em>Is Individual</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.ForLoopNodeImpl#getPortionKind <em>Portion Kind</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.ForLoopNodeImpl#getDeclaredShortName <em>Declared Short Name</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.ForLoopNodeImpl#getDeclaredName <em>Declared Name</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.ForLoopNodeImpl#getTypings <em>Typings</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.ForLoopNodeImpl#getSubsetting <em>Subsetting</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.ForLoopNodeImpl#getReferences <em>References</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.ForLoopNodeImpl#getCrosses <em>Crosses</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.ForLoopNodeImpl#getRedefinitions <em>Redefinitions</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.ForLoopNodeImpl#getMultiplicity <em>Multiplicity</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.ForLoopNodeImpl#isIsOrdered <em>Is Ordered</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.ForLoopNodeImpl#isIsNonunique <em>Is Nonunique</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.ForLoopNodeImpl#getForVariableParameter <em>For Variable Parameter</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.ForLoopNodeImpl#getForNodeParameter <em>For Node Parameter</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.ForLoopNodeImpl#getActionParameterEnd <em>Action Parameter End</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.ForLoopNodeImpl#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ForLoopNodeImpl extends ActionNodeElementsImpl implements ForLoopNode
{
  /**
   * The default value of the '{@link #isIsThen() <em>Is Then</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsThen()
   * @generated
   * @ordered
   */
  protected static final boolean IS_THEN_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsThen() <em>Is Then</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsThen()
   * @generated
   * @ordered
   */
  protected boolean isThen = IS_THEN_EDEFAULT;

  /**
   * The cached value of the '{@link #getThenMultiplicity() <em>Then Multiplicity</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getThenMultiplicity()
   * @generated
   * @ordered
   */
  protected EList<String> thenMultiplicity;

  /**
   * The default value of the '{@link #getVisibility() <em>Visibility</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVisibility()
   * @generated
   * @ordered
   */
  protected static final VisibilityIndicator VISIBILITY_EDEFAULT = VisibilityIndicator.NULL;

  /**
   * The cached value of the '{@link #getVisibility() <em>Visibility</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVisibility()
   * @generated
   * @ordered
   */
  protected VisibilityIndicator visibility = VISIBILITY_EDEFAULT;

  /**
   * The default value of the '{@link #isIsVariant() <em>Is Variant</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsVariant()
   * @generated
   * @ordered
   */
  protected static final boolean IS_VARIANT_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsVariant() <em>Is Variant</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsVariant()
   * @generated
   * @ordered
   */
  protected boolean isVariant = IS_VARIANT_EDEFAULT;

  /**
   * The default value of the '{@link #isIsAbstract() <em>Is Abstract</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsAbstract()
   * @generated
   * @ordered
   */
  protected static final boolean IS_ABSTRACT_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsAbstract() <em>Is Abstract</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsAbstract()
   * @generated
   * @ordered
   */
  protected boolean isAbstract = IS_ABSTRACT_EDEFAULT;

  /**
   * The default value of the '{@link #isIsVariation() <em>Is Variation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsVariation()
   * @generated
   * @ordered
   */
  protected static final boolean IS_VARIATION_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsVariation() <em>Is Variation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsVariation()
   * @generated
   * @ordered
   */
  protected boolean isVariation = IS_VARIATION_EDEFAULT;

  /**
   * The default value of the '{@link #getDirection() <em>Direction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDirection()
   * @generated
   * @ordered
   */
  protected static final FeatureDirection DIRECTION_EDEFAULT = FeatureDirection.NULL;

  /**
   * The cached value of the '{@link #getDirection() <em>Direction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDirection()
   * @generated
   * @ordered
   */
  protected FeatureDirection direction = DIRECTION_EDEFAULT;

  /**
   * The default value of the '{@link #isIsReadOnly() <em>Is Read Only</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsReadOnly()
   * @generated
   * @ordered
   */
  protected static final boolean IS_READ_ONLY_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsReadOnly() <em>Is Read Only</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsReadOnly()
   * @generated
   * @ordered
   */
  protected boolean isReadOnly = IS_READ_ONLY_EDEFAULT;

  /**
   * The default value of the '{@link #isIsDerived() <em>Is Derived</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsDerived()
   * @generated
   * @ordered
   */
  protected static final boolean IS_DERIVED_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsDerived() <em>Is Derived</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsDerived()
   * @generated
   * @ordered
   */
  protected boolean isDerived = IS_DERIVED_EDEFAULT;

  /**
   * The default value of the '{@link #isIsReference() <em>Is Reference</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsReference()
   * @generated
   * @ordered
   */
  protected static final boolean IS_REFERENCE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsReference() <em>Is Reference</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsReference()
   * @generated
   * @ordered
   */
  protected boolean isReference = IS_REFERENCE_EDEFAULT;

  /**
   * The default value of the '{@link #isIsEnd() <em>Is End</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsEnd()
   * @generated
   * @ordered
   */
  protected static final boolean IS_END_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsEnd() <em>Is End</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsEnd()
   * @generated
   * @ordered
   */
  protected boolean isEnd = IS_END_EDEFAULT;

  /**
   * The default value of the '{@link #isIsIndividual() <em>Is Individual</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsIndividual()
   * @generated
   * @ordered
   */
  protected static final boolean IS_INDIVIDUAL_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsIndividual() <em>Is Individual</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsIndividual()
   * @generated
   * @ordered
   */
  protected boolean isIndividual = IS_INDIVIDUAL_EDEFAULT;

  /**
   * The default value of the '{@link #getPortionKind() <em>Portion Kind</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPortionKind()
   * @generated
   * @ordered
   */
  protected static final PortionKind PORTION_KIND_EDEFAULT = PortionKind.NULL;

  /**
   * The cached value of the '{@link #getPortionKind() <em>Portion Kind</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPortionKind()
   * @generated
   * @ordered
   */
  protected PortionKind portionKind = PORTION_KIND_EDEFAULT;

  /**
   * The default value of the '{@link #getDeclaredShortName() <em>Declared Short Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDeclaredShortName()
   * @generated
   * @ordered
   */
  protected static final String DECLARED_SHORT_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDeclaredShortName() <em>Declared Short Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDeclaredShortName()
   * @generated
   * @ordered
   */
  protected String declaredShortName = DECLARED_SHORT_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getDeclaredName() <em>Declared Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDeclaredName()
   * @generated
   * @ordered
   */
  protected static final String DECLARED_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDeclaredName() <em>Declared Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDeclaredName()
   * @generated
   * @ordered
   */
  protected String declaredName = DECLARED_NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getTypings() <em>Typings</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypings()
   * @generated
   * @ordered
   */
  protected EList<String> typings;

  /**
   * The cached value of the '{@link #getSubsetting() <em>Subsetting</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubsetting()
   * @generated
   * @ordered
   */
  protected EList<String> subsetting;

  /**
   * The cached value of the '{@link #getReferences() <em>References</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReferences()
   * @generated
   * @ordered
   */
  protected EList<String> references;

  /**
   * The cached value of the '{@link #getCrosses() <em>Crosses</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCrosses()
   * @generated
   * @ordered
   */
  protected EList<String> crosses;

  /**
   * The cached value of the '{@link #getRedefinitions() <em>Redefinitions</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRedefinitions()
   * @generated
   * @ordered
   */
  protected EList<String> redefinitions;

  /**
   * The cached value of the '{@link #getMultiplicity() <em>Multiplicity</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMultiplicity()
   * @generated
   * @ordered
   */
  protected EList<String> multiplicity;

  /**
   * The default value of the '{@link #isIsOrdered() <em>Is Ordered</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsOrdered()
   * @generated
   * @ordered
   */
  protected static final boolean IS_ORDERED_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsOrdered() <em>Is Ordered</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsOrdered()
   * @generated
   * @ordered
   */
  protected boolean isOrdered = IS_ORDERED_EDEFAULT;

  /**
   * The default value of the '{@link #isIsNonunique() <em>Is Nonunique</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsNonunique()
   * @generated
   * @ordered
   */
  protected static final boolean IS_NONUNIQUE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsNonunique() <em>Is Nonunique</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsNonunique()
   * @generated
   * @ordered
   */
  protected boolean isNonunique = IS_NONUNIQUE_EDEFAULT;

  /**
   * The cached value of the '{@link #getForVariableParameter() <em>For Variable Parameter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getForVariableParameter()
   * @generated
   * @ordered
   */
  protected ForVariableParameter forVariableParameter;

  /**
   * The default value of the '{@link #getForNodeParameter() <em>For Node Parameter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getForNodeParameter()
   * @generated
   * @ordered
   */
  protected static final String FOR_NODE_PARAMETER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getForNodeParameter() <em>For Node Parameter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getForNodeParameter()
   * @generated
   * @ordered
   */
  protected String forNodeParameter = FOR_NODE_PARAMETER_EDEFAULT;

  /**
   * The cached value of the '{@link #getActionParameterEnd() <em>Action Parameter End</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getActionParameterEnd()
   * @generated
   * @ordered
   */
  protected EList<ActionParameterEnd> actionParameterEnd;

  /**
   * The cached value of the '{@link #getElements() <em>Elements</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getElements()
   * @generated
   * @ordered
   */
  protected EList<ActionBodyElement> elements;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ForLoopNodeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SysMLOCPackage.eINSTANCE.getForLoopNode();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsThen()
  {
    return isThen;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsThen(boolean newIsThen)
  {
    boolean oldIsThen = isThen;
    isThen = newIsThen;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLOCPackage.FOR_LOOP_NODE__IS_THEN, oldIsThen, isThen));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getThenMultiplicity()
  {
    if (thenMultiplicity == null)
    {
      thenMultiplicity = new EDataTypeEList<String>(String.class, this, SysMLOCPackage.FOR_LOOP_NODE__THEN_MULTIPLICITY);
    }
    return thenMultiplicity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VisibilityIndicator getVisibility()
  {
    return visibility;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVisibility(VisibilityIndicator newVisibility)
  {
    VisibilityIndicator oldVisibility = visibility;
    visibility = newVisibility == null ? VISIBILITY_EDEFAULT : newVisibility;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLOCPackage.FOR_LOOP_NODE__VISIBILITY, oldVisibility, visibility));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsVariant()
  {
    return isVariant;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsVariant(boolean newIsVariant)
  {
    boolean oldIsVariant = isVariant;
    isVariant = newIsVariant;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLOCPackage.FOR_LOOP_NODE__IS_VARIANT, oldIsVariant, isVariant));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsAbstract()
  {
    return isAbstract;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsAbstract(boolean newIsAbstract)
  {
    boolean oldIsAbstract = isAbstract;
    isAbstract = newIsAbstract;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLOCPackage.FOR_LOOP_NODE__IS_ABSTRACT, oldIsAbstract, isAbstract));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsVariation()
  {
    return isVariation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsVariation(boolean newIsVariation)
  {
    boolean oldIsVariation = isVariation;
    isVariation = newIsVariation;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLOCPackage.FOR_LOOP_NODE__IS_VARIATION, oldIsVariation, isVariation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FeatureDirection getDirection()
  {
    return direction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDirection(FeatureDirection newDirection)
  {
    FeatureDirection oldDirection = direction;
    direction = newDirection == null ? DIRECTION_EDEFAULT : newDirection;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLOCPackage.FOR_LOOP_NODE__DIRECTION, oldDirection, direction));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsReadOnly()
  {
    return isReadOnly;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsReadOnly(boolean newIsReadOnly)
  {
    boolean oldIsReadOnly = isReadOnly;
    isReadOnly = newIsReadOnly;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLOCPackage.FOR_LOOP_NODE__IS_READ_ONLY, oldIsReadOnly, isReadOnly));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsDerived()
  {
    return isDerived;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsDerived(boolean newIsDerived)
  {
    boolean oldIsDerived = isDerived;
    isDerived = newIsDerived;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLOCPackage.FOR_LOOP_NODE__IS_DERIVED, oldIsDerived, isDerived));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsReference()
  {
    return isReference;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsReference(boolean newIsReference)
  {
    boolean oldIsReference = isReference;
    isReference = newIsReference;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLOCPackage.FOR_LOOP_NODE__IS_REFERENCE, oldIsReference, isReference));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsEnd()
  {
    return isEnd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsEnd(boolean newIsEnd)
  {
    boolean oldIsEnd = isEnd;
    isEnd = newIsEnd;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLOCPackage.FOR_LOOP_NODE__IS_END, oldIsEnd, isEnd));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsIndividual()
  {
    return isIndividual;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsIndividual(boolean newIsIndividual)
  {
    boolean oldIsIndividual = isIndividual;
    isIndividual = newIsIndividual;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLOCPackage.FOR_LOOP_NODE__IS_INDIVIDUAL, oldIsIndividual, isIndividual));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PortionKind getPortionKind()
  {
    return portionKind;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPortionKind(PortionKind newPortionKind)
  {
    PortionKind oldPortionKind = portionKind;
    portionKind = newPortionKind == null ? PORTION_KIND_EDEFAULT : newPortionKind;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLOCPackage.FOR_LOOP_NODE__PORTION_KIND, oldPortionKind, portionKind));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDeclaredShortName()
  {
    return declaredShortName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDeclaredShortName(String newDeclaredShortName)
  {
    String oldDeclaredShortName = declaredShortName;
    declaredShortName = newDeclaredShortName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLOCPackage.FOR_LOOP_NODE__DECLARED_SHORT_NAME, oldDeclaredShortName, declaredShortName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDeclaredName()
  {
    return declaredName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDeclaredName(String newDeclaredName)
  {
    String oldDeclaredName = declaredName;
    declaredName = newDeclaredName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLOCPackage.FOR_LOOP_NODE__DECLARED_NAME, oldDeclaredName, declaredName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getTypings()
  {
    if (typings == null)
    {
      typings = new EDataTypeEList<String>(String.class, this, SysMLOCPackage.FOR_LOOP_NODE__TYPINGS);
    }
    return typings;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getSubsetting()
  {
    if (subsetting == null)
    {
      subsetting = new EDataTypeEList<String>(String.class, this, SysMLOCPackage.FOR_LOOP_NODE__SUBSETTING);
    }
    return subsetting;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getReferences()
  {
    if (references == null)
    {
      references = new EDataTypeEList<String>(String.class, this, SysMLOCPackage.FOR_LOOP_NODE__REFERENCES);
    }
    return references;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getCrosses()
  {
    if (crosses == null)
    {
      crosses = new EDataTypeEList<String>(String.class, this, SysMLOCPackage.FOR_LOOP_NODE__CROSSES);
    }
    return crosses;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getRedefinitions()
  {
    if (redefinitions == null)
    {
      redefinitions = new EDataTypeEList<String>(String.class, this, SysMLOCPackage.FOR_LOOP_NODE__REDEFINITIONS);
    }
    return redefinitions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getMultiplicity()
  {
    if (multiplicity == null)
    {
      multiplicity = new EDataTypeEList<String>(String.class, this, SysMLOCPackage.FOR_LOOP_NODE__MULTIPLICITY);
    }
    return multiplicity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsOrdered()
  {
    return isOrdered;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsOrdered(boolean newIsOrdered)
  {
    boolean oldIsOrdered = isOrdered;
    isOrdered = newIsOrdered;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLOCPackage.FOR_LOOP_NODE__IS_ORDERED, oldIsOrdered, isOrdered));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsNonunique()
  {
    return isNonunique;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsNonunique(boolean newIsNonunique)
  {
    boolean oldIsNonunique = isNonunique;
    isNonunique = newIsNonunique;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLOCPackage.FOR_LOOP_NODE__IS_NONUNIQUE, oldIsNonunique, isNonunique));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ForVariableParameter getForVariableParameter()
  {
    return forVariableParameter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetForVariableParameter(ForVariableParameter newForVariableParameter, NotificationChain msgs)
  {
    ForVariableParameter oldForVariableParameter = forVariableParameter;
    forVariableParameter = newForVariableParameter;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SysMLOCPackage.FOR_LOOP_NODE__FOR_VARIABLE_PARAMETER, oldForVariableParameter, newForVariableParameter);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setForVariableParameter(ForVariableParameter newForVariableParameter)
  {
    if (newForVariableParameter != forVariableParameter)
    {
      NotificationChain msgs = null;
      if (forVariableParameter != null)
        msgs = ((InternalEObject)forVariableParameter).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SysMLOCPackage.FOR_LOOP_NODE__FOR_VARIABLE_PARAMETER, null, msgs);
      if (newForVariableParameter != null)
        msgs = ((InternalEObject)newForVariableParameter).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SysMLOCPackage.FOR_LOOP_NODE__FOR_VARIABLE_PARAMETER, null, msgs);
      msgs = basicSetForVariableParameter(newForVariableParameter, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLOCPackage.FOR_LOOP_NODE__FOR_VARIABLE_PARAMETER, newForVariableParameter, newForVariableParameter));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getForNodeParameter()
  {
    return forNodeParameter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setForNodeParameter(String newForNodeParameter)
  {
    String oldForNodeParameter = forNodeParameter;
    forNodeParameter = newForNodeParameter;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLOCPackage.FOR_LOOP_NODE__FOR_NODE_PARAMETER, oldForNodeParameter, forNodeParameter));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ActionParameterEnd> getActionParameterEnd()
  {
    if (actionParameterEnd == null)
    {
      actionParameterEnd = new EObjectContainmentEList<ActionParameterEnd>(ActionParameterEnd.class, this, SysMLOCPackage.FOR_LOOP_NODE__ACTION_PARAMETER_END);
    }
    return actionParameterEnd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ActionBodyElement> getElements()
  {
    if (elements == null)
    {
      elements = new EObjectContainmentEList<ActionBodyElement>(ActionBodyElement.class, this, SysMLOCPackage.FOR_LOOP_NODE__ELEMENTS);
    }
    return elements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SysMLOCPackage.FOR_LOOP_NODE__FOR_VARIABLE_PARAMETER:
        return basicSetForVariableParameter(null, msgs);
      case SysMLOCPackage.FOR_LOOP_NODE__ACTION_PARAMETER_END:
        return ((InternalEList<?>)getActionParameterEnd()).basicRemove(otherEnd, msgs);
      case SysMLOCPackage.FOR_LOOP_NODE__ELEMENTS:
        return ((InternalEList<?>)getElements()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SysMLOCPackage.FOR_LOOP_NODE__IS_THEN:
        return isIsThen();
      case SysMLOCPackage.FOR_LOOP_NODE__THEN_MULTIPLICITY:
        return getThenMultiplicity();
      case SysMLOCPackage.FOR_LOOP_NODE__VISIBILITY:
        return getVisibility();
      case SysMLOCPackage.FOR_LOOP_NODE__IS_VARIANT:
        return isIsVariant();
      case SysMLOCPackage.FOR_LOOP_NODE__IS_ABSTRACT:
        return isIsAbstract();
      case SysMLOCPackage.FOR_LOOP_NODE__IS_VARIATION:
        return isIsVariation();
      case SysMLOCPackage.FOR_LOOP_NODE__DIRECTION:
        return getDirection();
      case SysMLOCPackage.FOR_LOOP_NODE__IS_READ_ONLY:
        return isIsReadOnly();
      case SysMLOCPackage.FOR_LOOP_NODE__IS_DERIVED:
        return isIsDerived();
      case SysMLOCPackage.FOR_LOOP_NODE__IS_REFERENCE:
        return isIsReference();
      case SysMLOCPackage.FOR_LOOP_NODE__IS_END:
        return isIsEnd();
      case SysMLOCPackage.FOR_LOOP_NODE__IS_INDIVIDUAL:
        return isIsIndividual();
      case SysMLOCPackage.FOR_LOOP_NODE__PORTION_KIND:
        return getPortionKind();
      case SysMLOCPackage.FOR_LOOP_NODE__DECLARED_SHORT_NAME:
        return getDeclaredShortName();
      case SysMLOCPackage.FOR_LOOP_NODE__DECLARED_NAME:
        return getDeclaredName();
      case SysMLOCPackage.FOR_LOOP_NODE__TYPINGS:
        return getTypings();
      case SysMLOCPackage.FOR_LOOP_NODE__SUBSETTING:
        return getSubsetting();
      case SysMLOCPackage.FOR_LOOP_NODE__REFERENCES:
        return getReferences();
      case SysMLOCPackage.FOR_LOOP_NODE__CROSSES:
        return getCrosses();
      case SysMLOCPackage.FOR_LOOP_NODE__REDEFINITIONS:
        return getRedefinitions();
      case SysMLOCPackage.FOR_LOOP_NODE__MULTIPLICITY:
        return getMultiplicity();
      case SysMLOCPackage.FOR_LOOP_NODE__IS_ORDERED:
        return isIsOrdered();
      case SysMLOCPackage.FOR_LOOP_NODE__IS_NONUNIQUE:
        return isIsNonunique();
      case SysMLOCPackage.FOR_LOOP_NODE__FOR_VARIABLE_PARAMETER:
        return getForVariableParameter();
      case SysMLOCPackage.FOR_LOOP_NODE__FOR_NODE_PARAMETER:
        return getForNodeParameter();
      case SysMLOCPackage.FOR_LOOP_NODE__ACTION_PARAMETER_END:
        return getActionParameterEnd();
      case SysMLOCPackage.FOR_LOOP_NODE__ELEMENTS:
        return getElements();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SysMLOCPackage.FOR_LOOP_NODE__IS_THEN:
        setIsThen((Boolean)newValue);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__THEN_MULTIPLICITY:
        getThenMultiplicity().clear();
        getThenMultiplicity().addAll((Collection<? extends String>)newValue);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__VISIBILITY:
        setVisibility((VisibilityIndicator)newValue);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__IS_VARIANT:
        setIsVariant((Boolean)newValue);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__IS_ABSTRACT:
        setIsAbstract((Boolean)newValue);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__IS_VARIATION:
        setIsVariation((Boolean)newValue);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__DIRECTION:
        setDirection((FeatureDirection)newValue);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__IS_READ_ONLY:
        setIsReadOnly((Boolean)newValue);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__IS_DERIVED:
        setIsDerived((Boolean)newValue);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__IS_REFERENCE:
        setIsReference((Boolean)newValue);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__IS_END:
        setIsEnd((Boolean)newValue);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__IS_INDIVIDUAL:
        setIsIndividual((Boolean)newValue);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__PORTION_KIND:
        setPortionKind((PortionKind)newValue);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__DECLARED_SHORT_NAME:
        setDeclaredShortName((String)newValue);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__DECLARED_NAME:
        setDeclaredName((String)newValue);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__TYPINGS:
        getTypings().clear();
        getTypings().addAll((Collection<? extends String>)newValue);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__SUBSETTING:
        getSubsetting().clear();
        getSubsetting().addAll((Collection<? extends String>)newValue);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__REFERENCES:
        getReferences().clear();
        getReferences().addAll((Collection<? extends String>)newValue);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__CROSSES:
        getCrosses().clear();
        getCrosses().addAll((Collection<? extends String>)newValue);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__REDEFINITIONS:
        getRedefinitions().clear();
        getRedefinitions().addAll((Collection<? extends String>)newValue);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__MULTIPLICITY:
        getMultiplicity().clear();
        getMultiplicity().addAll((Collection<? extends String>)newValue);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__IS_ORDERED:
        setIsOrdered((Boolean)newValue);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__IS_NONUNIQUE:
        setIsNonunique((Boolean)newValue);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__FOR_VARIABLE_PARAMETER:
        setForVariableParameter((ForVariableParameter)newValue);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__FOR_NODE_PARAMETER:
        setForNodeParameter((String)newValue);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__ACTION_PARAMETER_END:
        getActionParameterEnd().clear();
        getActionParameterEnd().addAll((Collection<? extends ActionParameterEnd>)newValue);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__ELEMENTS:
        getElements().clear();
        getElements().addAll((Collection<? extends ActionBodyElement>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SysMLOCPackage.FOR_LOOP_NODE__IS_THEN:
        setIsThen(IS_THEN_EDEFAULT);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__THEN_MULTIPLICITY:
        getThenMultiplicity().clear();
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__VISIBILITY:
        setVisibility(VISIBILITY_EDEFAULT);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__IS_VARIANT:
        setIsVariant(IS_VARIANT_EDEFAULT);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__IS_ABSTRACT:
        setIsAbstract(IS_ABSTRACT_EDEFAULT);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__IS_VARIATION:
        setIsVariation(IS_VARIATION_EDEFAULT);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__DIRECTION:
        setDirection(DIRECTION_EDEFAULT);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__IS_READ_ONLY:
        setIsReadOnly(IS_READ_ONLY_EDEFAULT);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__IS_DERIVED:
        setIsDerived(IS_DERIVED_EDEFAULT);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__IS_REFERENCE:
        setIsReference(IS_REFERENCE_EDEFAULT);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__IS_END:
        setIsEnd(IS_END_EDEFAULT);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__IS_INDIVIDUAL:
        setIsIndividual(IS_INDIVIDUAL_EDEFAULT);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__PORTION_KIND:
        setPortionKind(PORTION_KIND_EDEFAULT);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__DECLARED_SHORT_NAME:
        setDeclaredShortName(DECLARED_SHORT_NAME_EDEFAULT);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__DECLARED_NAME:
        setDeclaredName(DECLARED_NAME_EDEFAULT);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__TYPINGS:
        getTypings().clear();
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__SUBSETTING:
        getSubsetting().clear();
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__REFERENCES:
        getReferences().clear();
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__CROSSES:
        getCrosses().clear();
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__REDEFINITIONS:
        getRedefinitions().clear();
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__MULTIPLICITY:
        getMultiplicity().clear();
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__IS_ORDERED:
        setIsOrdered(IS_ORDERED_EDEFAULT);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__IS_NONUNIQUE:
        setIsNonunique(IS_NONUNIQUE_EDEFAULT);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__FOR_VARIABLE_PARAMETER:
        setForVariableParameter((ForVariableParameter)null);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__FOR_NODE_PARAMETER:
        setForNodeParameter(FOR_NODE_PARAMETER_EDEFAULT);
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__ACTION_PARAMETER_END:
        getActionParameterEnd().clear();
        return;
      case SysMLOCPackage.FOR_LOOP_NODE__ELEMENTS:
        getElements().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SysMLOCPackage.FOR_LOOP_NODE__IS_THEN:
        return isThen != IS_THEN_EDEFAULT;
      case SysMLOCPackage.FOR_LOOP_NODE__THEN_MULTIPLICITY:
        return thenMultiplicity != null && !thenMultiplicity.isEmpty();
      case SysMLOCPackage.FOR_LOOP_NODE__VISIBILITY:
        return visibility != VISIBILITY_EDEFAULT;
      case SysMLOCPackage.FOR_LOOP_NODE__IS_VARIANT:
        return isVariant != IS_VARIANT_EDEFAULT;
      case SysMLOCPackage.FOR_LOOP_NODE__IS_ABSTRACT:
        return isAbstract != IS_ABSTRACT_EDEFAULT;
      case SysMLOCPackage.FOR_LOOP_NODE__IS_VARIATION:
        return isVariation != IS_VARIATION_EDEFAULT;
      case SysMLOCPackage.FOR_LOOP_NODE__DIRECTION:
        return direction != DIRECTION_EDEFAULT;
      case SysMLOCPackage.FOR_LOOP_NODE__IS_READ_ONLY:
        return isReadOnly != IS_READ_ONLY_EDEFAULT;
      case SysMLOCPackage.FOR_LOOP_NODE__IS_DERIVED:
        return isDerived != IS_DERIVED_EDEFAULT;
      case SysMLOCPackage.FOR_LOOP_NODE__IS_REFERENCE:
        return isReference != IS_REFERENCE_EDEFAULT;
      case SysMLOCPackage.FOR_LOOP_NODE__IS_END:
        return isEnd != IS_END_EDEFAULT;
      case SysMLOCPackage.FOR_LOOP_NODE__IS_INDIVIDUAL:
        return isIndividual != IS_INDIVIDUAL_EDEFAULT;
      case SysMLOCPackage.FOR_LOOP_NODE__PORTION_KIND:
        return portionKind != PORTION_KIND_EDEFAULT;
      case SysMLOCPackage.FOR_LOOP_NODE__DECLARED_SHORT_NAME:
        return DECLARED_SHORT_NAME_EDEFAULT == null ? declaredShortName != null : !DECLARED_SHORT_NAME_EDEFAULT.equals(declaredShortName);
      case SysMLOCPackage.FOR_LOOP_NODE__DECLARED_NAME:
        return DECLARED_NAME_EDEFAULT == null ? declaredName != null : !DECLARED_NAME_EDEFAULT.equals(declaredName);
      case SysMLOCPackage.FOR_LOOP_NODE__TYPINGS:
        return typings != null && !typings.isEmpty();
      case SysMLOCPackage.FOR_LOOP_NODE__SUBSETTING:
        return subsetting != null && !subsetting.isEmpty();
      case SysMLOCPackage.FOR_LOOP_NODE__REFERENCES:
        return references != null && !references.isEmpty();
      case SysMLOCPackage.FOR_LOOP_NODE__CROSSES:
        return crosses != null && !crosses.isEmpty();
      case SysMLOCPackage.FOR_LOOP_NODE__REDEFINITIONS:
        return redefinitions != null && !redefinitions.isEmpty();
      case SysMLOCPackage.FOR_LOOP_NODE__MULTIPLICITY:
        return multiplicity != null && !multiplicity.isEmpty();
      case SysMLOCPackage.FOR_LOOP_NODE__IS_ORDERED:
        return isOrdered != IS_ORDERED_EDEFAULT;
      case SysMLOCPackage.FOR_LOOP_NODE__IS_NONUNIQUE:
        return isNonunique != IS_NONUNIQUE_EDEFAULT;
      case SysMLOCPackage.FOR_LOOP_NODE__FOR_VARIABLE_PARAMETER:
        return forVariableParameter != null;
      case SysMLOCPackage.FOR_LOOP_NODE__FOR_NODE_PARAMETER:
        return FOR_NODE_PARAMETER_EDEFAULT == null ? forNodeParameter != null : !FOR_NODE_PARAMETER_EDEFAULT.equals(forNodeParameter);
      case SysMLOCPackage.FOR_LOOP_NODE__ACTION_PARAMETER_END:
        return actionParameterEnd != null && !actionParameterEnd.isEmpty();
      case SysMLOCPackage.FOR_LOOP_NODE__ELEMENTS:
        return elements != null && !elements.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eBaseStructuralFeatureID(int derivedFeatureID, Class<?> baseClass)
  {
    if (baseClass == EmptySuccessionPrefix.class)
    {
      switch (derivedFeatureID)
      {
        case SysMLOCPackage.FOR_LOOP_NODE__IS_THEN: return SysMLOCPackage.EMPTY_SUCCESSION_PREFIX__IS_THEN;
        case SysMLOCPackage.FOR_LOOP_NODE__THEN_MULTIPLICITY: return SysMLOCPackage.EMPTY_SUCCESSION_PREFIX__THEN_MULTIPLICITY;
        default: return -1;
      }
    }
    if (baseClass == MemberPrefix.class)
    {
      switch (derivedFeatureID)
      {
        case SysMLOCPackage.FOR_LOOP_NODE__VISIBILITY: return SysMLOCPackage.MEMBER_PREFIX__VISIBILITY;
        case SysMLOCPackage.FOR_LOOP_NODE__IS_VARIANT: return SysMLOCPackage.MEMBER_PREFIX__IS_VARIANT;
        default: return -1;
      }
    }
    if (baseClass == BasicDefinitionPrefix.class)
    {
      switch (derivedFeatureID)
      {
        case SysMLOCPackage.FOR_LOOP_NODE__IS_ABSTRACT: return SysMLOCPackage.BASIC_DEFINITION_PREFIX__IS_ABSTRACT;
        case SysMLOCPackage.FOR_LOOP_NODE__IS_VARIATION: return SysMLOCPackage.BASIC_DEFINITION_PREFIX__IS_VARIATION;
        default: return -1;
      }
    }
    if (baseClass == RefPrefix.class)
    {
      switch (derivedFeatureID)
      {
        case SysMLOCPackage.FOR_LOOP_NODE__DIRECTION: return SysMLOCPackage.REF_PREFIX__DIRECTION;
        case SysMLOCPackage.FOR_LOOP_NODE__IS_READ_ONLY: return SysMLOCPackage.REF_PREFIX__IS_READ_ONLY;
        case SysMLOCPackage.FOR_LOOP_NODE__IS_DERIVED: return SysMLOCPackage.REF_PREFIX__IS_DERIVED;
        default: return -1;
      }
    }
    if (baseClass == BasicUsagePrefix.class)
    {
      switch (derivedFeatureID)
      {
        case SysMLOCPackage.FOR_LOOP_NODE__IS_REFERENCE: return SysMLOCPackage.BASIC_USAGE_PREFIX__IS_REFERENCE;
        default: return -1;
      }
    }
    if (baseClass == OccurrenceUsagePrefix.class)
    {
      switch (derivedFeatureID)
      {
        case SysMLOCPackage.FOR_LOOP_NODE__IS_END: return SysMLOCPackage.OCCURRENCE_USAGE_PREFIX__IS_END;
        case SysMLOCPackage.FOR_LOOP_NODE__IS_INDIVIDUAL: return SysMLOCPackage.OCCURRENCE_USAGE_PREFIX__IS_INDIVIDUAL;
        case SysMLOCPackage.FOR_LOOP_NODE__PORTION_KIND: return SysMLOCPackage.OCCURRENCE_USAGE_PREFIX__PORTION_KIND;
        default: return -1;
      }
    }
    if (baseClass == Identification.class)
    {
      switch (derivedFeatureID)
      {
        case SysMLOCPackage.FOR_LOOP_NODE__DECLARED_SHORT_NAME: return SysMLOCPackage.IDENTIFICATION__DECLARED_SHORT_NAME;
        case SysMLOCPackage.FOR_LOOP_NODE__DECLARED_NAME: return SysMLOCPackage.IDENTIFICATION__DECLARED_NAME;
        default: return -1;
      }
    }
    if (baseClass == TypingFeatureTyping.class)
    {
      switch (derivedFeatureID)
      {
        case SysMLOCPackage.FOR_LOOP_NODE__TYPINGS: return SysMLOCPackage.TYPING_FEATURE_TYPING__TYPINGS;
        default: return -1;
      }
    }
    if (baseClass == SubsettingFeatureChain.class)
    {
      switch (derivedFeatureID)
      {
        case SysMLOCPackage.FOR_LOOP_NODE__SUBSETTING: return SysMLOCPackage.SUBSETTING_FEATURE_CHAIN__SUBSETTING;
        default: return -1;
      }
    }
    if (baseClass == ReferenceFeatureChain.class)
    {
      switch (derivedFeatureID)
      {
        case SysMLOCPackage.FOR_LOOP_NODE__REFERENCES: return SysMLOCPackage.REFERENCE_FEATURE_CHAIN__REFERENCES;
        default: return -1;
      }
    }
    if (baseClass == CrossFeatureChain.class)
    {
      switch (derivedFeatureID)
      {
        case SysMLOCPackage.FOR_LOOP_NODE__CROSSES: return SysMLOCPackage.CROSS_FEATURE_CHAIN__CROSSES;
        default: return -1;
      }
    }
    if (baseClass == RedefinitionFeatureChain.class)
    {
      switch (derivedFeatureID)
      {
        case SysMLOCPackage.FOR_LOOP_NODE__REDEFINITIONS: return SysMLOCPackage.REDEFINITION_FEATURE_CHAIN__REDEFINITIONS;
        default: return -1;
      }
    }
    if (baseClass == FeatureSpecialization.class)
    {
      switch (derivedFeatureID)
      {
        default: return -1;
      }
    }
    if (baseClass == MultiplicityRange.class)
    {
      switch (derivedFeatureID)
      {
        case SysMLOCPackage.FOR_LOOP_NODE__MULTIPLICITY: return SysMLOCPackage.MULTIPLICITY_RANGE__MULTIPLICITY;
        default: return -1;
      }
    }
    if (baseClass == MultiplicityPart.class)
    {
      switch (derivedFeatureID)
      {
        case SysMLOCPackage.FOR_LOOP_NODE__IS_ORDERED: return SysMLOCPackage.MULTIPLICITY_PART__IS_ORDERED;
        case SysMLOCPackage.FOR_LOOP_NODE__IS_NONUNIQUE: return SysMLOCPackage.MULTIPLICITY_PART__IS_NONUNIQUE;
        default: return -1;
      }
    }
    if (baseClass == FeatureSpecializationPart.class)
    {
      switch (derivedFeatureID)
      {
        default: return -1;
      }
    }
    if (baseClass == FeatureDeclaration.class)
    {
      switch (derivedFeatureID)
      {
        default: return -1;
      }
    }
    if (baseClass == UsageDeclaration.class)
    {
      switch (derivedFeatureID)
      {
        default: return -1;
      }
    }
    if (baseClass == ActionNodeUsageDeclaration.class)
    {
      switch (derivedFeatureID)
      {
        default: return -1;
      }
    }
    if (baseClass == ActionNodePrefix.class)
    {
      switch (derivedFeatureID)
      {
        default: return -1;
      }
    }
    return super.eBaseStructuralFeatureID(derivedFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eDerivedStructuralFeatureID(int baseFeatureID, Class<?> baseClass)
  {
    if (baseClass == EmptySuccessionPrefix.class)
    {
      switch (baseFeatureID)
      {
        case SysMLOCPackage.EMPTY_SUCCESSION_PREFIX__IS_THEN: return SysMLOCPackage.FOR_LOOP_NODE__IS_THEN;
        case SysMLOCPackage.EMPTY_SUCCESSION_PREFIX__THEN_MULTIPLICITY: return SysMLOCPackage.FOR_LOOP_NODE__THEN_MULTIPLICITY;
        default: return -1;
      }
    }
    if (baseClass == MemberPrefix.class)
    {
      switch (baseFeatureID)
      {
        case SysMLOCPackage.MEMBER_PREFIX__VISIBILITY: return SysMLOCPackage.FOR_LOOP_NODE__VISIBILITY;
        case SysMLOCPackage.MEMBER_PREFIX__IS_VARIANT: return SysMLOCPackage.FOR_LOOP_NODE__IS_VARIANT;
        default: return -1;
      }
    }
    if (baseClass == BasicDefinitionPrefix.class)
    {
      switch (baseFeatureID)
      {
        case SysMLOCPackage.BASIC_DEFINITION_PREFIX__IS_ABSTRACT: return SysMLOCPackage.FOR_LOOP_NODE__IS_ABSTRACT;
        case SysMLOCPackage.BASIC_DEFINITION_PREFIX__IS_VARIATION: return SysMLOCPackage.FOR_LOOP_NODE__IS_VARIATION;
        default: return -1;
      }
    }
    if (baseClass == RefPrefix.class)
    {
      switch (baseFeatureID)
      {
        case SysMLOCPackage.REF_PREFIX__DIRECTION: return SysMLOCPackage.FOR_LOOP_NODE__DIRECTION;
        case SysMLOCPackage.REF_PREFIX__IS_READ_ONLY: return SysMLOCPackage.FOR_LOOP_NODE__IS_READ_ONLY;
        case SysMLOCPackage.REF_PREFIX__IS_DERIVED: return SysMLOCPackage.FOR_LOOP_NODE__IS_DERIVED;
        default: return -1;
      }
    }
    if (baseClass == BasicUsagePrefix.class)
    {
      switch (baseFeatureID)
      {
        case SysMLOCPackage.BASIC_USAGE_PREFIX__IS_REFERENCE: return SysMLOCPackage.FOR_LOOP_NODE__IS_REFERENCE;
        default: return -1;
      }
    }
    if (baseClass == OccurrenceUsagePrefix.class)
    {
      switch (baseFeatureID)
      {
        case SysMLOCPackage.OCCURRENCE_USAGE_PREFIX__IS_END: return SysMLOCPackage.FOR_LOOP_NODE__IS_END;
        case SysMLOCPackage.OCCURRENCE_USAGE_PREFIX__IS_INDIVIDUAL: return SysMLOCPackage.FOR_LOOP_NODE__IS_INDIVIDUAL;
        case SysMLOCPackage.OCCURRENCE_USAGE_PREFIX__PORTION_KIND: return SysMLOCPackage.FOR_LOOP_NODE__PORTION_KIND;
        default: return -1;
      }
    }
    if (baseClass == Identification.class)
    {
      switch (baseFeatureID)
      {
        case SysMLOCPackage.IDENTIFICATION__DECLARED_SHORT_NAME: return SysMLOCPackage.FOR_LOOP_NODE__DECLARED_SHORT_NAME;
        case SysMLOCPackage.IDENTIFICATION__DECLARED_NAME: return SysMLOCPackage.FOR_LOOP_NODE__DECLARED_NAME;
        default: return -1;
      }
    }
    if (baseClass == TypingFeatureTyping.class)
    {
      switch (baseFeatureID)
      {
        case SysMLOCPackage.TYPING_FEATURE_TYPING__TYPINGS: return SysMLOCPackage.FOR_LOOP_NODE__TYPINGS;
        default: return -1;
      }
    }
    if (baseClass == SubsettingFeatureChain.class)
    {
      switch (baseFeatureID)
      {
        case SysMLOCPackage.SUBSETTING_FEATURE_CHAIN__SUBSETTING: return SysMLOCPackage.FOR_LOOP_NODE__SUBSETTING;
        default: return -1;
      }
    }
    if (baseClass == ReferenceFeatureChain.class)
    {
      switch (baseFeatureID)
      {
        case SysMLOCPackage.REFERENCE_FEATURE_CHAIN__REFERENCES: return SysMLOCPackage.FOR_LOOP_NODE__REFERENCES;
        default: return -1;
      }
    }
    if (baseClass == CrossFeatureChain.class)
    {
      switch (baseFeatureID)
      {
        case SysMLOCPackage.CROSS_FEATURE_CHAIN__CROSSES: return SysMLOCPackage.FOR_LOOP_NODE__CROSSES;
        default: return -1;
      }
    }
    if (baseClass == RedefinitionFeatureChain.class)
    {
      switch (baseFeatureID)
      {
        case SysMLOCPackage.REDEFINITION_FEATURE_CHAIN__REDEFINITIONS: return SysMLOCPackage.FOR_LOOP_NODE__REDEFINITIONS;
        default: return -1;
      }
    }
    if (baseClass == FeatureSpecialization.class)
    {
      switch (baseFeatureID)
      {
        default: return -1;
      }
    }
    if (baseClass == MultiplicityRange.class)
    {
      switch (baseFeatureID)
      {
        case SysMLOCPackage.MULTIPLICITY_RANGE__MULTIPLICITY: return SysMLOCPackage.FOR_LOOP_NODE__MULTIPLICITY;
        default: return -1;
      }
    }
    if (baseClass == MultiplicityPart.class)
    {
      switch (baseFeatureID)
      {
        case SysMLOCPackage.MULTIPLICITY_PART__IS_ORDERED: return SysMLOCPackage.FOR_LOOP_NODE__IS_ORDERED;
        case SysMLOCPackage.MULTIPLICITY_PART__IS_NONUNIQUE: return SysMLOCPackage.FOR_LOOP_NODE__IS_NONUNIQUE;
        default: return -1;
      }
    }
    if (baseClass == FeatureSpecializationPart.class)
    {
      switch (baseFeatureID)
      {
        default: return -1;
      }
    }
    if (baseClass == FeatureDeclaration.class)
    {
      switch (baseFeatureID)
      {
        default: return -1;
      }
    }
    if (baseClass == UsageDeclaration.class)
    {
      switch (baseFeatureID)
      {
        default: return -1;
      }
    }
    if (baseClass == ActionNodeUsageDeclaration.class)
    {
      switch (baseFeatureID)
      {
        default: return -1;
      }
    }
    if (baseClass == ActionNodePrefix.class)
    {
      switch (baseFeatureID)
      {
        default: return -1;
      }
    }
    return super.eDerivedStructuralFeatureID(baseFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (isThen: ");
    result.append(isThen);
    result.append(", ThenMultiplicity: ");
    result.append(thenMultiplicity);
    result.append(", visibility: ");
    result.append(visibility);
    result.append(", isVariant: ");
    result.append(isVariant);
    result.append(", isAbstract: ");
    result.append(isAbstract);
    result.append(", isVariation: ");
    result.append(isVariation);
    result.append(", direction: ");
    result.append(direction);
    result.append(", isReadOnly: ");
    result.append(isReadOnly);
    result.append(", isDerived: ");
    result.append(isDerived);
    result.append(", isReference: ");
    result.append(isReference);
    result.append(", isEnd: ");
    result.append(isEnd);
    result.append(", isIndividual: ");
    result.append(isIndividual);
    result.append(", portionKind: ");
    result.append(portionKind);
    result.append(", declaredShortName: ");
    result.append(declaredShortName);
    result.append(", declaredName: ");
    result.append(declaredName);
    result.append(", typings: ");
    result.append(typings);
    result.append(", subsetting: ");
    result.append(subsetting);
    result.append(", references: ");
    result.append(references);
    result.append(", crosses: ");
    result.append(crosses);
    result.append(", redefinitions: ");
    result.append(redefinitions);
    result.append(", Multiplicity: ");
    result.append(multiplicity);
    result.append(", isOrdered: ");
    result.append(isOrdered);
    result.append(", isNonunique: ");
    result.append(isNonunique);
    result.append(", forNodeParameter: ");
    result.append(forNodeParameter);
    result.append(')');
    return result.toString();
  }

} //ForLoopNodeImpl
