/**
 * generated by Xtext 2.38.0
 */
package dut.control.sysmloc.sysMLOC.impl;

import dut.control.sysmloc.sysMLOC.ImportElement;
import dut.control.sysmloc.sysMLOC.SysMLOCPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Import Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ImportElementImpl extends BaseElementImpl implements ImportElement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ImportElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SysMLOCPackage.Literals.IMPORT_ELEMENT;
  }

} //ImportElementImpl
