/**
 * generated by Xtext 2.38.0
 */
package dut.control.sysmloc.sysMLOC.impl;

import dut.control.sysmloc.sysMLOC.SysMLOCPackage;
import dut.control.sysmloc.sysMLOC.isImportAllFragment;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>is Import All Fragment</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.isImportAllFragmentImpl#isIsImportAll <em>Is Import All</em>}</li>
 * </ul>
 *
 * @generated
 */
public class isImportAllFragmentImpl extends MinimalEObjectImpl.Container implements isImportAllFragment
{
  /**
   * The default value of the '{@link #isIsImportAll() <em>Is Import All</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsImportAll()
   * @generated
   * @ordered
   */
  protected static final boolean IS_IMPORT_ALL_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsImportAll() <em>Is Import All</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsImportAll()
   * @generated
   * @ordered
   */
  protected boolean isImportAll = IS_IMPORT_ALL_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected isImportAllFragmentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SysMLOCPackage.eINSTANCE.getisImportAllFragment();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsImportAll()
  {
    return isImportAll;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsImportAll(boolean newIsImportAll)
  {
    boolean oldIsImportAll = isImportAll;
    isImportAll = newIsImportAll;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLOCPackage.IS_IMPORT_ALL_FRAGMENT__IS_IMPORT_ALL, oldIsImportAll, isImportAll));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SysMLOCPackage.IS_IMPORT_ALL_FRAGMENT__IS_IMPORT_ALL:
        return isIsImportAll();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SysMLOCPackage.IS_IMPORT_ALL_FRAGMENT__IS_IMPORT_ALL:
        setIsImportAll((Boolean)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SysMLOCPackage.IS_IMPORT_ALL_FRAGMENT__IS_IMPORT_ALL:
        setIsImportAll(IS_IMPORT_ALL_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SysMLOCPackage.IS_IMPORT_ALL_FRAGMENT__IS_IMPORT_ALL:
        return isImportAll != IS_IMPORT_ALL_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (isImportAll: ");
    result.append(isImportAll);
    result.append(')');
    return result.toString();
  }

} //isImportAllFragmentImpl
