/**
 * generated by Xtext 2.38.0
 */
package dut.control.sysmloc.sysMLOC.impl;

import dut.control.sysmloc.sysMLOC.ItemFeatureParameter;
import dut.control.sysmloc.sysMLOC.ItemFeatureParameterPart;
import dut.control.sysmloc.sysMLOC.SysMLOCPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Item Feature Parameter Part</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.ItemFeatureParameterPartImpl#getItemFeatureParameter <em>Item Feature Parameter</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ItemFeatureParameterPartImpl extends MinimalEObjectImpl.Container implements ItemFeatureParameterPart
{
  /**
   * The cached value of the '{@link #getItemFeatureParameter() <em>Item Feature Parameter</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getItemFeatureParameter()
   * @generated
   * @ordered
   */
  protected EList<ItemFeatureParameter> itemFeatureParameter;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ItemFeatureParameterPartImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SysMLOCPackage.eINSTANCE.getItemFeatureParameterPart();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ItemFeatureParameter> getItemFeatureParameter()
  {
    if (itemFeatureParameter == null)
    {
      itemFeatureParameter = new EObjectContainmentEList<ItemFeatureParameter>(ItemFeatureParameter.class, this, SysMLOCPackage.ITEM_FEATURE_PARAMETER_PART__ITEM_FEATURE_PARAMETER);
    }
    return itemFeatureParameter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SysMLOCPackage.ITEM_FEATURE_PARAMETER_PART__ITEM_FEATURE_PARAMETER:
        return ((InternalEList<?>)getItemFeatureParameter()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SysMLOCPackage.ITEM_FEATURE_PARAMETER_PART__ITEM_FEATURE_PARAMETER:
        return getItemFeatureParameter();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SysMLOCPackage.ITEM_FEATURE_PARAMETER_PART__ITEM_FEATURE_PARAMETER:
        getItemFeatureParameter().clear();
        getItemFeatureParameter().addAll((Collection<? extends ItemFeatureParameter>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SysMLOCPackage.ITEM_FEATURE_PARAMETER_PART__ITEM_FEATURE_PARAMETER:
        getItemFeatureParameter().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SysMLOCPackage.ITEM_FEATURE_PARAMETER_PART__ITEM_FEATURE_PARAMETER:
        return itemFeatureParameter != null && !itemFeatureParameter.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ItemFeatureParameterPartImpl
