/**
 * generated by Xtext 2.38.0
 */
package dut.control.sysmloc.sysMLOC.impl;

import dut.control.sysmloc.sysMLOC.Identification;
import dut.control.sysmloc.sysMLOC.LibraryPackage;
import dut.control.sysmloc.sysMLOC.PackageBodyElement;
import dut.control.sysmloc.sysMLOC.PrefixMetadata;
import dut.control.sysmloc.sysMLOC.SysMLOCPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Library Package</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.LibraryPackageImpl#getPrefixMetadataExtension <em>Prefix Metadata Extension</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.LibraryPackageImpl#getDeclaredShortName <em>Declared Short Name</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.LibraryPackageImpl#getDeclaredName <em>Declared Name</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.LibraryPackageImpl#isIsStandard <em>Is Standard</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.LibraryPackageImpl#isIsLibrary <em>Is Library</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.LibraryPackageImpl#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LibraryPackageImpl extends DefinitionElementImpl implements LibraryPackage
{
  /**
   * The cached value of the '{@link #getPrefixMetadataExtension() <em>Prefix Metadata Extension</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrefixMetadataExtension()
   * @generated
   * @ordered
   */
  protected EList<String> prefixMetadataExtension;

  /**
   * The default value of the '{@link #getDeclaredShortName() <em>Declared Short Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDeclaredShortName()
   * @generated
   * @ordered
   */
  protected static final String DECLARED_SHORT_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDeclaredShortName() <em>Declared Short Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDeclaredShortName()
   * @generated
   * @ordered
   */
  protected String declaredShortName = DECLARED_SHORT_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getDeclaredName() <em>Declared Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDeclaredName()
   * @generated
   * @ordered
   */
  protected static final String DECLARED_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDeclaredName() <em>Declared Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDeclaredName()
   * @generated
   * @ordered
   */
  protected String declaredName = DECLARED_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #isIsStandard() <em>Is Standard</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsStandard()
   * @generated
   * @ordered
   */
  protected static final boolean IS_STANDARD_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsStandard() <em>Is Standard</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsStandard()
   * @generated
   * @ordered
   */
  protected boolean isStandard = IS_STANDARD_EDEFAULT;

  /**
   * The default value of the '{@link #isIsLibrary() <em>Is Library</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsLibrary()
   * @generated
   * @ordered
   */
  protected static final boolean IS_LIBRARY_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsLibrary() <em>Is Library</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsLibrary()
   * @generated
   * @ordered
   */
  protected boolean isLibrary = IS_LIBRARY_EDEFAULT;

  /**
   * The cached value of the '{@link #getElements() <em>Elements</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getElements()
   * @generated
   * @ordered
   */
  protected EList<PackageBodyElement> elements;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LibraryPackageImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SysMLOCPackage.eINSTANCE.getLibraryPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getPrefixMetadataExtension()
  {
    if (prefixMetadataExtension == null)
    {
      prefixMetadataExtension = new EDataTypeEList<String>(String.class, this, SysMLOCPackage.LIBRARY_PACKAGE__PREFIX_METADATA_EXTENSION);
    }
    return prefixMetadataExtension;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDeclaredShortName()
  {
    return declaredShortName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDeclaredShortName(String newDeclaredShortName)
  {
    String oldDeclaredShortName = declaredShortName;
    declaredShortName = newDeclaredShortName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLOCPackage.LIBRARY_PACKAGE__DECLARED_SHORT_NAME, oldDeclaredShortName, declaredShortName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDeclaredName()
  {
    return declaredName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDeclaredName(String newDeclaredName)
  {
    String oldDeclaredName = declaredName;
    declaredName = newDeclaredName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLOCPackage.LIBRARY_PACKAGE__DECLARED_NAME, oldDeclaredName, declaredName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsStandard()
  {
    return isStandard;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsStandard(boolean newIsStandard)
  {
    boolean oldIsStandard = isStandard;
    isStandard = newIsStandard;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLOCPackage.LIBRARY_PACKAGE__IS_STANDARD, oldIsStandard, isStandard));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsLibrary()
  {
    return isLibrary;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsLibrary(boolean newIsLibrary)
  {
    boolean oldIsLibrary = isLibrary;
    isLibrary = newIsLibrary;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLOCPackage.LIBRARY_PACKAGE__IS_LIBRARY, oldIsLibrary, isLibrary));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<PackageBodyElement> getElements()
  {
    if (elements == null)
    {
      elements = new EObjectContainmentEList<PackageBodyElement>(PackageBodyElement.class, this, SysMLOCPackage.LIBRARY_PACKAGE__ELEMENTS);
    }
    return elements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SysMLOCPackage.LIBRARY_PACKAGE__ELEMENTS:
        return ((InternalEList<?>)getElements()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SysMLOCPackage.LIBRARY_PACKAGE__PREFIX_METADATA_EXTENSION:
        return getPrefixMetadataExtension();
      case SysMLOCPackage.LIBRARY_PACKAGE__DECLARED_SHORT_NAME:
        return getDeclaredShortName();
      case SysMLOCPackage.LIBRARY_PACKAGE__DECLARED_NAME:
        return getDeclaredName();
      case SysMLOCPackage.LIBRARY_PACKAGE__IS_STANDARD:
        return isIsStandard();
      case SysMLOCPackage.LIBRARY_PACKAGE__IS_LIBRARY:
        return isIsLibrary();
      case SysMLOCPackage.LIBRARY_PACKAGE__ELEMENTS:
        return getElements();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SysMLOCPackage.LIBRARY_PACKAGE__PREFIX_METADATA_EXTENSION:
        getPrefixMetadataExtension().clear();
        getPrefixMetadataExtension().addAll((Collection<? extends String>)newValue);
        return;
      case SysMLOCPackage.LIBRARY_PACKAGE__DECLARED_SHORT_NAME:
        setDeclaredShortName((String)newValue);
        return;
      case SysMLOCPackage.LIBRARY_PACKAGE__DECLARED_NAME:
        setDeclaredName((String)newValue);
        return;
      case SysMLOCPackage.LIBRARY_PACKAGE__IS_STANDARD:
        setIsStandard((Boolean)newValue);
        return;
      case SysMLOCPackage.LIBRARY_PACKAGE__IS_LIBRARY:
        setIsLibrary((Boolean)newValue);
        return;
      case SysMLOCPackage.LIBRARY_PACKAGE__ELEMENTS:
        getElements().clear();
        getElements().addAll((Collection<? extends PackageBodyElement>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SysMLOCPackage.LIBRARY_PACKAGE__PREFIX_METADATA_EXTENSION:
        getPrefixMetadataExtension().clear();
        return;
      case SysMLOCPackage.LIBRARY_PACKAGE__DECLARED_SHORT_NAME:
        setDeclaredShortName(DECLARED_SHORT_NAME_EDEFAULT);
        return;
      case SysMLOCPackage.LIBRARY_PACKAGE__DECLARED_NAME:
        setDeclaredName(DECLARED_NAME_EDEFAULT);
        return;
      case SysMLOCPackage.LIBRARY_PACKAGE__IS_STANDARD:
        setIsStandard(IS_STANDARD_EDEFAULT);
        return;
      case SysMLOCPackage.LIBRARY_PACKAGE__IS_LIBRARY:
        setIsLibrary(IS_LIBRARY_EDEFAULT);
        return;
      case SysMLOCPackage.LIBRARY_PACKAGE__ELEMENTS:
        getElements().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SysMLOCPackage.LIBRARY_PACKAGE__PREFIX_METADATA_EXTENSION:
        return prefixMetadataExtension != null && !prefixMetadataExtension.isEmpty();
      case SysMLOCPackage.LIBRARY_PACKAGE__DECLARED_SHORT_NAME:
        return DECLARED_SHORT_NAME_EDEFAULT == null ? declaredShortName != null : !DECLARED_SHORT_NAME_EDEFAULT.equals(declaredShortName);
      case SysMLOCPackage.LIBRARY_PACKAGE__DECLARED_NAME:
        return DECLARED_NAME_EDEFAULT == null ? declaredName != null : !DECLARED_NAME_EDEFAULT.equals(declaredName);
      case SysMLOCPackage.LIBRARY_PACKAGE__IS_STANDARD:
        return isStandard != IS_STANDARD_EDEFAULT;
      case SysMLOCPackage.LIBRARY_PACKAGE__IS_LIBRARY:
        return isLibrary != IS_LIBRARY_EDEFAULT;
      case SysMLOCPackage.LIBRARY_PACKAGE__ELEMENTS:
        return elements != null && !elements.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eBaseStructuralFeatureID(int derivedFeatureID, Class<?> baseClass)
  {
    if (baseClass == PrefixMetadata.class)
    {
      switch (derivedFeatureID)
      {
        case SysMLOCPackage.LIBRARY_PACKAGE__PREFIX_METADATA_EXTENSION: return SysMLOCPackage.PREFIX_METADATA__PREFIX_METADATA_EXTENSION;
        default: return -1;
      }
    }
    if (baseClass == Identification.class)
    {
      switch (derivedFeatureID)
      {
        case SysMLOCPackage.LIBRARY_PACKAGE__DECLARED_SHORT_NAME: return SysMLOCPackage.IDENTIFICATION__DECLARED_SHORT_NAME;
        case SysMLOCPackage.LIBRARY_PACKAGE__DECLARED_NAME: return SysMLOCPackage.IDENTIFICATION__DECLARED_NAME;
        default: return -1;
      }
    }
    return super.eBaseStructuralFeatureID(derivedFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eDerivedStructuralFeatureID(int baseFeatureID, Class<?> baseClass)
  {
    if (baseClass == PrefixMetadata.class)
    {
      switch (baseFeatureID)
      {
        case SysMLOCPackage.PREFIX_METADATA__PREFIX_METADATA_EXTENSION: return SysMLOCPackage.LIBRARY_PACKAGE__PREFIX_METADATA_EXTENSION;
        default: return -1;
      }
    }
    if (baseClass == Identification.class)
    {
      switch (baseFeatureID)
      {
        case SysMLOCPackage.IDENTIFICATION__DECLARED_SHORT_NAME: return SysMLOCPackage.LIBRARY_PACKAGE__DECLARED_SHORT_NAME;
        case SysMLOCPackage.IDENTIFICATION__DECLARED_NAME: return SysMLOCPackage.LIBRARY_PACKAGE__DECLARED_NAME;
        default: return -1;
      }
    }
    return super.eDerivedStructuralFeatureID(baseFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (prefixMetadataExtension: ");
    result.append(prefixMetadataExtension);
    result.append(", declaredShortName: ");
    result.append(declaredShortName);
    result.append(", declaredName: ");
    result.append(declaredName);
    result.append(", isStandard: ");
    result.append(isStandard);
    result.append(", isLibrary: ");
    result.append(isLibrary);
    result.append(')');
    return result.toString();
  }

} //LibraryPackageImpl
