/**
 * generated by Xtext 2.38.0
 */
package dut.control.sysmloc.sysMLOC.impl;

import dut.control.sysmloc.sysMLOC.CrossFeatureChain;
import dut.control.sysmloc.sysMLOC.FeatureSpecialization;
import dut.control.sysmloc.sysMLOC.FeatureValue;
import dut.control.sysmloc.sysMLOC.MultiplicityModifiers;
import dut.control.sysmloc.sysMLOC.MultiplicityPart;
import dut.control.sysmloc.sysMLOC.MultiplicityRange;
import dut.control.sysmloc.sysMLOC.PayloadFeature;
import dut.control.sysmloc.sysMLOC.PayloadFeatureSpecializationPart;
import dut.control.sysmloc.sysMLOC.RedefinitionFeatureChain;
import dut.control.sysmloc.sysMLOC.ReferenceFeatureChain;
import dut.control.sysmloc.sysMLOC.SubsettingFeatureChain;
import dut.control.sysmloc.sysMLOC.SysMLOCPackage;
import dut.control.sysmloc.sysMLOC.TypingFeatureTyping;
import dut.control.sysmloc.sysMLOC.ValuePart;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Payload Feature</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.PayloadFeatureImpl#getTypings <em>Typings</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.PayloadFeatureImpl#getSubsetting <em>Subsetting</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.PayloadFeatureImpl#getReferences <em>References</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.PayloadFeatureImpl#getCrosses <em>Crosses</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.PayloadFeatureImpl#getRedefinitions <em>Redefinitions</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.PayloadFeatureImpl#getMultiValue <em>Multi Value</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.PayloadFeatureImpl#getMultiLow <em>Multi Low</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.PayloadFeatureImpl#getMultiHigh <em>Multi High</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.PayloadFeatureImpl#isIsOrdered <em>Is Ordered</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.PayloadFeatureImpl#isIsNonunique <em>Is Nonunique</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.PayloadFeatureImpl#isIsInitial <em>Is Initial</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.PayloadFeatureImpl#isIsDefault <em>Is Default</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.PayloadFeatureImpl#getValuePart <em>Value Part</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.PayloadFeatureImpl#getPayloadFeatureElement <em>Payload Feature Element</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PayloadFeatureImpl extends IdentificationImpl implements PayloadFeature
{
  /**
   * The cached value of the '{@link #getTypings() <em>Typings</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypings()
   * @generated
   * @ordered
   */
  protected EList<String> typings;

  /**
   * The cached value of the '{@link #getSubsetting() <em>Subsetting</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubsetting()
   * @generated
   * @ordered
   */
  protected EList<String> subsetting;

  /**
   * The cached value of the '{@link #getReferences() <em>References</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReferences()
   * @generated
   * @ordered
   */
  protected EList<String> references;

  /**
   * The cached value of the '{@link #getCrosses() <em>Crosses</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCrosses()
   * @generated
   * @ordered
   */
  protected EList<String> crosses;

  /**
   * The cached value of the '{@link #getRedefinitions() <em>Redefinitions</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRedefinitions()
   * @generated
   * @ordered
   */
  protected EList<String> redefinitions;

  /**
   * The default value of the '{@link #getMultiValue() <em>Multi Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMultiValue()
   * @generated
   * @ordered
   */
  protected static final String MULTI_VALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMultiValue() <em>Multi Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMultiValue()
   * @generated
   * @ordered
   */
  protected String multiValue = MULTI_VALUE_EDEFAULT;

  /**
   * The default value of the '{@link #getMultiLow() <em>Multi Low</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMultiLow()
   * @generated
   * @ordered
   */
  protected static final String MULTI_LOW_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMultiLow() <em>Multi Low</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMultiLow()
   * @generated
   * @ordered
   */
  protected String multiLow = MULTI_LOW_EDEFAULT;

  /**
   * The default value of the '{@link #getMultiHigh() <em>Multi High</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMultiHigh()
   * @generated
   * @ordered
   */
  protected static final String MULTI_HIGH_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMultiHigh() <em>Multi High</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMultiHigh()
   * @generated
   * @ordered
   */
  protected String multiHigh = MULTI_HIGH_EDEFAULT;

  /**
   * The default value of the '{@link #isIsOrdered() <em>Is Ordered</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsOrdered()
   * @generated
   * @ordered
   */
  protected static final boolean IS_ORDERED_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsOrdered() <em>Is Ordered</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsOrdered()
   * @generated
   * @ordered
   */
  protected boolean isOrdered = IS_ORDERED_EDEFAULT;

  /**
   * The default value of the '{@link #isIsNonunique() <em>Is Nonunique</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsNonunique()
   * @generated
   * @ordered
   */
  protected static final boolean IS_NONUNIQUE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsNonunique() <em>Is Nonunique</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsNonunique()
   * @generated
   * @ordered
   */
  protected boolean isNonunique = IS_NONUNIQUE_EDEFAULT;

  /**
   * The default value of the '{@link #isIsInitial() <em>Is Initial</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsInitial()
   * @generated
   * @ordered
   */
  protected static final boolean IS_INITIAL_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsInitial() <em>Is Initial</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsInitial()
   * @generated
   * @ordered
   */
  protected boolean isInitial = IS_INITIAL_EDEFAULT;

  /**
   * The default value of the '{@link #isIsDefault() <em>Is Default</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsDefault()
   * @generated
   * @ordered
   */
  protected static final boolean IS_DEFAULT_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsDefault() <em>Is Default</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsDefault()
   * @generated
   * @ordered
   */
  protected boolean isDefault = IS_DEFAULT_EDEFAULT;

  /**
   * The default value of the '{@link #getValuePart() <em>Value Part</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValuePart()
   * @generated
   * @ordered
   */
  protected static final String VALUE_PART_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getValuePart() <em>Value Part</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValuePart()
   * @generated
   * @ordered
   */
  protected String valuePart = VALUE_PART_EDEFAULT;

  /**
   * The default value of the '{@link #getPayloadFeatureElement() <em>Payload Feature Element</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPayloadFeatureElement()
   * @generated
   * @ordered
   */
  protected static final String PAYLOAD_FEATURE_ELEMENT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPayloadFeatureElement() <em>Payload Feature Element</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPayloadFeatureElement()
   * @generated
   * @ordered
   */
  protected String payloadFeatureElement = PAYLOAD_FEATURE_ELEMENT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PayloadFeatureImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SysMLOCPackage.eINSTANCE.getPayloadFeature();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getTypings()
  {
    if (typings == null)
    {
      typings = new EDataTypeEList<String>(String.class, this, SysMLOCPackage.PAYLOAD_FEATURE__TYPINGS);
    }
    return typings;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getSubsetting()
  {
    if (subsetting == null)
    {
      subsetting = new EDataTypeEList<String>(String.class, this, SysMLOCPackage.PAYLOAD_FEATURE__SUBSETTING);
    }
    return subsetting;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getReferences()
  {
    if (references == null)
    {
      references = new EDataTypeEList<String>(String.class, this, SysMLOCPackage.PAYLOAD_FEATURE__REFERENCES);
    }
    return references;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getCrosses()
  {
    if (crosses == null)
    {
      crosses = new EDataTypeEList<String>(String.class, this, SysMLOCPackage.PAYLOAD_FEATURE__CROSSES);
    }
    return crosses;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getRedefinitions()
  {
    if (redefinitions == null)
    {
      redefinitions = new EDataTypeEList<String>(String.class, this, SysMLOCPackage.PAYLOAD_FEATURE__REDEFINITIONS);
    }
    return redefinitions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getMultiValue()
  {
    return multiValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMultiValue(String newMultiValue)
  {
    String oldMultiValue = multiValue;
    multiValue = newMultiValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLOCPackage.PAYLOAD_FEATURE__MULTI_VALUE, oldMultiValue, multiValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getMultiLow()
  {
    return multiLow;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMultiLow(String newMultiLow)
  {
    String oldMultiLow = multiLow;
    multiLow = newMultiLow;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLOCPackage.PAYLOAD_FEATURE__MULTI_LOW, oldMultiLow, multiLow));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getMultiHigh()
  {
    return multiHigh;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMultiHigh(String newMultiHigh)
  {
    String oldMultiHigh = multiHigh;
    multiHigh = newMultiHigh;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLOCPackage.PAYLOAD_FEATURE__MULTI_HIGH, oldMultiHigh, multiHigh));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsOrdered()
  {
    return isOrdered;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsOrdered(boolean newIsOrdered)
  {
    boolean oldIsOrdered = isOrdered;
    isOrdered = newIsOrdered;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLOCPackage.PAYLOAD_FEATURE__IS_ORDERED, oldIsOrdered, isOrdered));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsNonunique()
  {
    return isNonunique;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsNonunique(boolean newIsNonunique)
  {
    boolean oldIsNonunique = isNonunique;
    isNonunique = newIsNonunique;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLOCPackage.PAYLOAD_FEATURE__IS_NONUNIQUE, oldIsNonunique, isNonunique));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsInitial()
  {
    return isInitial;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsInitial(boolean newIsInitial)
  {
    boolean oldIsInitial = isInitial;
    isInitial = newIsInitial;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLOCPackage.PAYLOAD_FEATURE__IS_INITIAL, oldIsInitial, isInitial));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsDefault()
  {
    return isDefault;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsDefault(boolean newIsDefault)
  {
    boolean oldIsDefault = isDefault;
    isDefault = newIsDefault;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLOCPackage.PAYLOAD_FEATURE__IS_DEFAULT, oldIsDefault, isDefault));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getValuePart()
  {
    return valuePart;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setValuePart(String newValuePart)
  {
    String oldValuePart = valuePart;
    valuePart = newValuePart;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLOCPackage.PAYLOAD_FEATURE__VALUE_PART, oldValuePart, valuePart));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPayloadFeatureElement()
  {
    return payloadFeatureElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPayloadFeatureElement(String newPayloadFeatureElement)
  {
    String oldPayloadFeatureElement = payloadFeatureElement;
    payloadFeatureElement = newPayloadFeatureElement;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SysMLOCPackage.PAYLOAD_FEATURE__PAYLOAD_FEATURE_ELEMENT, oldPayloadFeatureElement, payloadFeatureElement));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SysMLOCPackage.PAYLOAD_FEATURE__TYPINGS:
        return getTypings();
      case SysMLOCPackage.PAYLOAD_FEATURE__SUBSETTING:
        return getSubsetting();
      case SysMLOCPackage.PAYLOAD_FEATURE__REFERENCES:
        return getReferences();
      case SysMLOCPackage.PAYLOAD_FEATURE__CROSSES:
        return getCrosses();
      case SysMLOCPackage.PAYLOAD_FEATURE__REDEFINITIONS:
        return getRedefinitions();
      case SysMLOCPackage.PAYLOAD_FEATURE__MULTI_VALUE:
        return getMultiValue();
      case SysMLOCPackage.PAYLOAD_FEATURE__MULTI_LOW:
        return getMultiLow();
      case SysMLOCPackage.PAYLOAD_FEATURE__MULTI_HIGH:
        return getMultiHigh();
      case SysMLOCPackage.PAYLOAD_FEATURE__IS_ORDERED:
        return isIsOrdered();
      case SysMLOCPackage.PAYLOAD_FEATURE__IS_NONUNIQUE:
        return isIsNonunique();
      case SysMLOCPackage.PAYLOAD_FEATURE__IS_INITIAL:
        return isIsInitial();
      case SysMLOCPackage.PAYLOAD_FEATURE__IS_DEFAULT:
        return isIsDefault();
      case SysMLOCPackage.PAYLOAD_FEATURE__VALUE_PART:
        return getValuePart();
      case SysMLOCPackage.PAYLOAD_FEATURE__PAYLOAD_FEATURE_ELEMENT:
        return getPayloadFeatureElement();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SysMLOCPackage.PAYLOAD_FEATURE__TYPINGS:
        getTypings().clear();
        getTypings().addAll((Collection<? extends String>)newValue);
        return;
      case SysMLOCPackage.PAYLOAD_FEATURE__SUBSETTING:
        getSubsetting().clear();
        getSubsetting().addAll((Collection<? extends String>)newValue);
        return;
      case SysMLOCPackage.PAYLOAD_FEATURE__REFERENCES:
        getReferences().clear();
        getReferences().addAll((Collection<? extends String>)newValue);
        return;
      case SysMLOCPackage.PAYLOAD_FEATURE__CROSSES:
        getCrosses().clear();
        getCrosses().addAll((Collection<? extends String>)newValue);
        return;
      case SysMLOCPackage.PAYLOAD_FEATURE__REDEFINITIONS:
        getRedefinitions().clear();
        getRedefinitions().addAll((Collection<? extends String>)newValue);
        return;
      case SysMLOCPackage.PAYLOAD_FEATURE__MULTI_VALUE:
        setMultiValue((String)newValue);
        return;
      case SysMLOCPackage.PAYLOAD_FEATURE__MULTI_LOW:
        setMultiLow((String)newValue);
        return;
      case SysMLOCPackage.PAYLOAD_FEATURE__MULTI_HIGH:
        setMultiHigh((String)newValue);
        return;
      case SysMLOCPackage.PAYLOAD_FEATURE__IS_ORDERED:
        setIsOrdered((Boolean)newValue);
        return;
      case SysMLOCPackage.PAYLOAD_FEATURE__IS_NONUNIQUE:
        setIsNonunique((Boolean)newValue);
        return;
      case SysMLOCPackage.PAYLOAD_FEATURE__IS_INITIAL:
        setIsInitial((Boolean)newValue);
        return;
      case SysMLOCPackage.PAYLOAD_FEATURE__IS_DEFAULT:
        setIsDefault((Boolean)newValue);
        return;
      case SysMLOCPackage.PAYLOAD_FEATURE__VALUE_PART:
        setValuePart((String)newValue);
        return;
      case SysMLOCPackage.PAYLOAD_FEATURE__PAYLOAD_FEATURE_ELEMENT:
        setPayloadFeatureElement((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SysMLOCPackage.PAYLOAD_FEATURE__TYPINGS:
        getTypings().clear();
        return;
      case SysMLOCPackage.PAYLOAD_FEATURE__SUBSETTING:
        getSubsetting().clear();
        return;
      case SysMLOCPackage.PAYLOAD_FEATURE__REFERENCES:
        getReferences().clear();
        return;
      case SysMLOCPackage.PAYLOAD_FEATURE__CROSSES:
        getCrosses().clear();
        return;
      case SysMLOCPackage.PAYLOAD_FEATURE__REDEFINITIONS:
        getRedefinitions().clear();
        return;
      case SysMLOCPackage.PAYLOAD_FEATURE__MULTI_VALUE:
        setMultiValue(MULTI_VALUE_EDEFAULT);
        return;
      case SysMLOCPackage.PAYLOAD_FEATURE__MULTI_LOW:
        setMultiLow(MULTI_LOW_EDEFAULT);
        return;
      case SysMLOCPackage.PAYLOAD_FEATURE__MULTI_HIGH:
        setMultiHigh(MULTI_HIGH_EDEFAULT);
        return;
      case SysMLOCPackage.PAYLOAD_FEATURE__IS_ORDERED:
        setIsOrdered(IS_ORDERED_EDEFAULT);
        return;
      case SysMLOCPackage.PAYLOAD_FEATURE__IS_NONUNIQUE:
        setIsNonunique(IS_NONUNIQUE_EDEFAULT);
        return;
      case SysMLOCPackage.PAYLOAD_FEATURE__IS_INITIAL:
        setIsInitial(IS_INITIAL_EDEFAULT);
        return;
      case SysMLOCPackage.PAYLOAD_FEATURE__IS_DEFAULT:
        setIsDefault(IS_DEFAULT_EDEFAULT);
        return;
      case SysMLOCPackage.PAYLOAD_FEATURE__VALUE_PART:
        setValuePart(VALUE_PART_EDEFAULT);
        return;
      case SysMLOCPackage.PAYLOAD_FEATURE__PAYLOAD_FEATURE_ELEMENT:
        setPayloadFeatureElement(PAYLOAD_FEATURE_ELEMENT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SysMLOCPackage.PAYLOAD_FEATURE__TYPINGS:
        return typings != null && !typings.isEmpty();
      case SysMLOCPackage.PAYLOAD_FEATURE__SUBSETTING:
        return subsetting != null && !subsetting.isEmpty();
      case SysMLOCPackage.PAYLOAD_FEATURE__REFERENCES:
        return references != null && !references.isEmpty();
      case SysMLOCPackage.PAYLOAD_FEATURE__CROSSES:
        return crosses != null && !crosses.isEmpty();
      case SysMLOCPackage.PAYLOAD_FEATURE__REDEFINITIONS:
        return redefinitions != null && !redefinitions.isEmpty();
      case SysMLOCPackage.PAYLOAD_FEATURE__MULTI_VALUE:
        return MULTI_VALUE_EDEFAULT == null ? multiValue != null : !MULTI_VALUE_EDEFAULT.equals(multiValue);
      case SysMLOCPackage.PAYLOAD_FEATURE__MULTI_LOW:
        return MULTI_LOW_EDEFAULT == null ? multiLow != null : !MULTI_LOW_EDEFAULT.equals(multiLow);
      case SysMLOCPackage.PAYLOAD_FEATURE__MULTI_HIGH:
        return MULTI_HIGH_EDEFAULT == null ? multiHigh != null : !MULTI_HIGH_EDEFAULT.equals(multiHigh);
      case SysMLOCPackage.PAYLOAD_FEATURE__IS_ORDERED:
        return isOrdered != IS_ORDERED_EDEFAULT;
      case SysMLOCPackage.PAYLOAD_FEATURE__IS_NONUNIQUE:
        return isNonunique != IS_NONUNIQUE_EDEFAULT;
      case SysMLOCPackage.PAYLOAD_FEATURE__IS_INITIAL:
        return isInitial != IS_INITIAL_EDEFAULT;
      case SysMLOCPackage.PAYLOAD_FEATURE__IS_DEFAULT:
        return isDefault != IS_DEFAULT_EDEFAULT;
      case SysMLOCPackage.PAYLOAD_FEATURE__VALUE_PART:
        return VALUE_PART_EDEFAULT == null ? valuePart != null : !VALUE_PART_EDEFAULT.equals(valuePart);
      case SysMLOCPackage.PAYLOAD_FEATURE__PAYLOAD_FEATURE_ELEMENT:
        return PAYLOAD_FEATURE_ELEMENT_EDEFAULT == null ? payloadFeatureElement != null : !PAYLOAD_FEATURE_ELEMENT_EDEFAULT.equals(payloadFeatureElement);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eBaseStructuralFeatureID(int derivedFeatureID, Class<?> baseClass)
  {
    if (baseClass == TypingFeatureTyping.class)
    {
      switch (derivedFeatureID)
      {
        case SysMLOCPackage.PAYLOAD_FEATURE__TYPINGS: return SysMLOCPackage.TYPING_FEATURE_TYPING__TYPINGS;
        default: return -1;
      }
    }
    if (baseClass == SubsettingFeatureChain.class)
    {
      switch (derivedFeatureID)
      {
        case SysMLOCPackage.PAYLOAD_FEATURE__SUBSETTING: return SysMLOCPackage.SUBSETTING_FEATURE_CHAIN__SUBSETTING;
        default: return -1;
      }
    }
    if (baseClass == ReferenceFeatureChain.class)
    {
      switch (derivedFeatureID)
      {
        case SysMLOCPackage.PAYLOAD_FEATURE__REFERENCES: return SysMLOCPackage.REFERENCE_FEATURE_CHAIN__REFERENCES;
        default: return -1;
      }
    }
    if (baseClass == CrossFeatureChain.class)
    {
      switch (derivedFeatureID)
      {
        case SysMLOCPackage.PAYLOAD_FEATURE__CROSSES: return SysMLOCPackage.CROSS_FEATURE_CHAIN__CROSSES;
        default: return -1;
      }
    }
    if (baseClass == RedefinitionFeatureChain.class)
    {
      switch (derivedFeatureID)
      {
        case SysMLOCPackage.PAYLOAD_FEATURE__REDEFINITIONS: return SysMLOCPackage.REDEFINITION_FEATURE_CHAIN__REDEFINITIONS;
        default: return -1;
      }
    }
    if (baseClass == FeatureSpecialization.class)
    {
      switch (derivedFeatureID)
      {
        default: return -1;
      }
    }
    if (baseClass == MultiplicityRange.class)
    {
      switch (derivedFeatureID)
      {
        case SysMLOCPackage.PAYLOAD_FEATURE__MULTI_VALUE: return SysMLOCPackage.MULTIPLICITY_RANGE__MULTI_VALUE;
        case SysMLOCPackage.PAYLOAD_FEATURE__MULTI_LOW: return SysMLOCPackage.MULTIPLICITY_RANGE__MULTI_LOW;
        case SysMLOCPackage.PAYLOAD_FEATURE__MULTI_HIGH: return SysMLOCPackage.MULTIPLICITY_RANGE__MULTI_HIGH;
        default: return -1;
      }
    }
    if (baseClass == MultiplicityModifiers.class)
    {
      switch (derivedFeatureID)
      {
        case SysMLOCPackage.PAYLOAD_FEATURE__IS_ORDERED: return SysMLOCPackage.MULTIPLICITY_MODIFIERS__IS_ORDERED;
        case SysMLOCPackage.PAYLOAD_FEATURE__IS_NONUNIQUE: return SysMLOCPackage.MULTIPLICITY_MODIFIERS__IS_NONUNIQUE;
        default: return -1;
      }
    }
    if (baseClass == MultiplicityPart.class)
    {
      switch (derivedFeatureID)
      {
        default: return -1;
      }
    }
    if (baseClass == PayloadFeatureSpecializationPart.class)
    {
      switch (derivedFeatureID)
      {
        default: return -1;
      }
    }
    if (baseClass == FeatureValue.class)
    {
      switch (derivedFeatureID)
      {
        case SysMLOCPackage.PAYLOAD_FEATURE__IS_INITIAL: return SysMLOCPackage.FEATURE_VALUE__IS_INITIAL;
        case SysMLOCPackage.PAYLOAD_FEATURE__IS_DEFAULT: return SysMLOCPackage.FEATURE_VALUE__IS_DEFAULT;
        case SysMLOCPackage.PAYLOAD_FEATURE__VALUE_PART: return SysMLOCPackage.FEATURE_VALUE__VALUE_PART;
        default: return -1;
      }
    }
    if (baseClass == ValuePart.class)
    {
      switch (derivedFeatureID)
      {
        default: return -1;
      }
    }
    return super.eBaseStructuralFeatureID(derivedFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eDerivedStructuralFeatureID(int baseFeatureID, Class<?> baseClass)
  {
    if (baseClass == TypingFeatureTyping.class)
    {
      switch (baseFeatureID)
      {
        case SysMLOCPackage.TYPING_FEATURE_TYPING__TYPINGS: return SysMLOCPackage.PAYLOAD_FEATURE__TYPINGS;
        default: return -1;
      }
    }
    if (baseClass == SubsettingFeatureChain.class)
    {
      switch (baseFeatureID)
      {
        case SysMLOCPackage.SUBSETTING_FEATURE_CHAIN__SUBSETTING: return SysMLOCPackage.PAYLOAD_FEATURE__SUBSETTING;
        default: return -1;
      }
    }
    if (baseClass == ReferenceFeatureChain.class)
    {
      switch (baseFeatureID)
      {
        case SysMLOCPackage.REFERENCE_FEATURE_CHAIN__REFERENCES: return SysMLOCPackage.PAYLOAD_FEATURE__REFERENCES;
        default: return -1;
      }
    }
    if (baseClass == CrossFeatureChain.class)
    {
      switch (baseFeatureID)
      {
        case SysMLOCPackage.CROSS_FEATURE_CHAIN__CROSSES: return SysMLOCPackage.PAYLOAD_FEATURE__CROSSES;
        default: return -1;
      }
    }
    if (baseClass == RedefinitionFeatureChain.class)
    {
      switch (baseFeatureID)
      {
        case SysMLOCPackage.REDEFINITION_FEATURE_CHAIN__REDEFINITIONS: return SysMLOCPackage.PAYLOAD_FEATURE__REDEFINITIONS;
        default: return -1;
      }
    }
    if (baseClass == FeatureSpecialization.class)
    {
      switch (baseFeatureID)
      {
        default: return -1;
      }
    }
    if (baseClass == MultiplicityRange.class)
    {
      switch (baseFeatureID)
      {
        case SysMLOCPackage.MULTIPLICITY_RANGE__MULTI_VALUE: return SysMLOCPackage.PAYLOAD_FEATURE__MULTI_VALUE;
        case SysMLOCPackage.MULTIPLICITY_RANGE__MULTI_LOW: return SysMLOCPackage.PAYLOAD_FEATURE__MULTI_LOW;
        case SysMLOCPackage.MULTIPLICITY_RANGE__MULTI_HIGH: return SysMLOCPackage.PAYLOAD_FEATURE__MULTI_HIGH;
        default: return -1;
      }
    }
    if (baseClass == MultiplicityModifiers.class)
    {
      switch (baseFeatureID)
      {
        case SysMLOCPackage.MULTIPLICITY_MODIFIERS__IS_ORDERED: return SysMLOCPackage.PAYLOAD_FEATURE__IS_ORDERED;
        case SysMLOCPackage.MULTIPLICITY_MODIFIERS__IS_NONUNIQUE: return SysMLOCPackage.PAYLOAD_FEATURE__IS_NONUNIQUE;
        default: return -1;
      }
    }
    if (baseClass == MultiplicityPart.class)
    {
      switch (baseFeatureID)
      {
        default: return -1;
      }
    }
    if (baseClass == PayloadFeatureSpecializationPart.class)
    {
      switch (baseFeatureID)
      {
        default: return -1;
      }
    }
    if (baseClass == FeatureValue.class)
    {
      switch (baseFeatureID)
      {
        case SysMLOCPackage.FEATURE_VALUE__IS_INITIAL: return SysMLOCPackage.PAYLOAD_FEATURE__IS_INITIAL;
        case SysMLOCPackage.FEATURE_VALUE__IS_DEFAULT: return SysMLOCPackage.PAYLOAD_FEATURE__IS_DEFAULT;
        case SysMLOCPackage.FEATURE_VALUE__VALUE_PART: return SysMLOCPackage.PAYLOAD_FEATURE__VALUE_PART;
        default: return -1;
      }
    }
    if (baseClass == ValuePart.class)
    {
      switch (baseFeatureID)
      {
        default: return -1;
      }
    }
    return super.eDerivedStructuralFeatureID(baseFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (typings: ");
    result.append(typings);
    result.append(", subsetting: ");
    result.append(subsetting);
    result.append(", references: ");
    result.append(references);
    result.append(", crosses: ");
    result.append(crosses);
    result.append(", redefinitions: ");
    result.append(redefinitions);
    result.append(", MultiValue: ");
    result.append(multiValue);
    result.append(", MultiLow: ");
    result.append(multiLow);
    result.append(", MultiHigh: ");
    result.append(multiHigh);
    result.append(", isOrdered: ");
    result.append(isOrdered);
    result.append(", isNonunique: ");
    result.append(isNonunique);
    result.append(", isInitial: ");
    result.append(isInitial);
    result.append(", isDefault: ");
    result.append(isDefault);
    result.append(", valuePart: ");
    result.append(valuePart);
    result.append(", payloadFeatureElement: ");
    result.append(payloadFeatureElement);
    result.append(')');
    return result.toString();
  }

} //PayloadFeatureImpl
