/**
 * generated by Xtext 2.38.0
 */
package dut.control.sysmloc.sysMLOC.impl;

import dut.control.sysmloc.sysMLOC.PerformedActionParameterPart;
import dut.control.sysmloc.sysMLOC.PerformedActionUsage;
import dut.control.sysmloc.sysMLOC.SysMLOCPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Performed Action Parameter Part</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link dut.control.sysmloc.sysMLOC.impl.PerformedActionParameterPartImpl#getPerformedActionParameterPart <em>Performed Action Parameter Part</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PerformedActionParameterPartImpl extends MinimalEObjectImpl.Container implements PerformedActionParameterPart
{
  /**
   * The cached value of the '{@link #getPerformedActionParameterPart() <em>Performed Action Parameter Part</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPerformedActionParameterPart()
   * @generated
   * @ordered
   */
  protected EList<PerformedActionUsage> performedActionParameterPart;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PerformedActionParameterPartImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SysMLOCPackage.eINSTANCE.getPerformedActionParameterPart();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<PerformedActionUsage> getPerformedActionParameterPart()
  {
    if (performedActionParameterPart == null)
    {
      performedActionParameterPart = new EObjectContainmentEList<PerformedActionUsage>(PerformedActionUsage.class, this, SysMLOCPackage.PERFORMED_ACTION_PARAMETER_PART__PERFORMED_ACTION_PARAMETER_PART);
    }
    return performedActionParameterPart;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SysMLOCPackage.PERFORMED_ACTION_PARAMETER_PART__PERFORMED_ACTION_PARAMETER_PART:
        return ((InternalEList<?>)getPerformedActionParameterPart()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SysMLOCPackage.PERFORMED_ACTION_PARAMETER_PART__PERFORMED_ACTION_PARAMETER_PART:
        return getPerformedActionParameterPart();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SysMLOCPackage.PERFORMED_ACTION_PARAMETER_PART__PERFORMED_ACTION_PARAMETER_PART:
        getPerformedActionParameterPart().clear();
        getPerformedActionParameterPart().addAll((Collection<? extends PerformedActionUsage>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SysMLOCPackage.PERFORMED_ACTION_PARAMETER_PART__PERFORMED_ACTION_PARAMETER_PART:
        getPerformedActionParameterPart().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SysMLOCPackage.PERFORMED_ACTION_PARAMETER_PART__PERFORMED_ACTION_PARAMETER_PART:
        return performedActionParameterPart != null && !performedActionParameterPart.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //PerformedActionParameterPartImpl
