/**
 * generated by Xtext 2.38.0
 */
package dut.control.sysmloc.sysMLOC.impl;

import dut.control.sysmloc.sysMLOC.StructureUsageElements;
import dut.control.sysmloc.sysMLOC.SysMLOCPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Structure Usage Elements</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class StructureUsageElementsImpl extends OccurrenceUsageElementImpl implements StructureUsageElements
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StructureUsageElementsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SysMLOCPackage.eINSTANCE.getStructureUsageElements();
  }

} //StructureUsageElementsImpl
