/**
 * generated by Xtext 2.38.0
 */
package dut.control.sysmloc.sysMLOC.impl;

import dut.control.sysmloc.sysMLOC.SysMLOCPackage;
import dut.control.sysmloc.sysMLOC.WhileLoopNode;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>While Loop Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class WhileLoopNodeImpl extends MemberPrefixImpl implements WhileLoopNode
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected WhileLoopNodeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SysMLOCPackage.eINSTANCE.getWhileLoopNode();
  }

} //WhileLoopNodeImpl
