/**
 * generated by Xtext 2.38.0
 */
package dut.control.moloc.mOloc;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>constraining</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dut.control.moloc.mOloc.constraining#isIsConstrainedby <em>Is Constrainedby</em>}</li>
 *   <li>{@link dut.control.moloc.mOloc.constraining#getConstrain <em>Constrain</em>}</li>
 * </ul>
 *
 * @see dut.control.moloc.mOloc.MOlocPackage#getconstraining()
 * @model
 * @generated
 */
public interface constraining extends EObject
{
  /**
   * Returns the value of the '<em><b>Is Constrainedby</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Constrainedby</em>' attribute.
   * @see #setIsConstrainedby(boolean)
   * @see dut.control.moloc.mOloc.MOlocPackage#getconstraining_IsConstrainedby()
   * @model
   * @generated
   */
  boolean isIsConstrainedby();

  /**
   * Sets the value of the '{@link dut.control.moloc.mOloc.constraining#isIsConstrainedby <em>Is Constrainedby</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Constrainedby</em>' attribute.
   * @see #isIsConstrainedby()
   * @generated
   */
  void setIsConstrainedby(boolean value);

  /**
   * Returns the value of the '<em><b>Constrain</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constrain</em>' containment reference.
   * @see #setConstrain(ConstrainingClause)
   * @see dut.control.moloc.mOloc.MOlocPackage#getconstraining_Constrain()
   * @model containment="true"
   * @generated
   */
  ConstrainingClause getConstrain();

  /**
   * Sets the value of the '{@link dut.control.moloc.mOloc.constraining#getConstrain <em>Constrain</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constrain</em>' containment reference.
   * @see #getConstrain()
   * @generated
   */
  void setConstrain(ConstrainingClause value);

} // constraining
