/**
 * generated by Xtext 2.38.0
 */
package dut.control.moloc.mOloc;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>description</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dut.control.moloc.mOloc.MOlocPackage#getdescription()
 * @model
 * @generated
 */
public interface description extends description_string, class_modification
{
} // description
