/**
 * generated by Xtext 2.38.0
 */
package dut.control.moloc.mOloc;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Equation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dut.control.moloc.mOloc.MOlocPackage#getEquation()
 * @model
 * @generated
 */
public interface Equation extends EObject
{
} // Equation
