/**
 * generated by Xtext 2.38.0
 */
package dut.control.moloc.mOloc;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>If Equation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dut.control.moloc.mOloc.IfEquation#getCondition <em>Condition</em>}</li>
 *   <li>{@link dut.control.moloc.mOloc.IfEquation#getIfEquations <em>If Equations</em>}</li>
 *   <li>{@link dut.control.moloc.mOloc.IfEquation#getElseCondition <em>Else Condition</em>}</li>
 *   <li>{@link dut.control.moloc.mOloc.IfEquation#getElseifEquations <em>Elseif Equations</em>}</li>
 *   <li>{@link dut.control.moloc.mOloc.IfEquation#getElseEquations <em>Else Equations</em>}</li>
 * </ul>
 *
 * @see dut.control.moloc.mOloc.MOlocPackage#getIfEquation()
 * @model
 * @generated
 */
public interface IfEquation extends Equation, description, description_string, annotation_modification_part
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' attribute.
   * @see #setCondition(String)
   * @see dut.control.moloc.mOloc.MOlocPackage#getIfEquation_Condition()
   * @model
   * @generated
   */
  String getCondition();

  /**
   * Sets the value of the '{@link dut.control.moloc.mOloc.IfEquation#getCondition <em>Condition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' attribute.
   * @see #getCondition()
   * @generated
   */
  void setCondition(String value);

  /**
   * Returns the value of the '<em><b>If Equations</b></em>' containment reference list.
   * The list contents are of type {@link dut.control.moloc.mOloc.Equation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>If Equations</em>' containment reference list.
   * @see dut.control.moloc.mOloc.MOlocPackage#getIfEquation_IfEquations()
   * @model containment="true"
   * @generated
   */
  EList<Equation> getIfEquations();

  /**
   * Returns the value of the '<em><b>Else Condition</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Else Condition</em>' attribute list.
   * @see dut.control.moloc.mOloc.MOlocPackage#getIfEquation_ElseCondition()
   * @model unique="false"
   * @generated
   */
  EList<String> getElseCondition();

  /**
   * Returns the value of the '<em><b>Elseif Equations</b></em>' containment reference list.
   * The list contents are of type {@link dut.control.moloc.mOloc.Equation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elseif Equations</em>' containment reference list.
   * @see dut.control.moloc.mOloc.MOlocPackage#getIfEquation_ElseifEquations()
   * @model containment="true"
   * @generated
   */
  EList<Equation> getElseifEquations();

  /**
   * Returns the value of the '<em><b>Else Equations</b></em>' containment reference list.
   * The list contents are of type {@link dut.control.moloc.mOloc.Equation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Else Equations</em>' containment reference list.
   * @see dut.control.moloc.mOloc.MOlocPackage#getIfEquation_ElseEquations()
   * @model containment="true"
   * @generated
   */
  EList<Equation> getElseEquations();

} // IfEquation
