/**
 * generated by Xtext 2.38.0
 */
package dut.control.moloc.mOloc;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>When Equation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dut.control.moloc.mOloc.WhenEquation#getWhen <em>When</em>}</li>
 *   <li>{@link dut.control.moloc.mOloc.WhenEquation#getWhen_eqs <em>When eqs</em>}</li>
 *   <li>{@link dut.control.moloc.mOloc.WhenEquation#getElsehwhen <em>Elsehwhen</em>}</li>
 *   <li>{@link dut.control.moloc.mOloc.WhenEquation#getElsewhen_eqs <em>Elsewhen eqs</em>}</li>
 * </ul>
 *
 * @see dut.control.moloc.mOloc.MOlocPackage#getWhenEquation()
 * @model
 * @generated
 */
public interface WhenEquation extends Equation
{
  /**
   * Returns the value of the '<em><b>When</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>When</em>' containment reference.
   * @see #setWhen(Expression)
   * @see dut.control.moloc.mOloc.MOlocPackage#getWhenEquation_When()
   * @model containment="true"
   * @generated
   */
  Expression getWhen();

  /**
   * Sets the value of the '{@link dut.control.moloc.mOloc.WhenEquation#getWhen <em>When</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>When</em>' containment reference.
   * @see #getWhen()
   * @generated
   */
  void setWhen(Expression value);

  /**
   * Returns the value of the '<em><b>When eqs</b></em>' containment reference list.
   * The list contents are of type {@link dut.control.moloc.mOloc.Equation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>When eqs</em>' containment reference list.
   * @see dut.control.moloc.mOloc.MOlocPackage#getWhenEquation_When_eqs()
   * @model containment="true"
   * @generated
   */
  EList<Equation> getWhen_eqs();

  /**
   * Returns the value of the '<em><b>Elsehwhen</b></em>' containment reference list.
   * The list contents are of type {@link dut.control.moloc.mOloc.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elsehwhen</em>' containment reference list.
   * @see dut.control.moloc.mOloc.MOlocPackage#getWhenEquation_Elsehwhen()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getElsehwhen();

  /**
   * Returns the value of the '<em><b>Elsewhen eqs</b></em>' containment reference list.
   * The list contents are of type {@link dut.control.moloc.mOloc.Equation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elsewhen eqs</em>' containment reference list.
   * @see dut.control.moloc.mOloc.MOlocPackage#getWhenEquation_Elsewhen_eqs()
   * @model containment="true"
   * @generated
   */
  EList<Equation> getElsewhen_eqs();

} // WhenEquation
