/**
 * generated by Xtext 2.38.0
 */
package dut.control.moloc.mOloc;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>While Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dut.control.moloc.mOloc.WhileStatement#getCondition <em>Condition</em>}</li>
 *   <li>{@link dut.control.moloc.mOloc.WhileStatement#getStatements <em>Statements</em>}</li>
 * </ul>
 *
 * @see dut.control.moloc.mOloc.MOlocPackage#getWhileStatement()
 * @model
 * @generated
 */
public interface WhileStatement extends Statement, description
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' attribute.
   * @see #setCondition(String)
   * @see dut.control.moloc.mOloc.MOlocPackage#getWhileStatement_Condition()
   * @model
   * @generated
   */
  String getCondition();

  /**
   * Sets the value of the '{@link dut.control.moloc.mOloc.WhileStatement#getCondition <em>Condition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' attribute.
   * @see #getCondition()
   * @generated
   */
  void setCondition(String value);

  /**
   * Returns the value of the '<em><b>Statements</b></em>' containment reference list.
   * The list contents are of type {@link dut.control.moloc.mOloc.Statement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statements</em>' containment reference list.
   * @see dut.control.moloc.mOloc.MOlocPackage#getWhileStatement_Statements()
   * @model containment="true"
   * @generated
   */
  EList<Statement> getStatements();

} // WhileStatement
