/**
 * generated by Xtext 2.38.0
 */
package dut.control.sysmloc.sysMLOC.util;

import dut.control.sysmloc.sysMLOC.ActionUsage;
import dut.control.sysmloc.sysMLOC.AnnotatingElement;
import dut.control.sysmloc.sysMLOC.AttributeDefinition;
import dut.control.sysmloc.sysMLOC.AttributeUsage;
import dut.control.sysmloc.sysMLOC.BaseElement;
import dut.control.sysmloc.sysMLOC.BehaviorUsageElement;
import dut.control.sysmloc.sysMLOC.Comment;
import dut.control.sysmloc.sysMLOC.DefinitionElement;
import dut.control.sysmloc.sysMLOC.FeatureDeclaration;
import dut.control.sysmloc.sysMLOC.FeatureSpecialization;
import dut.control.sysmloc.sysMLOC.FeatureSpecializationPart;
import dut.control.sysmloc.sysMLOC.FeatureValue;
import dut.control.sysmloc.sysMLOC.ImportElement;
import dut.control.sysmloc.sysMLOC.MultiplicityPart;
import dut.control.sysmloc.sysMLOC.Namespace;
import dut.control.sysmloc.sysMLOC.NamespaceImport;
import dut.control.sysmloc.sysMLOC.NonOccurrenceUsageElement;
import dut.control.sysmloc.sysMLOC.OccurrenceUsageElement;
import dut.control.sysmloc.sysMLOC.PartDefinition;
import dut.control.sysmloc.sysMLOC.PartUsage;
import dut.control.sysmloc.sysMLOC.StructureUsageElement;
import dut.control.sysmloc.sysMLOC.SysMLOCPackage;
import dut.control.sysmloc.sysMLOC.Usage;
import dut.control.sysmloc.sysMLOC.UsageElement;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.util.Switch;

/**
 * <!-- begin-user-doc -->
 * The <b>Switch</b> for the model's inheritance hierarchy.
 * It supports the call {@link #doSwitch(EObject) doSwitch(object)}
 * to invoke the <code>caseXXX</code> method for each class of the model,
 * starting with the actual class of the object
 * and proceeding up the inheritance hierarchy
 * until a non-null result is returned,
 * which is the result of the switch.
 * <!-- end-user-doc -->
 * @see dut.control.sysmloc.sysMLOC.SysMLOCPackage
 * @generated
 */
public class SysMLOCSwitch<T> extends Switch<T>
{
  /**
   * The cached model package
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static SysMLOCPackage modelPackage;

  /**
   * Creates an instance of the switch.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SysMLOCSwitch()
  {
    if (modelPackage == null)
    {
      modelPackage = SysMLOCPackage.eINSTANCE;
    }
  }

  /**
   * Checks whether this is a switch for the given package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param ePackage the package in question.
   * @return whether this is a switch for the given package.
   * @generated
   */
  @Override
  protected boolean isSwitchFor(EPackage ePackage)
  {
    return ePackage == modelPackage;
  }

  /**
   * Calls <code>caseXXX</code> for each class of the model until one returns a non null result; it yields that result.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the first non-null result returned by a <code>caseXXX</code> call.
   * @generated
   */
  @Override
  protected T doSwitch(int classifierID, EObject theEObject)
  {
    switch (classifierID)
    {
      case SysMLOCPackage.NAMESPACE:
      {
        Namespace namespace = (Namespace)theEObject;
        T result = caseNamespace(namespace);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case SysMLOCPackage.PACKAGE:
      {
        dut.control.sysmloc.sysMLOC.Package package_ = (dut.control.sysmloc.sysMLOC.Package)theEObject;
        T result = casePackage(package_);
        if (result == null) result = caseBaseElement(package_);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case SysMLOCPackage.BASE_ELEMENT:
      {
        BaseElement baseElement = (BaseElement)theEObject;
        T result = caseBaseElement(baseElement);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case SysMLOCPackage.ANNOTATING_ELEMENT:
      {
        AnnotatingElement annotatingElement = (AnnotatingElement)theEObject;
        T result = caseAnnotatingElement(annotatingElement);
        if (result == null) result = caseBaseElement(annotatingElement);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case SysMLOCPackage.IMPORT_ELEMENT:
      {
        ImportElement importElement = (ImportElement)theEObject;
        T result = caseImportElement(importElement);
        if (result == null) result = caseBaseElement(importElement);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case SysMLOCPackage.DEFINITION_ELEMENT:
      {
        DefinitionElement definitionElement = (DefinitionElement)theEObject;
        T result = caseDefinitionElement(definitionElement);
        if (result == null) result = caseBaseElement(definitionElement);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case SysMLOCPackage.USAGE_ELEMENT:
      {
        UsageElement usageElement = (UsageElement)theEObject;
        T result = caseUsageElement(usageElement);
        if (result == null) result = caseBaseElement(usageElement);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case SysMLOCPackage.NON_OCCURRENCE_USAGE_ELEMENT:
      {
        NonOccurrenceUsageElement nonOccurrenceUsageElement = (NonOccurrenceUsageElement)theEObject;
        T result = caseNonOccurrenceUsageElement(nonOccurrenceUsageElement);
        if (result == null) result = caseUsageElement(nonOccurrenceUsageElement);
        if (result == null) result = caseBaseElement(nonOccurrenceUsageElement);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case SysMLOCPackage.OCCURRENCE_USAGE_ELEMENT:
      {
        OccurrenceUsageElement occurrenceUsageElement = (OccurrenceUsageElement)theEObject;
        T result = caseOccurrenceUsageElement(occurrenceUsageElement);
        if (result == null) result = caseUsageElement(occurrenceUsageElement);
        if (result == null) result = caseBaseElement(occurrenceUsageElement);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case SysMLOCPackage.STRUCTURE_USAGE_ELEMENT:
      {
        StructureUsageElement structureUsageElement = (StructureUsageElement)theEObject;
        T result = caseStructureUsageElement(structureUsageElement);
        if (result == null) result = caseOccurrenceUsageElement(structureUsageElement);
        if (result == null) result = caseUsageElement(structureUsageElement);
        if (result == null) result = caseBaseElement(structureUsageElement);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case SysMLOCPackage.BEHAVIOR_USAGE_ELEMENT:
      {
        BehaviorUsageElement behaviorUsageElement = (BehaviorUsageElement)theEObject;
        T result = caseBehaviorUsageElement(behaviorUsageElement);
        if (result == null) result = caseOccurrenceUsageElement(behaviorUsageElement);
        if (result == null) result = caseUsageElement(behaviorUsageElement);
        if (result == null) result = caseBaseElement(behaviorUsageElement);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case SysMLOCPackage.NAMESPACE_IMPORT:
      {
        NamespaceImport namespaceImport = (NamespaceImport)theEObject;
        T result = caseNamespaceImport(namespaceImport);
        if (result == null) result = caseImportElement(namespaceImport);
        if (result == null) result = caseBaseElement(namespaceImport);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case SysMLOCPackage.COMMENT:
      {
        Comment comment = (Comment)theEObject;
        T result = caseComment(comment);
        if (result == null) result = caseAnnotatingElement(comment);
        if (result == null) result = caseBaseElement(comment);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case SysMLOCPackage.ATTRIBUTE_DEFINITION:
      {
        AttributeDefinition attributeDefinition = (AttributeDefinition)theEObject;
        T result = caseAttributeDefinition(attributeDefinition);
        if (result == null) result = caseDefinitionElement(attributeDefinition);
        if (result == null) result = caseBaseElement(attributeDefinition);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case SysMLOCPackage.PART_DEFINITION:
      {
        PartDefinition partDefinition = (PartDefinition)theEObject;
        T result = casePartDefinition(partDefinition);
        if (result == null) result = caseDefinitionElement(partDefinition);
        if (result == null) result = caseBaseElement(partDefinition);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case SysMLOCPackage.ATTRIBUTE_USAGE:
      {
        AttributeUsage attributeUsage = (AttributeUsage)theEObject;
        T result = caseAttributeUsage(attributeUsage);
        if (result == null) result = caseNonOccurrenceUsageElement(attributeUsage);
        if (result == null) result = caseUsageElement(attributeUsage);
        if (result == null) result = caseBaseElement(attributeUsage);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case SysMLOCPackage.ACTION_USAGE:
      {
        ActionUsage actionUsage = (ActionUsage)theEObject;
        T result = caseActionUsage(actionUsage);
        if (result == null) result = caseBehaviorUsageElement(actionUsage);
        if (result == null) result = caseOccurrenceUsageElement(actionUsage);
        if (result == null) result = caseUsageElement(actionUsage);
        if (result == null) result = caseBaseElement(actionUsage);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case SysMLOCPackage.PART_USAGE:
      {
        PartUsage partUsage = (PartUsage)theEObject;
        T result = casePartUsage(partUsage);
        if (result == null) result = caseStructureUsageElement(partUsage);
        if (result == null) result = caseUsage(partUsage);
        if (result == null) result = caseOccurrenceUsageElement(partUsage);
        if (result == null) result = caseFeatureDeclaration(partUsage);
        if (result == null) result = caseFeatureValue(partUsage);
        if (result == null) result = caseUsageElement(partUsage);
        if (result == null) result = caseFeatureSpecializationPart(partUsage);
        if (result == null) result = caseBaseElement(partUsage);
        if (result == null) result = caseFeatureSpecialization(partUsage);
        if (result == null) result = caseMultiplicityPart(partUsage);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case SysMLOCPackage.USAGE:
      {
        Usage usage = (Usage)theEObject;
        T result = caseUsage(usage);
        if (result == null) result = caseFeatureDeclaration(usage);
        if (result == null) result = caseFeatureValue(usage);
        if (result == null) result = caseFeatureSpecializationPart(usage);
        if (result == null) result = caseFeatureSpecialization(usage);
        if (result == null) result = caseMultiplicityPart(usage);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case SysMLOCPackage.FEATURE_VALUE:
      {
        FeatureValue featureValue = (FeatureValue)theEObject;
        T result = caseFeatureValue(featureValue);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case SysMLOCPackage.FEATURE_DECLARATION:
      {
        FeatureDeclaration featureDeclaration = (FeatureDeclaration)theEObject;
        T result = caseFeatureDeclaration(featureDeclaration);
        if (result == null) result = caseFeatureSpecializationPart(featureDeclaration);
        if (result == null) result = caseFeatureSpecialization(featureDeclaration);
        if (result == null) result = caseMultiplicityPart(featureDeclaration);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case SysMLOCPackage.FEATURE_SPECIALIZATION_PART:
      {
        FeatureSpecializationPart featureSpecializationPart = (FeatureSpecializationPart)theEObject;
        T result = caseFeatureSpecializationPart(featureSpecializationPart);
        if (result == null) result = caseFeatureSpecialization(featureSpecializationPart);
        if (result == null) result = caseMultiplicityPart(featureSpecializationPart);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case SysMLOCPackage.MULTIPLICITY_PART:
      {
        MultiplicityPart multiplicityPart = (MultiplicityPart)theEObject;
        T result = caseMultiplicityPart(multiplicityPart);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case SysMLOCPackage.FEATURE_SPECIALIZATION:
      {
        FeatureSpecialization featureSpecialization = (FeatureSpecialization)theEObject;
        T result = caseFeatureSpecialization(featureSpecialization);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      default: return defaultCase(theEObject);
    }
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Namespace</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Namespace</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseNamespace(Namespace object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Package</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Package</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePackage(dut.control.sysmloc.sysMLOC.Package object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Base Element</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Base Element</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBaseElement(BaseElement object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Annotating Element</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Annotating Element</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAnnotatingElement(AnnotatingElement object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Import Element</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Import Element</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseImportElement(ImportElement object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Definition Element</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Definition Element</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDefinitionElement(DefinitionElement object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Usage Element</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Usage Element</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseUsageElement(UsageElement object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Non Occurrence Usage Element</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Non Occurrence Usage Element</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseNonOccurrenceUsageElement(NonOccurrenceUsageElement object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Occurrence Usage Element</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Occurrence Usage Element</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseOccurrenceUsageElement(OccurrenceUsageElement object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Structure Usage Element</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Structure Usage Element</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseStructureUsageElement(StructureUsageElement object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Behavior Usage Element</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Behavior Usage Element</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBehaviorUsageElement(BehaviorUsageElement object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Namespace Import</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Namespace Import</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseNamespaceImport(NamespaceImport object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Comment</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Comment</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseComment(Comment object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Attribute Definition</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Attribute Definition</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAttributeDefinition(AttributeDefinition object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Part Definition</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Part Definition</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePartDefinition(PartDefinition object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Attribute Usage</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Attribute Usage</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAttributeUsage(AttributeUsage object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Action Usage</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Action Usage</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseActionUsage(ActionUsage object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Part Usage</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Part Usage</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePartUsage(PartUsage object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Usage</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Usage</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseUsage(Usage object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Feature Value</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Feature Value</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseFeatureValue(FeatureValue object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Feature Declaration</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Feature Declaration</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseFeatureDeclaration(FeatureDeclaration object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Feature Specialization Part</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Feature Specialization Part</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseFeatureSpecializationPart(FeatureSpecializationPart object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Multiplicity Part</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Multiplicity Part</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMultiplicityPart(MultiplicityPart object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Feature Specialization</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Feature Specialization</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseFeatureSpecialization(FeatureSpecialization object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EObject</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch, but this is the last case anyway.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EObject</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject)
   * @generated
   */
  @Override
  public T defaultCase(EObject object)
  {
    return null;
  }

} //SysMLOCSwitch
