//grammar dut.control.kermloc.KerMLOC with org.eclipse.xtext.common.Terminals
grammar dut.control.kermloc.KerMLOC hidden(WS, ML_NOTE)

import "http://www.eclipse.org/emf/2002/Ecore" as Ecore

generate kerMLOC "http://www.control.dut/kermloc/KerMLOC"

RootNamespace:
	(elements+=GeneralBodyElements)*
;

// TODO --------------------------------- Body Level ---------------------------------//

GeneralBodyElements:
	AnnotatingElement
    | ImportElement
    | AliasElement
    | CodeAnnotation
    | NonFeatureElement
//    | FeatureElement
;

AnnotatingBodyElement:
	AnnotatingElement
	| CodeAnnotation
;

PackageBodyElement:
    GeneralBodyElements
  	| ElementFilterElement
;

TypeBodyElement:
	GeneralBodyElements
;

NamespaceBodyElement:
	GeneralBodyElements
;

FunctionBodyElement:
	GeneralBodyElements
//	| ReturnFeatureElement
;

// TODO --------------------------------- Abstract Level ---------------------------------//

AnnotatingElement:
	Comment
	| Documentation
	| TextualRepresentation
//	| MetadataFeature
;

NonFeatureElement:
	Dependency
	| Namespace
	| Package
	| LibraryPackage 
	| Multiplicity
	| Type
	| Classifier 
	| Class
	| Structure
	| Metaclass
	| DataType 
	| Association
	| AssociationStructure
	| Interaction
	| Behavior
	| Function
	| Predicate
//	| Specialization
//	| Conjugation
//	| FeatureTyping
//	| Subclassification
//	| Disjoining
//	| FeatureInverting
//	| Subsetting
//	| Redefinition
//	| TypeFeaturing
;

//FeatureElement:
//	Feature
//	| Step
//	| Expression
//	| BooleanExpression
//	| Invariant
//	| Connector
//	| BindingConnector
//	| Succession
//	| Flow
//	| SuccessionFlow
//;

// TODO --------------------------------- Instance Level ---------------------------------//

Package:
	MemberPrefix
    PrefixMetadata*
    'package' 
    declaredName=QualifiedName 
    ( ';' | '{' (elements+=PackageBodyElement)* '}')
;

LibraryPackage:
	MemberPrefix
	( isStandard ?= 'standard' )? 
	isLibrary ?= 'library'
	PrefixMetadata*
	'package'
	Identification?
	( ';' | '{' (elements+=PackageBodyElement)* '}')
;

Dependency:
	MemberPrefix
	PrefixMetadata*
	'dependency'
	( Identification? 'from' )?
	client+=QualifiedName ( ',' client+=QualifiedName )*
	'to'
	supplier+=QualifiedName ( ',' supplier+=QualifiedName )*
	(';' | '{' ( elements+=AnnotatingElement )* '}')
;

Comment:
	MemberPrefix
	( 'comment' Identification? 
	  ('about' annotatedElement += QualifiedName
	     ( ',' annotatedElement += QualifiedName )* )? 
	)?
    ( 'locale' locale = STRING_VALUE )?
    body=REGULAR_COMMENT
;

Documentation:
	MemberPrefix
    'doc' Identification? 
    ( 'locale' locale = STRING_VALUE )?
    body=REGULAR_COMMENT
;

TextualRepresentation:
	MemberPrefix
    ( 'rep' Identification? )?
    'language' language = STRING_VALUE 
    body = REGULAR_COMMENT
;

ImportElement:
	visibility=VisibilityIndicator 
    'import' (isImportAll?='all')? 
    declaredName=QualifiedName (isNamespace?='::' '*')? ( '::' isRecursive ?= '**' )? 
    ( '[' filterPackageExpression+=Expression ']')*
	//	 declaredName=QualifiedName (isNamespace?='::' )? ( '*' | isRecursive ?= '**' )?  
    (';' | '{' ( elements+=AnnotatingBodyElement )* '}')
;

CodeAnnotation:
    body=SL_NOTE | body=ML_NOTE
;

AliasElement:
	MemberPrefix 
	'alias' 
	( '<' memberShortName = Name '>' )? ( memberName = Name )? 
	'for' memberElement = QualifiedName
	(';' | '{' (elements+=AnnotatingBodyElement)* '}')
;

ElementFilterElement:
	MemberPrefix
	'filter'
	filterExpression=Expression
	';'
;

Multiplicity:
	MemberPrefix
	'multiplicity' 
	Identification?
	(Subsets | MultiplicityBounds)
	( ';' | '{' (elements+=TypeBodyElement)* '}')
;

Namespace:
	PrefixMetadata*
	isNamespace?='namespace' 
	Identification?
	( ';' | '{' (elements+=NamespaceBodyElement)* '}')
;

Type:
	MemberPrefix
	TypePrefix
	'type'
	( isSufficient ?= 'all' )?
	Identification?
	MultiplicityBounds?
	( SpecializationPart | ConjugationPart )
	TypeRelationshipPart*
	( ';' | '{' (elements+=TypeBodyElement)* '}')
;

Classifier:
	MemberPrefix
	TypePrefix
	'classifier'
	ClassifierDeclaration
	( ';' | '{' (elements+=TypeBodyElement)* '}')
;

Class:
	MemberPrefix
	TypePrefix 
	'class' 
	ClassifierDeclaration
	( ';' | '{' (elements+=TypeBodyElement)* '}')
;

Structure:
	MemberPrefix
	TypePrefix
	'struct'
	ClassifierDeclaration
	( ';' | '{' (elements+=TypeBodyElement)* '}')
;

Metaclass:
	MemberPrefix
	TypePrefix
	'metaclass' 
	ClassifierDeclaration
	( ';' | '{' (elements+=TypeBodyElement)* '}')
;

DataType:
	MemberPrefix
	TypePrefix
	'datatype' 
	ClassifierDeclaration
	( ';' | '{' (elements+=TypeBodyElement)* '}')
;

Association:
	MemberPrefix
	TypePrefix
	'assoc' 
	ClassifierDeclaration
	( ';' | '{' (elements+=TypeBodyElement)* '}')
;

AssociationStructure:
	MemberPrefix
	TypePrefix
	'assoc' 'struct' 
	ClassifierDeclaration
	( ';' | '{' (elements+=TypeBodyElement)* '}')
;

Interaction:
	MemberPrefix
	TypePrefix
	'interaction'
	ClassifierDeclaration
	( ';' | '{' (elements+=TypeBodyElement)* '}')
;

Behavior:
	MemberPrefix
	TypePrefix
	'behavior'
	ClassifierDeclaration
	( ';' | '{' (elements+=TypeBodyElement)* '}')
;

Function:
	MemberPrefix
	TypePrefix
	'function'
	ClassifierDeclaration
	( ';' | '{' (elements+=FunctionBodyElement)* (resultExpressionParameter+=ResultExpression)? '}')
;

Predicate:
	MemberPrefix
	TypePrefix
	'predicate'
	ClassifierDeclaration
	( ';' | '{' (elements+=FunctionBodyElement)* (resultExpressionParameter+=ResultExpression)? '}')	
;

// TODO --------------------------------- Secondary Instance Level ---------------------------------//
ResultExpression:
	MemberPrefix resultExpression=Expression
;

// TODO --------------------------------- Fragment Level ---------------------------------//
fragment Identification:
	'<' declaredShortName = Name '>' ( declaredName = Name )?
	| declaredName = Name
;

fragment MemberPrefix:
	( visibility = VisibilityIndicator )?
	( isVariant ?= 'variant')?
;

fragment PrefixMetadata:
	//	'#' prefixMetadataExtension += QualifiedName
	//	prefixMetadataExtension += PrefixMetadataName
	prefixMetadataExtension += PREFIXNAME_TEXT
;

fragment MultiplicityBounds:
	//	'[' Multiplicity += MultiplicityExpression ']' | '[' Multiplicity += MultiplicityExpression '..' Multiplicity += MultiplicityExpression ']'
	'[' MultiLow = MultiplicityExpression ( '..' MultiHigh = MultiplicityExpression )? ']'
;

fragment FeatureSpecialization:
	(':'|'defined' 'by') TypingFeatureTyping
	| (':>'|'specializes'|'subsets') SubsettingFeatureChain
	| ('::>'|'references')  ReferenceFeatureChain
	| ('=>'|'crosses') CrossFeatureChain
	| (':>>'|'redefines') RedefinitionFeatureChain
;

fragment TypingFeatureTyping:
	typings+=FeatureTypingName (',' typings+=FeatureTypingName)*
;

fragment SubsettingFeatureChain:
	subsetting+=FeatureChainName (',' subsetting+=FeatureChainName)*
;

fragment ReferenceFeatureChain:
	references+=FeatureChainName (',' references+=FeatureChainName)*
;

fragment CrossFeatureChain:
	crosses+=FeatureChainName (',' crosses+=FeatureChainName)*
;

fragment RedefinitionFeatureChain:
	redefinitions+=FeatureChainName (',' redefinitions+=FeatureChainName)*
;

fragment Subsets:
	(':>'| 'subsets') SubsettingFeatureChain
;

fragment TypePrefix:
	( isAbstract ?= 'abstract' )? 
	PrefixMetadata*
;

fragment SpecializationPart:
	 ( ':>' | 'specializes' ) 
	 SubsettingFeatureChain
;

fragment SuperclassingPart:
	( ':>' | 'specializes' ) 
	SubsettingFeatureChain
;

fragment ClassifierConjugationPart:
	( '~' | 'conjugates' ) 
	originalType=FeatureChainName
;

fragment ConjugationPart:
	( '~' | 'conjugates' ) 
	originalType=FeatureChainName
;

fragment TypeRelationshipPart:
	DisjoiningPart | UnioningPart | IntersectingPart | DifferencingPart
;

fragment DisjoiningPart:
	'disjoint' 'from' disjoining += FeatureChainName 
	( ',' disjoining += FeatureChainName )* 
;

fragment UnioningPart:
	'unions' unioning += FeatureChainName 
	( ',' unioning += FeatureChainName )* 
;

fragment IntersectingPart:
	'intersects' intersecting += FeatureChainName 
	( ',' intersecting += FeatureChainName )* 
;

fragment DifferencingPart :
	'differences' differencing += FeatureChainName 
	( ',' differencing += FeatureChainName )* 
;

fragment ClassifierDeclaration:
	(isSufficient ?= 'all' )?
	Identification?
	MultiplicityBounds?
	( SuperclassingPart | ClassifierConjugationPart )?
	TypeRelationshipPart*
;



// TODO --------------------------------- Enum Level ---------------------------------//

enum VisibilityIndicator:
	null='NULLVisibility' | public = 'public' | private = 'private' | protected = 'protected'
;

// TODO --------------------------------- String Level ---------------------------------//

/* NAMES */

Name:
	ID | UNRESTRICTED_NAME
;

Qualification :
	( Name '::' )+
;

QualifiedName:
	Qualification? Name
;

FeatureChainName:
	'USELESS'? 
	QualifiedName ('.' Name)*
;

FeatureTypingName:
	FeatureChainName | '~' QualifiedName
;

Expression:
	OwnedExpression 
;

OwnedExpression:
	ConditionalExpression
;

ConditionalExpression:
	NullCoalescingExpression
	| 'if' NullCoalescingExpression '?' OwnedExpression 'else' OwnedExpression
;

NullCoalescingExpression:
	ImpliesExpression ('??' ImpliesExpression)*
;

ImpliesExpression:
	OrExpression ('implies' OrExpression)*
;

OrExpression:
	XorExpression ('|' XorExpression | 'or' XorExpression)*
;

XorExpression:
	AndExpression ('xor' AndExpression)*
;

AndExpression:
	EqualityExpression ('&' EqualityExpression | 'and' EqualityExpression)*
;

EqualityExpression:
	ClassificationExpression (('==' | '!=' | '===' | '!==') ClassificationExpression)*
;

ClassificationExpression:
	RelationalExpression (('hastype' | 'istype' | '@') ReferenceTypingName | 'as' ReferenceTypingName)?
	| ('hastype' | 'istype' | '@') ReferenceTypingName
	| MetadataReferenceName '@@' ReferenceTypingName
	| 'as' ReferenceTypingName
	| MetadataReferenceName 'meta' ReferenceTypingName
;

ReferenceTypingName:
	QualifiedName
;

MetadataReferenceName:
	QualifiedName
;

RelationalExpression:
	RangeExpression (('<' | '>' | '<=' | '>=') RangeExpression)*
;

RangeExpression:
	AdditiveExpression ('..' AdditiveExpression)?
;

AdditiveExpression:
	MultiplicativeExpression (('+'|'-') MultiplicativeExpression)*
;

MultiplicativeExpression:
	ExponentiationExpression (('*' | '/' | '%') ExponentiationExpression)*
;

ExponentiationExpression:
	UnaryExpression (('**' | '^') UnaryExpression)?
;

UnaryExpression:
	('+' | '-' | '~' | 'not') ExtentExpression
	| ExtentExpression
;

ExtentExpression:
	'all' ReferenceTypingName
	| PrimaryExpression
;

PrimaryExpression:
	BaseExpression
	('.' FeatureChainName)?
	(	( '#' '(' SequenceExpression ')'
		| '[' SequenceExpression ']'
		| '->' ReferenceTypingName (BodyExpression | FunctionReferenceExpression | ArgumentList)
		| '.' BodyExpression
		| '.?' BodyExpression
		)
		('.' FeatureChainName)?	
	)*
;

TargetExpression:
	BaseExpression
	('.' FeatureChainName)?
	(	( '#' '(' SequenceExpression ')'
		| '[' SequenceExpression ']'
		| '->' ReferenceTypingName (BodyExpression | FunctionReferenceExpression | ArgumentList)
		| '.' BodyExpression
		| '.?' BodyExpression
		)
	)*
;

BaseExpression:
	NullExpression
	| LiteralExpression 
	| FeatureReferenceExpression 
	| MetadataAccessExpression
	| InvocationExpression 
	| BodyExpression
	| '(' SequenceExpression ')'
;

FunctionReferenceExpression:
	QualifiedName
;

ArgumentList:
	'(' ( PositionalArgumentList | NamedArgumentList )? ')'
;

PositionalArgumentList:
	ArgumentValue (',' ArgumentValue)*
;

NamedArgumentList:
	NamedArgument (',' NamedArgument)*
;

ArgumentValue:
	OwnedExpression
;

NamedArgument:
	QualifiedName '=' ArgumentValue
;

NullExpression:
	'null' 
	| '(' ')' 
;

MetadataAccessExpression:
	QualifiedName '.' 'metadata'
;

InvocationExpression:
	'new'? FeatureChainName ArgumentList
;

BodyExpression:
	'{' 
		('in' Name FeatureSpecializationName* ';')*
		// False Grammar (to avoid the usage of '( bodyExpressions += CalculationBodyElement)*')
		// In OMG's tools, BodyExpression was rewritten as a nested format, but in this tool it is treated as a string, which cannot meet all the needs. This time, the original syntax is retained.
		('in' 'ref' Name FeatureSpecializationName* ';')*
		('private' FeatureChainName ':' QualifiedName '=' OwnedExpression ';')*
		('private' 'attribute' FeatureChainName '=' OwnedExpression ';')?
		('private' 'attribute' FeatureChainName ':' QualifiedName '{' (':>>' FeatureChainName '=' OwnedExpression ';')* '}')?
		//
		OwnedExpression
	'}'
	//	( bodyExpressions += CalculationBodyElement)*
;

FeatureSpecializationName:
	(':'|'defined' 'by') FeatureTypingName (',' FeatureTypingName)*
	| (':>'|'specializes'|'subsets') FeatureChainName (',' FeatureChainName)*
	| ('::>'|'references') FeatureChainName (',' FeatureChainName)*
	| ('=>'|'crosses') FeatureChainName (',' FeatureChainName)*
	| (':>>'|'redefines') FeatureChainName (',' FeatureChainName)*
;

SequenceExpression:
	OwnedExpression (',' SequenceExpression)?
;

MultiplicityExpression:
	LiteralExpression | FeatureReferenceExpression
;

LiteralExpression:
	LiteralBoolean
	| LiteralString
	| LiteralInteger
	| LiteralReal
	| LiteralInfinity
;

LiteralBoolean:
	BooleanValue
;

BooleanValue:
	'true' | 'false'
;

LiteralString:
	STRING_VALUE
;

LiteralInteger:
	DECIMAL_VALUE
;

LiteralReal:
	RealValue
;

RealValue:
	DECIMAL_VALUE? '.' ( DECIMAL_VALUE | EXP_VALUE ) | EXP_VALUE
;

LiteralInfinity:
	'*'
;

FeatureReferenceExpression:
	QualifiedName
;

// TODO --------------------------------- Terminal Level ---------------------------------//

terminal PREFIXNAME_TEXT:
	'#' ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;

terminal DECIMAL_VALUE returns Ecore::EInt:
	'0'..'9' ('0'..'9')*;

terminal EXP_VALUE:
	DECIMAL_VALUE (('e' | 'E') ('+' | '-')? DECIMAL_VALUE)?;

terminal ID:
	('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;

terminal UNRESTRICTED_NAME returns Ecore::EString:
	'\'' ('\\' ('b' | 't' | 'n' | 'f' | 'r' | '"' | "'" | '\\') | !('\\' | '\''))* '\'';

terminal STRING_VALUE returns Ecore::EString:
	'"' ('\\' ('b' | 't' | 'n' | 'f' | 'r' | '"' | "'" | '\\') | !('\\' | '"'))* '"';

terminal REGULAR_COMMENT:
	'/*' -> '*/';

terminal ML_NOTE:
	'//*'-> '*/';

terminal SL_NOTE:
	'//' (!('\n' | '\r') !('\n' | '\r')*)? ('\r'? '\n')?;
	
terminal WS:
	(' ' | '\t' | '\r' | '\n')+;