/**
 * generated by Xtext 2.38.0
 */
package dut.control.kermloc.kerMLOC;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Namespace</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dut.control.kermloc.kerMLOC.Namespace#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see dut.control.kermloc.kerMLOC.KerMLOCPackage#getNamespace()
 * @model
 * @generated
 */
public interface Namespace extends EObject
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' attribute list.
   * @see dut.control.kermloc.kerMLOC.KerMLOCPackage#getNamespace_Elements()
   * @model unique="false"
   * @generated
   */
  EList<String> getElements();

} // Namespace
