/**
 * generated by Xtext 2.38.0
 */
package dut.control.kermloc.kerMLOC;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Step</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dut.control.kermloc.kerMLOC.Step#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see dut.control.kermloc.kerMLOC.KerMLOCPackage#getStep()
 * @model
 * @generated
 */
public interface Step extends FeatureElement, MemberPrefix, ExtendedPrefix, FeaturePrefix, EndFeaturePrefix, BasicFeaturePrefix, PrefixMetadata, FeatureDeclaration, Identification, FeatureSpecializationPart, FeatureSpecialization, TypingFeatureTyping, SubsettingFeatureChain, ReferenceFeatureChain, CrossFeatureChain, RedefinitionFeatureChain, MultiplicityPart, MultiplicityRange, MultiplicityModifiers, FeatureConjugationPart, FeatureRelationshipPart, TypeRelationshipPart, DisjoiningPart, UnioningPart, IntersectingPart, DifferencingPart, ChainingPart, InvertingPart, TypeFeaturingPart, ValuePart, FeatureValue
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link dut.control.kermloc.kerMLOC.TypeBodyElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see dut.control.kermloc.kerMLOC.KerMLOCPackage#getStep_Elements()
   * @model containment="true"
   * @generated
   */
  EList<TypeBodyElement> getElements();

} // Step
