/**
 * generated by Xtext 2.38.0
 */
package dut.control.kermloc.kerMLOC;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Featuring Part</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dut.control.kermloc.kerMLOC.TypeFeaturingPart#getFeaturingType <em>Featuring Type</em>}</li>
 * </ul>
 *
 * @see dut.control.kermloc.kerMLOC.KerMLOCPackage#getTypeFeaturingPart()
 * @model
 * @generated
 */
public interface TypeFeaturingPart extends EObject
{
  /**
   * Returns the value of the '<em><b>Featuring Type</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Featuring Type</em>' attribute list.
   * @see dut.control.kermloc.kerMLOC.KerMLOCPackage#getTypeFeaturingPart_FeaturingType()
   * @model unique="false"
   * @generated
   */
  EList<String> getFeaturingType();

} // TypeFeaturingPart
