/* Additional record code for BouncingBall_res generated by the OpenModelica Compiler OpenModelica v1.25.5 (64-bit). */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "BouncingBall_res_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

