/*
 * generated by Xtext 2.36.0
 */
package dut.control.sysmloc.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import dut.control.sysmloc.SysMLOCRuntimeModule;
import dut.control.sysmloc.SysMLOCStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SysMLOCIdeSetup extends SysMLOCStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SysMLOCRuntimeModule(), new SysMLOCIdeModule()));
	}
	
}
