/**
 * generated by Xtext 2.38.0
 */
package dut.control.moloc.mOloc.impl;

import dut.control.moloc.mOloc.AnnotationModificationElement;
import dut.control.moloc.mOloc.MOlocPackage;
import dut.control.moloc.mOloc.annotation_modification_part;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>annotation modification part</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link dut.control.moloc.mOloc.impl.annotation_modification_partImpl#isIsAnnotation <em>Is Annotation</em>}</li>
 *   <li>{@link dut.control.moloc.mOloc.impl.annotation_modification_partImpl#getAnnotations <em>Annotations</em>}</li>
 *   <li>{@link dut.control.moloc.mOloc.impl.annotation_modification_partImpl#isIsAnnotationOver <em>Is Annotation Over</em>}</li>
 * </ul>
 *
 * @generated
 */
public class annotation_modification_partImpl extends MinimalEObjectImpl.Container implements annotation_modification_part
{
  /**
   * The default value of the '{@link #isIsAnnotation() <em>Is Annotation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsAnnotation()
   * @generated
   * @ordered
   */
  protected static final boolean IS_ANNOTATION_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsAnnotation() <em>Is Annotation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsAnnotation()
   * @generated
   * @ordered
   */
  protected boolean isAnnotation = IS_ANNOTATION_EDEFAULT;

  /**
   * The cached value of the '{@link #getAnnotations() <em>Annotations</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAnnotations()
   * @generated
   * @ordered
   */
  protected EList<AnnotationModificationElement> annotations;

  /**
   * The default value of the '{@link #isIsAnnotationOver() <em>Is Annotation Over</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsAnnotationOver()
   * @generated
   * @ordered
   */
  protected static final boolean IS_ANNOTATION_OVER_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsAnnotationOver() <em>Is Annotation Over</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsAnnotationOver()
   * @generated
   * @ordered
   */
  protected boolean isAnnotationOver = IS_ANNOTATION_OVER_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected annotation_modification_partImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MOlocPackage.Literals.ANNOTATION_MODIFICATION_PART;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsAnnotation()
  {
    return isAnnotation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsAnnotation(boolean newIsAnnotation)
  {
    boolean oldIsAnnotation = isAnnotation;
    isAnnotation = newIsAnnotation;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MOlocPackage.ANNOTATION_MODIFICATION_PART__IS_ANNOTATION, oldIsAnnotation, isAnnotation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<AnnotationModificationElement> getAnnotations()
  {
    if (annotations == null)
    {
      annotations = new EObjectContainmentEList<AnnotationModificationElement>(AnnotationModificationElement.class, this, MOlocPackage.ANNOTATION_MODIFICATION_PART__ANNOTATIONS);
    }
    return annotations;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsAnnotationOver()
  {
    return isAnnotationOver;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsAnnotationOver(boolean newIsAnnotationOver)
  {
    boolean oldIsAnnotationOver = isAnnotationOver;
    isAnnotationOver = newIsAnnotationOver;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MOlocPackage.ANNOTATION_MODIFICATION_PART__IS_ANNOTATION_OVER, oldIsAnnotationOver, isAnnotationOver));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MOlocPackage.ANNOTATION_MODIFICATION_PART__ANNOTATIONS:
        return ((InternalEList<?>)getAnnotations()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MOlocPackage.ANNOTATION_MODIFICATION_PART__IS_ANNOTATION:
        return isIsAnnotation();
      case MOlocPackage.ANNOTATION_MODIFICATION_PART__ANNOTATIONS:
        return getAnnotations();
      case MOlocPackage.ANNOTATION_MODIFICATION_PART__IS_ANNOTATION_OVER:
        return isIsAnnotationOver();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MOlocPackage.ANNOTATION_MODIFICATION_PART__IS_ANNOTATION:
        setIsAnnotation((Boolean)newValue);
        return;
      case MOlocPackage.ANNOTATION_MODIFICATION_PART__ANNOTATIONS:
        getAnnotations().clear();
        getAnnotations().addAll((Collection<? extends AnnotationModificationElement>)newValue);
        return;
      case MOlocPackage.ANNOTATION_MODIFICATION_PART__IS_ANNOTATION_OVER:
        setIsAnnotationOver((Boolean)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MOlocPackage.ANNOTATION_MODIFICATION_PART__IS_ANNOTATION:
        setIsAnnotation(IS_ANNOTATION_EDEFAULT);
        return;
      case MOlocPackage.ANNOTATION_MODIFICATION_PART__ANNOTATIONS:
        getAnnotations().clear();
        return;
      case MOlocPackage.ANNOTATION_MODIFICATION_PART__IS_ANNOTATION_OVER:
        setIsAnnotationOver(IS_ANNOTATION_OVER_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MOlocPackage.ANNOTATION_MODIFICATION_PART__IS_ANNOTATION:
        return isAnnotation != IS_ANNOTATION_EDEFAULT;
      case MOlocPackage.ANNOTATION_MODIFICATION_PART__ANNOTATIONS:
        return annotations != null && !annotations.isEmpty();
      case MOlocPackage.ANNOTATION_MODIFICATION_PART__IS_ANNOTATION_OVER:
        return isAnnotationOver != IS_ANNOTATION_OVER_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (isAnnotation: ");
    result.append(isAnnotation);
    result.append(", isAnnotationOver: ");
    result.append(isAnnotationOver);
    result.append(')');
    return result.toString();
  }

} //annotation_modification_partImpl
