/**
 * generated by Xtext 2.38.0
 */
package dut.control.moloc.mOloc.impl;

import dut.control.moloc.mOloc.Argument;
import dut.control.moloc.mOloc.Break;
import dut.control.moloc.mOloc.ClassType;
import dut.control.moloc.mOloc.Class_definition;
import dut.control.moloc.mOloc.Component_declaration;
import dut.control.moloc.mOloc.Direction;
import dut.control.moloc.mOloc.Element;
import dut.control.moloc.mOloc.EnumerationLiteral;
import dut.control.moloc.mOloc.ExtendsClause;
import dut.control.moloc.mOloc.ExternalElement;
import dut.control.moloc.mOloc.GeneralClause;
import dut.control.moloc.mOloc.ImportClause;
import dut.control.moloc.mOloc.MOlocFactory;
import dut.control.moloc.mOloc.MOlocPackage;
import dut.control.moloc.mOloc.NULLElement;
import dut.control.moloc.mOloc.ParameterType;
import dut.control.moloc.mOloc.RelationshipType;
import dut.control.moloc.mOloc.Stored_definition;
import dut.control.moloc.mOloc.Unfinished2;
import dut.control.moloc.mOloc.array_subscripts;
import dut.control.moloc.mOloc.class_modification;
import dut.control.moloc.mOloc.class_name;
import dut.control.moloc.mOloc.class_prefixes;
import dut.control.moloc.mOloc.class_specifier;
import dut.control.moloc.mOloc.component_clause1;
import dut.control.moloc.mOloc.component_declaration1;
import dut.control.moloc.mOloc.composition;
import dut.control.moloc.mOloc.constraining_clause;
import dut.control.moloc.mOloc.declaration;
import dut.control.moloc.mOloc.der_class_specifier;
import dut.control.moloc.mOloc.description;
import dut.control.moloc.mOloc.description_string;
import dut.control.moloc.mOloc.element_modification;
import dut.control.moloc.mOloc.element_replaceable;
import dut.control.moloc.mOloc.enum_list;
import dut.control.moloc.mOloc.long_class_specifier;
import dut.control.moloc.mOloc.modification;
import dut.control.moloc.mOloc.short_class_definition;
import dut.control.moloc.mOloc.short_class_specifier;
import dut.control.moloc.mOloc.type_prefix;
import dut.control.moloc.mOloc.type_specifier;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class MOlocPackageImpl extends EPackageImpl implements MOlocPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass stored_definitionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass class_definitionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass class_prefixesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass class_specifierEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass long_class_specifierEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass short_class_specifierEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass der_class_specifierEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass class_nameEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass class_modificationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass description_stringEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass compositionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass type_specifierEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass enum_listEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass enumerationLiteralEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass descriptionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass argumentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass element_modificationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass element_replaceableEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass short_class_definitionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass component_clause1EClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass type_prefixEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass component_declaration1EClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass declarationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass array_subscriptsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass unfinished2EClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modificationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass constraining_clauseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass elementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass importClauseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass extendsClauseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass breakEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass generalClauseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass component_declarationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass externalElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass nullElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum classTypeEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum directionEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum relationshipTypeEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum parameterTypeEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see dut.control.moloc.mOloc.MOlocPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private MOlocPackageImpl()
  {
    super(eNS_URI, MOlocFactory.eINSTANCE);
  }
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link MOlocPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static MOlocPackage init()
  {
    if (isInited) return (MOlocPackage)EPackage.Registry.INSTANCE.getEPackage(MOlocPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredMOlocPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    MOlocPackageImpl theMOlocPackage = registeredMOlocPackage instanceof MOlocPackageImpl ? (MOlocPackageImpl)registeredMOlocPackage : new MOlocPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theMOlocPackage.createPackageContents();

    // Initialize created meta-data
    theMOlocPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theMOlocPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(MOlocPackage.eNS_URI, theMOlocPackage);
    return theMOlocPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getStored_definition()
  {
    return stored_definitionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getStored_definition_IsWithin()
  {
    return (EAttribute)stored_definitionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getStored_definition_Within()
  {
    return (EAttribute)stored_definitionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getStored_definition_Classes()
  {
    return (EReference)stored_definitionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getClass_definition()
  {
    return class_definitionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getClass_definition_Isfinal()
  {
    return (EAttribute)class_definitionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getClass_definition_IsEncapsulated()
  {
    return (EAttribute)class_definitionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getclass_prefixes()
  {
    return class_prefixesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getclass_prefixes_IsPartial()
  {
    return (EAttribute)class_prefixesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getclass_prefixes_IsExpandable()
  {
    return (EAttribute)class_prefixesEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getclass_prefixes_IsPure()
  {
    return (EAttribute)class_prefixesEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getclass_prefixes_IsOperator()
  {
    return (EAttribute)class_prefixesEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getclass_prefixes_ClassType()
  {
    return (EAttribute)class_prefixesEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getclass_specifier()
  {
    return class_specifierEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getlong_class_specifier()
  {
    return long_class_specifierEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getlong_class_specifier_IsExtends()
  {
    return (EAttribute)long_class_specifierEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getshort_class_specifier()
  {
    return short_class_specifierEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getshort_class_specifier_Direction()
  {
    return (EAttribute)short_class_specifierEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getshort_class_specifier_IsEnumeration()
  {
    return (EAttribute)short_class_specifierEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getshort_class_specifier_IsColon()
  {
    return (EAttribute)short_class_specifierEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getder_class_specifier()
  {
    return der_class_specifierEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getder_class_specifier_IsDer()
  {
    return (EAttribute)der_class_specifierEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getder_class_specifier_DerName()
  {
    return (EAttribute)der_class_specifierEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getclass_name()
  {
    return class_nameEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getclass_name_ClassName()
  {
    return (EAttribute)class_nameEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getclass_modification()
  {
    return class_modificationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getclass_modification_Arguments()
  {
    return (EReference)class_modificationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getdescription_string()
  {
    return description_stringEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getdescription_string_Description()
  {
    return (EAttribute)description_stringEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getcomposition()
  {
    return compositionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getcomposition_Elements()
  {
    return (EReference)compositionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass gettype_specifier()
  {
    return type_specifierEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute gettype_specifier_TypeSpecifier()
  {
    return (EAttribute)type_specifierEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getenum_list()
  {
    return enum_listEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getenum_list_EnumerationLiteral()
  {
    return (EReference)enum_listEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEnumerationLiteral()
  {
    return enumerationLiteralEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEnumerationLiteral_Title()
  {
    return (EAttribute)enumerationLiteralEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getdescription()
  {
    return descriptionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getdescription_IsAnnotation()
  {
    return (EAttribute)descriptionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getArgument()
  {
    return argumentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getArgument_IsRedeclare()
  {
    return (EAttribute)argumentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getArgument_IsEach()
  {
    return (EAttribute)argumentEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getArgument_Isfinal()
  {
    return (EAttribute)argumentEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getelement_modification()
  {
    return element_modificationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getelement_modification_ElementName()
  {
    return (EAttribute)element_modificationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getelement_replaceable()
  {
    return element_replaceableEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getelement_replaceable_IsReplaceable()
  {
    return (EAttribute)element_replaceableEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getshort_class_definition()
  {
    return short_class_definitionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getcomponent_clause1()
  {
    return component_clause1EClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass gettype_prefix()
  {
    return type_prefixEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute gettype_prefix_RelationshipType()
  {
    return (EAttribute)type_prefixEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute gettype_prefix_ParameterType()
  {
    return (EAttribute)type_prefixEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute gettype_prefix_DirectionType()
  {
    return (EAttribute)type_prefixEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getcomponent_declaration1()
  {
    return component_declaration1EClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getdeclaration()
  {
    return declarationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getdeclaration_DeclarationName()
  {
    return (EAttribute)declarationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getarray_subscripts()
  {
    return array_subscriptsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getarray_subscripts_Subscript()
  {
    return (EAttribute)array_subscriptsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUnfinished2()
  {
    return unfinished2EClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUnfinished2_Aa()
  {
    return (EAttribute)unfinished2EClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getmodification()
  {
    return modificationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getmodification_Expression()
  {
    return (EAttribute)modificationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getconstraining_clause()
  {
    return constraining_clauseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getconstraining_clause_Elements2()
  {
    return (EReference)constraining_clauseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getElement()
  {
    return elementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getImportClause()
  {
    return importClauseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getImportClause_SelfName()
  {
    return (EAttribute)importClauseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getImportClause_ImportName()
  {
    return (EAttribute)importClauseEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getImportClause_IsImportAll()
  {
    return (EAttribute)importClauseEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getImportClause_ObjectName()
  {
    return (EAttribute)importClauseEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExtendsClause()
  {
    return extendsClauseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getExtendsClause_Breaks()
  {
    return (EReference)extendsClauseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExtendsClause_IsAnnotation()
  {
    return (EAttribute)extendsClauseEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getBreak()
  {
    return breakEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getBreak_Connect()
  {
    return (EReference)breakEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getBreak_BreakName()
  {
    return (EAttribute)breakEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getGeneralClause()
  {
    return generalClauseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGeneralClause_IsRedeclare()
  {
    return (EAttribute)generalClauseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGeneralClause_Isfinal()
  {
    return (EAttribute)generalClauseEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGeneralClause_IsInner()
  {
    return (EAttribute)generalClauseEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGeneralClause_IsOuter()
  {
    return (EAttribute)generalClauseEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGeneralClause_IsReplaceable()
  {
    return (EAttribute)generalClauseEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGeneralClause_Component_list()
  {
    return (EReference)generalClauseEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getComponent_declaration()
  {
    return component_declarationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getComponent_declaration_Condition_attribute()
  {
    return (EAttribute)component_declarationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExternalElement()
  {
    return externalElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExternalElement_Language_specification()
  {
    return (EAttribute)externalElementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExternalElement_Ref()
  {
    return (EAttribute)externalElementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExternalElement_IsAnnotation()
  {
    return (EAttribute)externalElementEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getNULLElement()
  {
    return nullElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getNULLElement_Nullname()
  {
    return (EAttribute)nullElementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getClassType()
  {
    return classTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getDirection()
  {
    return directionEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getRelationshipType()
  {
    return relationshipTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getParameterType()
  {
    return parameterTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MOlocFactory getMOlocFactory()
  {
    return (MOlocFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    stored_definitionEClass = createEClass(STORED_DEFINITION);
    createEAttribute(stored_definitionEClass, STORED_DEFINITION__IS_WITHIN);
    createEAttribute(stored_definitionEClass, STORED_DEFINITION__WITHIN);
    createEReference(stored_definitionEClass, STORED_DEFINITION__CLASSES);

    class_definitionEClass = createEClass(CLASS_DEFINITION);
    createEAttribute(class_definitionEClass, CLASS_DEFINITION__ISFINAL);
    createEAttribute(class_definitionEClass, CLASS_DEFINITION__IS_ENCAPSULATED);

    class_prefixesEClass = createEClass(CLASS_PREFIXES);
    createEAttribute(class_prefixesEClass, CLASS_PREFIXES__IS_PARTIAL);
    createEAttribute(class_prefixesEClass, CLASS_PREFIXES__IS_EXPANDABLE);
    createEAttribute(class_prefixesEClass, CLASS_PREFIXES__IS_PURE);
    createEAttribute(class_prefixesEClass, CLASS_PREFIXES__IS_OPERATOR);
    createEAttribute(class_prefixesEClass, CLASS_PREFIXES__CLASS_TYPE);

    class_specifierEClass = createEClass(CLASS_SPECIFIER);

    long_class_specifierEClass = createEClass(LONG_CLASS_SPECIFIER);
    createEAttribute(long_class_specifierEClass, LONG_CLASS_SPECIFIER__IS_EXTENDS);

    short_class_specifierEClass = createEClass(SHORT_CLASS_SPECIFIER);
    createEAttribute(short_class_specifierEClass, SHORT_CLASS_SPECIFIER__DIRECTION);
    createEAttribute(short_class_specifierEClass, SHORT_CLASS_SPECIFIER__IS_ENUMERATION);
    createEAttribute(short_class_specifierEClass, SHORT_CLASS_SPECIFIER__IS_COLON);

    der_class_specifierEClass = createEClass(DER_CLASS_SPECIFIER);
    createEAttribute(der_class_specifierEClass, DER_CLASS_SPECIFIER__IS_DER);
    createEAttribute(der_class_specifierEClass, DER_CLASS_SPECIFIER__DER_NAME);

    class_nameEClass = createEClass(CLASS_NAME);
    createEAttribute(class_nameEClass, CLASS_NAME__CLASS_NAME);

    class_modificationEClass = createEClass(CLASS_MODIFICATION);
    createEReference(class_modificationEClass, CLASS_MODIFICATION__ARGUMENTS);

    description_stringEClass = createEClass(DESCRIPTION_STRING);
    createEAttribute(description_stringEClass, DESCRIPTION_STRING__DESCRIPTION);

    compositionEClass = createEClass(COMPOSITION);
    createEReference(compositionEClass, COMPOSITION__ELEMENTS);

    type_specifierEClass = createEClass(TYPE_SPECIFIER);
    createEAttribute(type_specifierEClass, TYPE_SPECIFIER__TYPE_SPECIFIER);

    enum_listEClass = createEClass(ENUM_LIST);
    createEReference(enum_listEClass, ENUM_LIST__ENUMERATION_LITERAL);

    enumerationLiteralEClass = createEClass(ENUMERATION_LITERAL);
    createEAttribute(enumerationLiteralEClass, ENUMERATION_LITERAL__TITLE);

    descriptionEClass = createEClass(DESCRIPTION);
    createEAttribute(descriptionEClass, DESCRIPTION__IS_ANNOTATION);

    argumentEClass = createEClass(ARGUMENT);
    createEAttribute(argumentEClass, ARGUMENT__IS_REDECLARE);
    createEAttribute(argumentEClass, ARGUMENT__IS_EACH);
    createEAttribute(argumentEClass, ARGUMENT__ISFINAL);

    element_modificationEClass = createEClass(ELEMENT_MODIFICATION);
    createEAttribute(element_modificationEClass, ELEMENT_MODIFICATION__ELEMENT_NAME);

    element_replaceableEClass = createEClass(ELEMENT_REPLACEABLE);
    createEAttribute(element_replaceableEClass, ELEMENT_REPLACEABLE__IS_REPLACEABLE);

    short_class_definitionEClass = createEClass(SHORT_CLASS_DEFINITION);

    component_clause1EClass = createEClass(COMPONENT_CLAUSE1);

    type_prefixEClass = createEClass(TYPE_PREFIX);
    createEAttribute(type_prefixEClass, TYPE_PREFIX__RELATIONSHIP_TYPE);
    createEAttribute(type_prefixEClass, TYPE_PREFIX__PARAMETER_TYPE);
    createEAttribute(type_prefixEClass, TYPE_PREFIX__DIRECTION_TYPE);

    component_declaration1EClass = createEClass(COMPONENT_DECLARATION1);

    declarationEClass = createEClass(DECLARATION);
    createEAttribute(declarationEClass, DECLARATION__DECLARATION_NAME);

    array_subscriptsEClass = createEClass(ARRAY_SUBSCRIPTS);
    createEAttribute(array_subscriptsEClass, ARRAY_SUBSCRIPTS__SUBSCRIPT);

    unfinished2EClass = createEClass(UNFINISHED2);
    createEAttribute(unfinished2EClass, UNFINISHED2__AA);

    modificationEClass = createEClass(MODIFICATION);
    createEAttribute(modificationEClass, MODIFICATION__EXPRESSION);

    constraining_clauseEClass = createEClass(CONSTRAINING_CLAUSE);
    createEReference(constraining_clauseEClass, CONSTRAINING_CLAUSE__ELEMENTS2);

    elementEClass = createEClass(ELEMENT);

    importClauseEClass = createEClass(IMPORT_CLAUSE);
    createEAttribute(importClauseEClass, IMPORT_CLAUSE__SELF_NAME);
    createEAttribute(importClauseEClass, IMPORT_CLAUSE__IMPORT_NAME);
    createEAttribute(importClauseEClass, IMPORT_CLAUSE__IS_IMPORT_ALL);
    createEAttribute(importClauseEClass, IMPORT_CLAUSE__OBJECT_NAME);

    extendsClauseEClass = createEClass(EXTENDS_CLAUSE);
    createEReference(extendsClauseEClass, EXTENDS_CLAUSE__BREAKS);
    createEAttribute(extendsClauseEClass, EXTENDS_CLAUSE__IS_ANNOTATION);

    breakEClass = createEClass(BREAK);
    createEReference(breakEClass, BREAK__CONNECT);
    createEAttribute(breakEClass, BREAK__BREAK_NAME);

    generalClauseEClass = createEClass(GENERAL_CLAUSE);
    createEAttribute(generalClauseEClass, GENERAL_CLAUSE__IS_REDECLARE);
    createEAttribute(generalClauseEClass, GENERAL_CLAUSE__ISFINAL);
    createEAttribute(generalClauseEClass, GENERAL_CLAUSE__IS_INNER);
    createEAttribute(generalClauseEClass, GENERAL_CLAUSE__IS_OUTER);
    createEAttribute(generalClauseEClass, GENERAL_CLAUSE__IS_REPLACEABLE);
    createEReference(generalClauseEClass, GENERAL_CLAUSE__COMPONENT_LIST);

    component_declarationEClass = createEClass(COMPONENT_DECLARATION);
    createEAttribute(component_declarationEClass, COMPONENT_DECLARATION__CONDITION_ATTRIBUTE);

    externalElementEClass = createEClass(EXTERNAL_ELEMENT);
    createEAttribute(externalElementEClass, EXTERNAL_ELEMENT__LANGUAGE_SPECIFICATION);
    createEAttribute(externalElementEClass, EXTERNAL_ELEMENT__REF);
    createEAttribute(externalElementEClass, EXTERNAL_ELEMENT__IS_ANNOTATION);

    nullElementEClass = createEClass(NULL_ELEMENT);
    createEAttribute(nullElementEClass, NULL_ELEMENT__NULLNAME);

    // Create enums
    classTypeEEnum = createEEnum(CLASS_TYPE);
    directionEEnum = createEEnum(DIRECTION);
    relationshipTypeEEnum = createEEnum(RELATIONSHIP_TYPE);
    parameterTypeEEnum = createEEnum(PARAMETER_TYPE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    class_definitionEClass.getESuperTypes().add(this.getclass_prefixes());
    class_definitionEClass.getESuperTypes().add(this.getclass_specifier());
    class_definitionEClass.getESuperTypes().add(this.getlong_class_specifier());
    class_definitionEClass.getESuperTypes().add(this.getclass_name());
    class_definitionEClass.getESuperTypes().add(this.getclass_modification());
    class_definitionEClass.getESuperTypes().add(this.getdescription_string());
    class_definitionEClass.getESuperTypes().add(this.getcomposition());
    class_definitionEClass.getESuperTypes().add(this.getshort_class_specifier());
    class_definitionEClass.getESuperTypes().add(this.gettype_specifier());
    class_definitionEClass.getESuperTypes().add(this.getenum_list());
    class_definitionEClass.getESuperTypes().add(this.getdescription());
    class_definitionEClass.getESuperTypes().add(this.getder_class_specifier());
    class_specifierEClass.getESuperTypes().add(this.getlong_class_specifier());
    class_specifierEClass.getESuperTypes().add(this.getclass_name());
    class_specifierEClass.getESuperTypes().add(this.getclass_modification());
    class_specifierEClass.getESuperTypes().add(this.getdescription_string());
    class_specifierEClass.getESuperTypes().add(this.getcomposition());
    class_specifierEClass.getESuperTypes().add(this.getshort_class_specifier());
    class_specifierEClass.getESuperTypes().add(this.gettype_specifier());
    class_specifierEClass.getESuperTypes().add(this.getenum_list());
    class_specifierEClass.getESuperTypes().add(this.getdescription());
    class_specifierEClass.getESuperTypes().add(this.getder_class_specifier());
    long_class_specifierEClass.getESuperTypes().add(this.getclass_name());
    long_class_specifierEClass.getESuperTypes().add(this.getclass_modification());
    long_class_specifierEClass.getESuperTypes().add(this.getdescription_string());
    long_class_specifierEClass.getESuperTypes().add(this.getcomposition());
    short_class_specifierEClass.getESuperTypes().add(this.getclass_name());
    short_class_specifierEClass.getESuperTypes().add(this.gettype_specifier());
    short_class_specifierEClass.getESuperTypes().add(this.getclass_modification());
    short_class_specifierEClass.getESuperTypes().add(this.getenum_list());
    short_class_specifierEClass.getESuperTypes().add(this.getdescription());
    short_class_specifierEClass.getESuperTypes().add(this.getdescription_string());
    der_class_specifierEClass.getESuperTypes().add(this.getclass_name());
    der_class_specifierEClass.getESuperTypes().add(this.gettype_specifier());
    der_class_specifierEClass.getESuperTypes().add(this.getdescription());
    der_class_specifierEClass.getESuperTypes().add(this.getdescription_string());
    der_class_specifierEClass.getESuperTypes().add(this.getclass_modification());
    enumerationLiteralEClass.getESuperTypes().add(this.getdescription());
    enumerationLiteralEClass.getESuperTypes().add(this.getdescription_string());
    enumerationLiteralEClass.getESuperTypes().add(this.getclass_modification());
    descriptionEClass.getESuperTypes().add(this.getdescription_string());
    descriptionEClass.getESuperTypes().add(this.getclass_modification());
    argumentEClass.getESuperTypes().add(this.getshort_class_definition());
    argumentEClass.getESuperTypes().add(this.getclass_prefixes());
    argumentEClass.getESuperTypes().add(this.getshort_class_specifier());
    element_modificationEClass.getESuperTypes().add(this.getmodification());
    element_modificationEClass.getESuperTypes().add(this.getclass_modification());
    element_modificationEClass.getESuperTypes().add(this.getdescription_string());
    element_replaceableEClass.getESuperTypes().add(this.getshort_class_definition());
    element_replaceableEClass.getESuperTypes().add(this.getclass_prefixes());
    element_replaceableEClass.getESuperTypes().add(this.getshort_class_specifier());
    element_replaceableEClass.getESuperTypes().add(this.getcomponent_clause1());
    element_replaceableEClass.getESuperTypes().add(this.gettype_prefix());
    element_replaceableEClass.getESuperTypes().add(this.getcomponent_declaration1());
    element_replaceableEClass.getESuperTypes().add(this.getdeclaration());
    element_replaceableEClass.getESuperTypes().add(this.getarray_subscripts());
    element_replaceableEClass.getESuperTypes().add(this.getmodification());
    element_replaceableEClass.getESuperTypes().add(this.getconstraining_clause());
    short_class_definitionEClass.getESuperTypes().add(this.getclass_prefixes());
    short_class_definitionEClass.getESuperTypes().add(this.getshort_class_specifier());
    component_clause1EClass.getESuperTypes().add(this.gettype_prefix());
    component_clause1EClass.getESuperTypes().add(this.gettype_specifier());
    component_clause1EClass.getESuperTypes().add(this.getcomponent_declaration1());
    component_clause1EClass.getESuperTypes().add(this.getdeclaration());
    component_clause1EClass.getESuperTypes().add(this.getarray_subscripts());
    component_clause1EClass.getESuperTypes().add(this.getmodification());
    component_clause1EClass.getESuperTypes().add(this.getclass_modification());
    component_clause1EClass.getESuperTypes().add(this.getdescription());
    component_declaration1EClass.getESuperTypes().add(this.getdeclaration());
    component_declaration1EClass.getESuperTypes().add(this.getarray_subscripts());
    component_declaration1EClass.getESuperTypes().add(this.getmodification());
    component_declaration1EClass.getESuperTypes().add(this.getclass_modification());
    component_declaration1EClass.getESuperTypes().add(this.getdescription());
    declarationEClass.getESuperTypes().add(this.getarray_subscripts());
    declarationEClass.getESuperTypes().add(this.getmodification());
    declarationEClass.getESuperTypes().add(this.getclass_modification());
    modificationEClass.getESuperTypes().add(this.getclass_modification());
    importClauseEClass.getESuperTypes().add(this.getElement());
    importClauseEClass.getESuperTypes().add(this.getdescription());
    extendsClauseEClass.getESuperTypes().add(this.getElement());
    extendsClauseEClass.getESuperTypes().add(this.gettype_specifier());
    extendsClauseEClass.getESuperTypes().add(this.getclass_modification());
    generalClauseEClass.getESuperTypes().add(this.getElement());
    generalClauseEClass.getESuperTypes().add(this.gettype_prefix());
    generalClauseEClass.getESuperTypes().add(this.gettype_specifier());
    generalClauseEClass.getESuperTypes().add(this.getarray_subscripts());
    component_declarationEClass.getESuperTypes().add(this.getdeclaration());
    component_declarationEClass.getESuperTypes().add(this.getdescription());
    externalElementEClass.getESuperTypes().add(this.getElement());
    externalElementEClass.getESuperTypes().add(this.getclass_modification());

    // Initialize classes and features; add operations and parameters
    initEClass(stored_definitionEClass, Stored_definition.class, "Stored_definition", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getStored_definition_IsWithin(), ecorePackage.getEBoolean(), "isWithin", null, 0, 1, Stored_definition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getStored_definition_Within(), ecorePackage.getEString(), "within", null, 0, 1, Stored_definition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getStored_definition_Classes(), this.getClass_definition(), null, "classes", null, 0, -1, Stored_definition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(class_definitionEClass, Class_definition.class, "Class_definition", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getClass_definition_Isfinal(), ecorePackage.getEBoolean(), "isfinal", null, 0, 1, Class_definition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getClass_definition_IsEncapsulated(), ecorePackage.getEBoolean(), "isEncapsulated", null, 0, 1, Class_definition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(class_prefixesEClass, class_prefixes.class, "class_prefixes", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getclass_prefixes_IsPartial(), ecorePackage.getEBoolean(), "isPartial", null, 0, 1, class_prefixes.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getclass_prefixes_IsExpandable(), ecorePackage.getEBoolean(), "isExpandable", null, 0, 1, class_prefixes.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getclass_prefixes_IsPure(), ecorePackage.getEBoolean(), "isPure", null, 0, 1, class_prefixes.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getclass_prefixes_IsOperator(), ecorePackage.getEBoolean(), "isOperator", null, 0, 1, class_prefixes.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getclass_prefixes_ClassType(), this.getClassType(), "classType", null, 0, 1, class_prefixes.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(class_specifierEClass, class_specifier.class, "class_specifier", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(long_class_specifierEClass, long_class_specifier.class, "long_class_specifier", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getlong_class_specifier_IsExtends(), ecorePackage.getEBoolean(), "isExtends", null, 0, 1, long_class_specifier.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(short_class_specifierEClass, short_class_specifier.class, "short_class_specifier", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getshort_class_specifier_Direction(), this.getDirection(), "direction", null, 0, 1, short_class_specifier.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getshort_class_specifier_IsEnumeration(), ecorePackage.getEBoolean(), "isEnumeration", null, 0, 1, short_class_specifier.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getshort_class_specifier_IsColon(), ecorePackage.getEBoolean(), "isColon", null, 0, 1, short_class_specifier.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(der_class_specifierEClass, der_class_specifier.class, "der_class_specifier", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getder_class_specifier_IsDer(), ecorePackage.getEBoolean(), "isDer", null, 0, 1, der_class_specifier.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getder_class_specifier_DerName(), ecorePackage.getEString(), "derName", null, 0, -1, der_class_specifier.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(class_nameEClass, class_name.class, "class_name", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getclass_name_ClassName(), ecorePackage.getEString(), "className", null, 0, 1, class_name.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(class_modificationEClass, class_modification.class, "class_modification", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getclass_modification_Arguments(), this.getArgument(), null, "arguments", null, 0, -1, class_modification.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(description_stringEClass, description_string.class, "description_string", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getdescription_string_Description(), ecorePackage.getEString(), "description", null, 0, 1, description_string.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(compositionEClass, composition.class, "composition", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getcomposition_Elements(), this.getElement(), null, "elements", null, 0, -1, composition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(type_specifierEClass, type_specifier.class, "type_specifier", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(gettype_specifier_TypeSpecifier(), ecorePackage.getEString(), "typeSpecifier", null, 0, 1, type_specifier.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(enum_listEClass, enum_list.class, "enum_list", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getenum_list_EnumerationLiteral(), this.getEnumerationLiteral(), null, "enumerationLiteral", null, 0, -1, enum_list.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(enumerationLiteralEClass, EnumerationLiteral.class, "EnumerationLiteral", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEnumerationLiteral_Title(), ecorePackage.getEString(), "title", null, 0, 1, EnumerationLiteral.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(descriptionEClass, description.class, "description", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getdescription_IsAnnotation(), ecorePackage.getEBoolean(), "isAnnotation", null, 0, 1, description.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(argumentEClass, Argument.class, "Argument", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getArgument_IsRedeclare(), ecorePackage.getEBoolean(), "isRedeclare", null, 0, 1, Argument.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getArgument_IsEach(), ecorePackage.getEBoolean(), "isEach", null, 0, 1, Argument.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getArgument_Isfinal(), ecorePackage.getEBoolean(), "isfinal", null, 0, 1, Argument.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(element_modificationEClass, element_modification.class, "element_modification", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getelement_modification_ElementName(), ecorePackage.getEString(), "elementName", null, 0, 1, element_modification.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(element_replaceableEClass, element_replaceable.class, "element_replaceable", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getelement_replaceable_IsReplaceable(), ecorePackage.getEBoolean(), "isReplaceable", null, 0, 1, element_replaceable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(short_class_definitionEClass, short_class_definition.class, "short_class_definition", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(component_clause1EClass, component_clause1.class, "component_clause1", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(type_prefixEClass, type_prefix.class, "type_prefix", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(gettype_prefix_RelationshipType(), this.getRelationshipType(), "relationshipType", null, 0, 1, type_prefix.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(gettype_prefix_ParameterType(), this.getParameterType(), "parameterType", null, 0, 1, type_prefix.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(gettype_prefix_DirectionType(), this.getDirection(), "directionType", null, 0, 1, type_prefix.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(component_declaration1EClass, component_declaration1.class, "component_declaration1", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(declarationEClass, declaration.class, "declaration", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getdeclaration_DeclarationName(), ecorePackage.getEString(), "declarationName", null, 0, 1, declaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(array_subscriptsEClass, array_subscripts.class, "array_subscripts", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getarray_subscripts_Subscript(), ecorePackage.getEString(), "subscript", null, 0, -1, array_subscripts.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(unfinished2EClass, Unfinished2.class, "Unfinished2", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getUnfinished2_Aa(), ecorePackage.getEString(), "aa", null, 0, 1, Unfinished2.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(modificationEClass, modification.class, "modification", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getmodification_Expression(), ecorePackage.getEString(), "expression", null, 0, 1, modification.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(constraining_clauseEClass, constraining_clause.class, "constraining_clause", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getconstraining_clause_Elements2(), this.getUnfinished2(), null, "elements2", null, 0, -1, constraining_clause.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(elementEClass, Element.class, "Element", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(importClauseEClass, ImportClause.class, "ImportClause", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getImportClause_SelfName(), ecorePackage.getEString(), "selfName", null, 0, 1, ImportClause.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getImportClause_ImportName(), ecorePackage.getEString(), "importName", null, 0, 1, ImportClause.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getImportClause_IsImportAll(), ecorePackage.getEBoolean(), "isImportAll", null, 0, 1, ImportClause.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getImportClause_ObjectName(), ecorePackage.getEString(), "objectName", null, 0, -1, ImportClause.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(extendsClauseEClass, ExtendsClause.class, "ExtendsClause", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getExtendsClause_Breaks(), this.getBreak(), null, "breaks", null, 0, -1, ExtendsClause.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getExtendsClause_IsAnnotation(), ecorePackage.getEBoolean(), "isAnnotation", null, 0, 1, ExtendsClause.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(breakEClass, Break.class, "Break", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getBreak_Connect(), this.getNULLElement(), null, "connect", null, 0, 1, Break.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getBreak_BreakName(), ecorePackage.getEString(), "breakName", null, 0, 1, Break.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(generalClauseEClass, GeneralClause.class, "GeneralClause", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getGeneralClause_IsRedeclare(), ecorePackage.getEBoolean(), "isRedeclare", null, 0, 1, GeneralClause.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGeneralClause_Isfinal(), ecorePackage.getEBoolean(), "isfinal", null, 0, 1, GeneralClause.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGeneralClause_IsInner(), ecorePackage.getEBoolean(), "isInner", null, 0, 1, GeneralClause.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGeneralClause_IsOuter(), ecorePackage.getEBoolean(), "isOuter", null, 0, 1, GeneralClause.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGeneralClause_IsReplaceable(), ecorePackage.getEBoolean(), "isReplaceable", null, 0, 1, GeneralClause.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGeneralClause_Component_list(), this.getComponent_declaration(), null, "component_list", null, 0, -1, GeneralClause.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(component_declarationEClass, Component_declaration.class, "Component_declaration", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getComponent_declaration_Condition_attribute(), ecorePackage.getEString(), "condition_attribute", null, 0, 1, Component_declaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(externalElementEClass, ExternalElement.class, "ExternalElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getExternalElement_Language_specification(), ecorePackage.getEString(), "language_specification", null, 0, 1, ExternalElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getExternalElement_Ref(), ecorePackage.getEString(), "ref", null, 0, 1, ExternalElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getExternalElement_IsAnnotation(), ecorePackage.getEBoolean(), "isAnnotation", null, 0, 1, ExternalElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(nullElementEClass, NULLElement.class, "NULLElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getNULLElement_Nullname(), ecorePackage.getEString(), "nullname", null, 0, 1, NULLElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(classTypeEEnum, ClassType.class, "ClassType");
    addEEnumLiteral(classTypeEEnum, ClassType.NULL);
    addEEnumLiteral(classTypeEEnum, ClassType.CLASS);
    addEEnumLiteral(classTypeEEnum, ClassType.MODEL);
    addEEnumLiteral(classTypeEEnum, ClassType.RECORD);
    addEEnumLiteral(classTypeEEnum, ClassType.BLOCK);
    addEEnumLiteral(classTypeEEnum, ClassType.CONNECTOR);
    addEEnumLiteral(classTypeEEnum, ClassType.TYPE);
    addEEnumLiteral(classTypeEEnum, ClassType.PACKAGE);
    addEEnumLiteral(classTypeEEnum, ClassType.FUNCTION);

    initEEnum(directionEEnum, Direction.class, "Direction");
    addEEnumLiteral(directionEEnum, Direction.NULL);
    addEEnumLiteral(directionEEnum, Direction.INPUT);
    addEEnumLiteral(directionEEnum, Direction.OUTPUT);

    initEEnum(relationshipTypeEEnum, RelationshipType.class, "RelationshipType");
    addEEnumLiteral(relationshipTypeEEnum, RelationshipType.NULL);
    addEEnumLiteral(relationshipTypeEEnum, RelationshipType.FLOW);
    addEEnumLiteral(relationshipTypeEEnum, RelationshipType.STREAM);

    initEEnum(parameterTypeEEnum, ParameterType.class, "ParameterType");
    addEEnumLiteral(parameterTypeEEnum, ParameterType.NULL);
    addEEnumLiteral(parameterTypeEEnum, ParameterType.DISCRETE);
    addEEnumLiteral(parameterTypeEEnum, ParameterType.PARAMETER);
    addEEnumLiteral(parameterTypeEEnum, ParameterType.CONSTANT);

    // Create resource
    createResource(eNS_URI);
  }

} //MOlocPackageImpl
