/**
 * generated by Xtext 2.38.0
 */
package dut.control.sysmloc.sysMLOC;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Calculation Usage</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dut.control.sysmloc.sysMLOC.CalculationUsage#getElements <em>Elements</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.CalculationUsage#getResultExpressionParameter <em>Result Expression Parameter</em>}</li>
 * </ul>
 *
 * @see dut.control.sysmloc.sysMLOC.SysMLOCPackage#getCalculationUsage()
 * @model
 * @generated
 */
public interface CalculationUsage extends BehaviorUsageElements, GeneralUsagePrefix, EmptySuccessionPrefix, MemberPrefix, isReturnPrefix, OccurrenceUsagePrefix, EndUsagePrefix, CrossEndUsagePrefix, BasicUsagePrefix, RefPrefix, BasicDefinitionPrefix, UsageExtensionKeyword, PrefixMetadata, ActionUsageDeclaration, UsageDeclaration, FeatureDeclaration, Identification, FeatureSpecializationPart, FeatureSpecialization, TypingFeatureTyping, SubsettingFeatureChain, ReferenceFeatureChain, CrossFeatureChain, RedefinitionFeatureChain, MultiplicityPart, MultiplicityRange, MultiplicityModifiers, FeatureValue
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link dut.control.sysmloc.sysMLOC.CalculationBodyElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see dut.control.sysmloc.sysMLOC.SysMLOCPackage#getCalculationUsage_Elements()
   * @model containment="true"
   * @generated
   */
  EList<CalculationBodyElement> getElements();

  /**
   * Returns the value of the '<em><b>Result Expression Parameter</b></em>' containment reference list.
   * The list contents are of type {@link dut.control.sysmloc.sysMLOC.ResultExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Result Expression Parameter</em>' containment reference list.
   * @see dut.control.sysmloc.sysMLOC.SysMLOCPackage#getCalculationUsage_ResultExpressionParameter()
   * @model containment="true"
   * @generated
   */
  EList<ResultExpression> getResultExpressionParameter();

} // CalculationUsage
