/**
 * generated by Xtext 2.38.0
 */
package dut.control.sysmloc.sysMLOC;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dut.control.sysmloc.sysMLOC.Comment#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see dut.control.sysmloc.sysMLOC.SysMLOCPackage#getComment()
 * @model
 * @generated
 */
public interface Comment extends AnnotatingElement
{
  /**
   * Returns the value of the '<em><b>Body</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' attribute.
   * @see #setBody(String)
   * @see dut.control.sysmloc.sysMLOC.SysMLOCPackage#getComment_Body()
   * @model
   * @generated
   */
  String getBody();

  /**
   * Sets the value of the '{@link dut.control.sysmloc.sysMLOC.Comment#getBody <em>Body</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' attribute.
   * @see #getBody()
   * @generated
   */
  void setBody(String value);

} // Comment
