/**
 * generated by Xtext 2.38.0
 */
package dut.control.sysmloc.sysMLOC;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Control Node Prefix</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dut.control.sysmloc.sysMLOC.ControlNodePrefix#isIsIndividual <em>Is Individual</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.ControlNodePrefix#getPortionKind <em>Portion Kind</em>}</li>
 * </ul>
 *
 * @see dut.control.sysmloc.sysMLOC.SysMLOCPackage#getControlNodePrefix()
 * @model
 * @generated
 */
public interface ControlNodePrefix extends RefPrefix
{
  /**
   * Returns the value of the '<em><b>Is Individual</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Individual</em>' attribute.
   * @see #setIsIndividual(boolean)
   * @see dut.control.sysmloc.sysMLOC.SysMLOCPackage#getControlNodePrefix_IsIndividual()
   * @model
   * @generated
   */
  boolean isIsIndividual();

  /**
   * Sets the value of the '{@link dut.control.sysmloc.sysMLOC.ControlNodePrefix#isIsIndividual <em>Is Individual</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Individual</em>' attribute.
   * @see #isIsIndividual()
   * @generated
   */
  void setIsIndividual(boolean value);

  /**
   * Returns the value of the '<em><b>Portion Kind</b></em>' attribute.
   * The literals are from the enumeration {@link dut.control.sysmloc.sysMLOC.PortionKind}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Portion Kind</em>' attribute.
   * @see dut.control.sysmloc.sysMLOC.PortionKind
   * @see #setPortionKind(PortionKind)
   * @see dut.control.sysmloc.sysMLOC.SysMLOCPackage#getControlNodePrefix_PortionKind()
   * @model
   * @generated
   */
  PortionKind getPortionKind();

  /**
   * Sets the value of the '{@link dut.control.sysmloc.sysMLOC.ControlNodePrefix#getPortionKind <em>Portion Kind</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Portion Kind</em>' attribute.
   * @see dut.control.sysmloc.sysMLOC.PortionKind
   * @see #getPortionKind()
   * @generated
   */
  void setPortionKind(PortionKind value);

} // ControlNodePrefix
