/**
 * generated by Xtext 2.38.0
 */
package dut.control.sysmloc.sysMLOC;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Include Use Case Usage</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dut.control.sysmloc.sysMLOC.IncludeUseCaseUsage#getElements <em>Elements</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.IncludeUseCaseUsage#getResultExpressionParameter <em>Result Expression Parameter</em>}</li>
 * </ul>
 *
 * @see dut.control.sysmloc.sysMLOC.SysMLOCPackage#getIncludeUseCaseUsage()
 * @model
 * @generated
 */
public interface IncludeUseCaseUsage extends BehaviorUsageElements, GeneralUsagePrefix, EmptySuccessionPrefix, MemberPrefix, isReturnPrefix, OccurrenceUsagePrefix, BasicUsagePrefix, RefPrefix, BasicDefinitionPrefix, UsageExtensionKeyword, PrefixMetadata, ReferenceSubsetting, FeatureSpecializationPart, FeatureSpecialization, TypingFeatureTyping, SubsettingFeatureChain, ReferenceFeatureChain, CrossFeatureChain, RedefinitionFeatureChain, MultiplicityPart, MultiplicityRange, UsageDeclaration, FeatureDeclaration, Identification, ValuePart, FeatureValue
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link dut.control.sysmloc.sysMLOC.CaseBodyElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see dut.control.sysmloc.sysMLOC.SysMLOCPackage#getIncludeUseCaseUsage_Elements()
   * @model containment="true"
   * @generated
   */
  EList<CaseBodyElement> getElements();

  /**
   * Returns the value of the '<em><b>Result Expression Parameter</b></em>' containment reference list.
   * The list contents are of type {@link dut.control.sysmloc.sysMLOC.ResultExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Result Expression Parameter</em>' containment reference list.
   * @see dut.control.sysmloc.sysMLOC.SysMLOCPackage#getIncludeUseCaseUsage_ResultExpressionParameter()
   * @model containment="true"
   * @generated
   */
  EList<ResultExpression> getResultExpressionParameter();

} // IncludeUseCaseUsage
