/**
 * generated by Xtext 2.38.0
 */
package dut.control.sysmloc.sysMLOC;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Multiplicity Modifiers</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dut.control.sysmloc.sysMLOC.MultiplicityModifiers#isIsOrdered <em>Is Ordered</em>}</li>
 *   <li>{@link dut.control.sysmloc.sysMLOC.MultiplicityModifiers#isIsNonunique <em>Is Nonunique</em>}</li>
 * </ul>
 *
 * @see dut.control.sysmloc.sysMLOC.SysMLOCPackage#getMultiplicityModifiers()
 * @model
 * @generated
 */
public interface MultiplicityModifiers extends EObject
{
  /**
   * Returns the value of the '<em><b>Is Ordered</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Ordered</em>' attribute.
   * @see #setIsOrdered(boolean)
   * @see dut.control.sysmloc.sysMLOC.SysMLOCPackage#getMultiplicityModifiers_IsOrdered()
   * @model
   * @generated
   */
  boolean isIsOrdered();

  /**
   * Sets the value of the '{@link dut.control.sysmloc.sysMLOC.MultiplicityModifiers#isIsOrdered <em>Is Ordered</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Ordered</em>' attribute.
   * @see #isIsOrdered()
   * @generated
   */
  void setIsOrdered(boolean value);

  /**
   * Returns the value of the '<em><b>Is Nonunique</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Nonunique</em>' attribute.
   * @see #setIsNonunique(boolean)
   * @see dut.control.sysmloc.sysMLOC.SysMLOCPackage#getMultiplicityModifiers_IsNonunique()
   * @model
   * @generated
   */
  boolean isIsNonunique();

  /**
   * Sets the value of the '{@link dut.control.sysmloc.sysMLOC.MultiplicityModifiers#isIsNonunique <em>Is Nonunique</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Nonunique</em>' attribute.
   * @see #isIsNonunique()
   * @generated
   */
  void setIsNonunique(boolean value);

} // MultiplicityModifiers
