/**
 * generated by Xtext 2.38.0
 */
package dut.control.sysmloc.sysMLOC;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Namespace Import</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dut.control.sysmloc.sysMLOC.SysMLOCPackage#getNamespaceImport()
 * @model
 * @generated
 */
public interface NamespaceImport extends ImportElement
{
} // NamespaceImport
