/**
 * generated by Xtext 2.38.0
 */
package dut.control.sysmloc.sysMLOC;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Non Occurrence Usage Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dut.control.sysmloc.sysMLOC.SysMLOCPackage#getNonOccurrenceUsageElement()
 * @model
 * @generated
 */
public interface NonOccurrenceUsageElement extends UsageElement
{
} // NonOccurrenceUsageElement
