/**
 * generated by Xtext 2.38.0
 */
package dut.control.sysmloc.sysMLOC;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Part Usage</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dut.control.sysmloc.sysMLOC.PartUsage#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see dut.control.sysmloc.sysMLOC.SysMLOCPackage#getPartUsage()
 * @model
 * @generated
 */
public interface PartUsage extends Type
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see dut.control.sysmloc.sysMLOC.SysMLOCPackage#getPartUsage_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link dut.control.sysmloc.sysMLOC.PartUsage#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // PartUsage
