/**
 * generated by Xtext 2.38.0
 */
package dut.control.sysmloc.sysMLOC;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rendering Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dut.control.sysmloc.sysMLOC.RenderingDefinition#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see dut.control.sysmloc.sysMLOC.SysMLOCPackage#getRenderingDefinition()
 * @model
 * @generated
 */
public interface RenderingDefinition extends DefinitionElement, MemberPrefix, OccurrenceDefinitionPrefix, BasicDefinitionPrefix, DefinitionDeclaration, Identification
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link dut.control.sysmloc.sysMLOC.DefinitionBodyElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see dut.control.sysmloc.sysMLOC.SysMLOCPackage#getRenderingDefinition_Elements()
   * @model containment="true"
   * @generated
   */
  EList<DefinitionBodyElement> getElements();

} // RenderingDefinition
