/**
 * generated by Xtext 2.38.0
 */
package dut.control.sysmloc.sysMLOC;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dut.control.sysmloc.sysMLOC.SysMLOCPackage#getType()
 * @model
 * @generated
 */
public interface Type extends EObject
{
} // Type
