/**
 * generated by Xtext 2.38.0
 */
package dut.control.sysmloc.sysMLOC;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Usage</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dut.control.sysmloc.sysMLOC.SysMLOCPackage#getUsage()
 * @model
 * @generated
 */
public interface Usage extends UsageDeclaration, FeatureDeclaration, Identification, FeatureSpecializationPart, FeatureSpecialization, TypingFeatureChain, SubsettingFeatureChain, ReferenceFeatureChain, CrossFeatureChain, RedefinitionFeatureChain, MultiplicityPart, MultiplicityRange, MultiplicityModifiers, FeatureValue
{
} // Usage
