package VehicleDefinitions{
	doc  /*
	     	 * Example vehicle definitions model.
	     	 */;
	// == Unfinished ImportElement ==;
	// == Unfinished ImportElement ==;
	// == Unfinished ImportElement ==;
	// == Unfinished ImportElement ==;
	// == Unfinished ImportElement ==;
	// == Unfinished Comment ==;
	part def Vehicle{
		// == Unfinished AttributeUsage ==;
	}
	part def Transmission;
	part def AxleAssembly;
	part def Axle{
		// == Unfinished PortUsage ==;
		// == Unfinished PortUsage ==;
	}
	part def Wheel{
		// == Unfinished PortUsage ==;
	}
	part def Lugbolt{
		// == Unfinished AttributeUsage ==;
	}
	// == Unfinished Comment ==;
	// == Unfinished PortDefinition =={
		// == Unfinished DefaultReferenceUsage ==;
	}
	// == Unfinished PortDefinition =={
		// == Unfinished DefaultReferenceUsage ==;
	}
	// == Unfinished PortDefinition =={
		// == Unfinished DefaultReferenceUsage ==;
	}
	// == Unfinished Comment ==;
	// == Unfinished InterfaceDefinition =={
		doc  /* The definition of the interface for mounting a Wheel to an Axle. */;
		// == Unfinished DefaultReferenceUsage ==;
		// == Unfinished DefaultReferenceUsage ==;
		// == Unfinished FlowUsage ==;
	}
}

