/*
 * generated by Xtext 2.38.0
 */
package dut.control.sysmloc.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import dut.control.sysmloc.ide.contentassist.antlr.internal.InternalSysMLOCParser;
import dut.control.sysmloc.services.SysMLOCGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class SysMLOCParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(SysMLOCGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, SysMLOCGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getBaseElementAccess().getAlternatives(), "rule__BaseElement__Alternatives");
			builder.put(grammarAccess.getDefinitionElementAccess().getAlternatives(), "rule__DefinitionElement__Alternatives");
			builder.put(grammarAccess.getUsageElementAccess().getAlternatives(), "rule__UsageElement__Alternatives");
			builder.put(grammarAccess.getOccurrenceUsageElementAccess().getAlternatives(), "rule__OccurrenceUsageElement__Alternatives");
			builder.put(grammarAccess.getAttributeDefinitionAccess().getAlternatives_3(), "rule__AttributeDefinition__Alternatives_3");
			builder.put(grammarAccess.getPartDefinitionAccess().getAlternatives_4(), "rule__PartDefinition__Alternatives_4");
			builder.put(grammarAccess.getAttributeUsageAccess().getAlternatives_2(), "rule__AttributeUsage__Alternatives_2");
			builder.put(grammarAccess.getActionUsageAccess().getAlternatives_2(), "rule__ActionUsage__Alternatives_2");
			builder.put(grammarAccess.getPartUsageAccess().getAlternatives_2(), "rule__PartUsage__Alternatives_2");
			builder.put(grammarAccess.getFeatureValueAccess().getAlternatives_0(), "rule__FeatureValue__Alternatives_0");
			builder.put(grammarAccess.getFeatureValueAccess().getAlternatives_0_2_1(), "rule__FeatureValue__Alternatives_0_2_1");
			builder.put(grammarAccess.getFeatureDeclarationAccess().getAlternatives(), "rule__FeatureDeclaration__Alternatives");
			builder.put(grammarAccess.getFeatureSpecializationPartAccess().getAlternatives(), "rule__FeatureSpecializationPart__Alternatives");
			builder.put(grammarAccess.getMultiplicityPartAccess().getAlternatives(), "rule__MultiplicityPart__Alternatives");
			builder.put(grammarAccess.getMultiplicityPartAccess().getAlternatives_1_1(), "rule__MultiplicityPart__Alternatives_1_1");
			builder.put(grammarAccess.getFeatureSpecializationAccess().getAlternatives(), "rule__FeatureSpecialization__Alternatives");
			builder.put(grammarAccess.getFeatureSpecializationAccess().getAlternatives_0_0(), "rule__FeatureSpecialization__Alternatives_0_0");
			builder.put(grammarAccess.getFeatureSpecializationAccess().getAlternatives_1_0(), "rule__FeatureSpecialization__Alternatives_1_0");
			builder.put(grammarAccess.getFeatureSpecializationAccess().getAlternatives_2_0(), "rule__FeatureSpecialization__Alternatives_2_0");
			builder.put(grammarAccess.getFeatureSpecializationAccess().getAlternatives_3_0(), "rule__FeatureSpecialization__Alternatives_3_0");
			builder.put(grammarAccess.getFeatureSpecializationAccess().getAlternatives_4_0(), "rule__FeatureSpecialization__Alternatives_4_0");
			builder.put(grammarAccess.getNameAccess().getAlternatives(), "rule__Name__Alternatives");
			builder.put(grammarAccess.getExpressionNameAccess().getAlternatives(), "rule__ExpressionName__Alternatives");
			builder.put(grammarAccess.getExpressionAccess().getAlternatives_2(), "rule__Expression__Alternatives_2");
			builder.put(grammarAccess.getVisibilityIndicatorAccess().getAlternatives(), "rule__VisibilityIndicator__Alternatives");
			builder.put(grammarAccess.getPackageAccess().getGroup(), "rule__Package__Group__0");
			builder.put(grammarAccess.getNamespaceImportAccess().getGroup(), "rule__NamespaceImport__Group__0");
			builder.put(grammarAccess.getCommentAccess().getGroup(), "rule__Comment__Group__0");
			builder.put(grammarAccess.getAttributeDefinitionAccess().getGroup(), "rule__AttributeDefinition__Group__0");
			builder.put(grammarAccess.getAttributeDefinitionAccess().getGroup_3_1(), "rule__AttributeDefinition__Group_3_1__0");
			builder.put(grammarAccess.getPartDefinitionAccess().getGroup(), "rule__PartDefinition__Group__0");
			builder.put(grammarAccess.getPartDefinitionAccess().getGroup_4_1(), "rule__PartDefinition__Group_4_1__0");
			builder.put(grammarAccess.getAttributeUsageAccess().getGroup(), "rule__AttributeUsage__Group__0");
			builder.put(grammarAccess.getAttributeUsageAccess().getGroup_2_1(), "rule__AttributeUsage__Group_2_1__0");
			builder.put(grammarAccess.getActionUsageAccess().getGroup(), "rule__ActionUsage__Group__0");
			builder.put(grammarAccess.getActionUsageAccess().getGroup_2_1(), "rule__ActionUsage__Group_2_1__0");
			builder.put(grammarAccess.getPartUsageAccess().getGroup(), "rule__PartUsage__Group__0");
			builder.put(grammarAccess.getPartUsageAccess().getGroup_2_1(), "rule__PartUsage__Group_2_1__0");
			builder.put(grammarAccess.getUsageAccess().getGroup(), "rule__Usage__Group__0");
			builder.put(grammarAccess.getFeatureValueAccess().getGroup(), "rule__FeatureValue__Group__0");
			builder.put(grammarAccess.getFeatureValueAccess().getGroup_0_2(), "rule__FeatureValue__Group_0_2__0");
			builder.put(grammarAccess.getFeatureDeclarationAccess().getGroup_0(), "rule__FeatureDeclaration__Group_0__0");
			builder.put(grammarAccess.getFeatureSpecializationPartAccess().getGroup_0(), "rule__FeatureSpecializationPart__Group_0__0");
			builder.put(grammarAccess.getFeatureSpecializationPartAccess().getGroup_1(), "rule__FeatureSpecializationPart__Group_1__0");
			builder.put(grammarAccess.getMultiplicityPartAccess().getGroup_0(), "rule__MultiplicityPart__Group_0__0");
			builder.put(grammarAccess.getMultiplicityPartAccess().getGroup_0_2(), "rule__MultiplicityPart__Group_0_2__0");
			builder.put(grammarAccess.getMultiplicityPartAccess().getGroup_1(), "rule__MultiplicityPart__Group_1__0");
			builder.put(grammarAccess.getMultiplicityPartAccess().getGroup_1_0(), "rule__MultiplicityPart__Group_1_0__0");
			builder.put(grammarAccess.getMultiplicityPartAccess().getGroup_1_0_2(), "rule__MultiplicityPart__Group_1_0_2__0");
			builder.put(grammarAccess.getMultiplicityPartAccess().getGroup_1_1_0(), "rule__MultiplicityPart__Group_1_1_0__0");
			builder.put(grammarAccess.getMultiplicityPartAccess().getGroup_1_1_1(), "rule__MultiplicityPart__Group_1_1_1__0");
			builder.put(grammarAccess.getFeatureSpecializationAccess().getGroup_0(), "rule__FeatureSpecialization__Group_0__0");
			builder.put(grammarAccess.getFeatureSpecializationAccess().getGroup_0_0_1(), "rule__FeatureSpecialization__Group_0_0_1__0");
			builder.put(grammarAccess.getFeatureSpecializationAccess().getGroup_0_2(), "rule__FeatureSpecialization__Group_0_2__0");
			builder.put(grammarAccess.getFeatureSpecializationAccess().getGroup_1(), "rule__FeatureSpecialization__Group_1__0");
			builder.put(grammarAccess.getFeatureSpecializationAccess().getGroup_1_2(), "rule__FeatureSpecialization__Group_1_2__0");
			builder.put(grammarAccess.getFeatureSpecializationAccess().getGroup_2(), "rule__FeatureSpecialization__Group_2__0");
			builder.put(grammarAccess.getFeatureSpecializationAccess().getGroup_2_2(), "rule__FeatureSpecialization__Group_2_2__0");
			builder.put(grammarAccess.getFeatureSpecializationAccess().getGroup_3(), "rule__FeatureSpecialization__Group_3__0");
			builder.put(grammarAccess.getFeatureSpecializationAccess().getGroup_3_2(), "rule__FeatureSpecialization__Group_3_2__0");
			builder.put(grammarAccess.getFeatureSpecializationAccess().getGroup_4(), "rule__FeatureSpecialization__Group_4__0");
			builder.put(grammarAccess.getFeatureSpecializationAccess().getGroup_4_2(), "rule__FeatureSpecialization__Group_4_2__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
			builder.put(grammarAccess.getFeatureChainNameAccess().getGroup(), "rule__FeatureChainName__Group__0");
			builder.put(grammarAccess.getFeatureChainNameAccess().getGroup_1(), "rule__FeatureChainName__Group_1__0");
			builder.put(grammarAccess.getExpressionAccess().getGroup(), "rule__Expression__Group__0");
			builder.put(grammarAccess.getExpressionAccess().getGroup_2_0(), "rule__Expression__Group_2_0__0");
			builder.put(grammarAccess.getExpressionAccess().getGroup_2_1(), "rule__Expression__Group_2_1__0");
			builder.put(grammarAccess.getNamespaceAccess().getPackagesAssignment(), "rule__Namespace__PackagesAssignment");
			builder.put(grammarAccess.getPackageAccess().getDeclaredNameAssignment_1(), "rule__Package__DeclaredNameAssignment_1");
			builder.put(grammarAccess.getPackageAccess().getElementsAssignment_3(), "rule__Package__ElementsAssignment_3");
			builder.put(grammarAccess.getNamespaceImportAccess().getVisibilityAssignment_0(), "rule__NamespaceImport__VisibilityAssignment_0");
			builder.put(grammarAccess.getNamespaceImportAccess().getDeclaredNameAssignment_2(), "rule__NamespaceImport__DeclaredNameAssignment_2");
			builder.put(grammarAccess.getCommentAccess().getBodyAssignment_1(), "rule__Comment__BodyAssignment_1");
			builder.put(grammarAccess.getAttributeDefinitionAccess().getDeclaredNameAssignment_2(), "rule__AttributeDefinition__DeclaredNameAssignment_2");
			builder.put(grammarAccess.getAttributeDefinitionAccess().getElementsAssignment_3_1_1(), "rule__AttributeDefinition__ElementsAssignment_3_1_1");
			builder.put(grammarAccess.getPartDefinitionAccess().getDeclaredNameAssignment_2(), "rule__PartDefinition__DeclaredNameAssignment_2");
			builder.put(grammarAccess.getPartDefinitionAccess().getElementsAssignment_4_1_1(), "rule__PartDefinition__ElementsAssignment_4_1_1");
			builder.put(grammarAccess.getAttributeUsageAccess().getDeclaredNameAssignment_1(), "rule__AttributeUsage__DeclaredNameAssignment_1");
			builder.put(grammarAccess.getAttributeUsageAccess().getElementsAssignment_2_1_1(), "rule__AttributeUsage__ElementsAssignment_2_1_1");
			builder.put(grammarAccess.getActionUsageAccess().getDeclaredNameAssignment_1(), "rule__ActionUsage__DeclaredNameAssignment_1");
			builder.put(grammarAccess.getActionUsageAccess().getElementsAssignment_2_1_1(), "rule__ActionUsage__ElementsAssignment_2_1_1");
			builder.put(grammarAccess.getPartUsageAccess().getElementsAssignment_2_1_1(), "rule__PartUsage__ElementsAssignment_2_1_1");
			builder.put(grammarAccess.getFeatureValueAccess().getIsInitialAssignment_0_1(), "rule__FeatureValue__IsInitialAssignment_0_1");
			builder.put(grammarAccess.getFeatureValueAccess().getIsDefaultAssignment_0_2_0(), "rule__FeatureValue__IsDefaultAssignment_0_2_0");
			builder.put(grammarAccess.getFeatureValueAccess().getIsInitialAssignment_0_2_1_1(), "rule__FeatureValue__IsInitialAssignment_0_2_1_1");
			builder.put(grammarAccess.getFeatureValueAccess().getOwnedExpressionAssignment_1(), "rule__FeatureValue__OwnedExpressionAssignment_1");
			builder.put(grammarAccess.getFeatureDeclarationAccess().getDeclaredNameAssignment_0_0(), "rule__FeatureDeclaration__DeclaredNameAssignment_0_0");
			builder.put(grammarAccess.getMultiplicityPartAccess().getMultiplicityAssignment_0_1(), "rule__MultiplicityPart__MultiplicityAssignment_0_1");
			builder.put(grammarAccess.getMultiplicityPartAccess().getMultiplicityAssignment_0_2_1(), "rule__MultiplicityPart__MultiplicityAssignment_0_2_1");
			builder.put(grammarAccess.getMultiplicityPartAccess().getMultiplicityAssignment_1_0_1(), "rule__MultiplicityPart__MultiplicityAssignment_1_0_1");
			builder.put(grammarAccess.getMultiplicityPartAccess().getMultiplicityAssignment_1_0_2_1(), "rule__MultiplicityPart__MultiplicityAssignment_1_0_2_1");
			builder.put(grammarAccess.getMultiplicityPartAccess().getIsOrderedAssignment_1_1_0_0(), "rule__MultiplicityPart__IsOrderedAssignment_1_1_0_0");
			builder.put(grammarAccess.getMultiplicityPartAccess().getIsNonuniqueAssignment_1_1_0_1(), "rule__MultiplicityPart__IsNonuniqueAssignment_1_1_0_1");
			builder.put(grammarAccess.getMultiplicityPartAccess().getIsNonuniqueAssignment_1_1_1_0(), "rule__MultiplicityPart__IsNonuniqueAssignment_1_1_1_0");
			builder.put(grammarAccess.getMultiplicityPartAccess().getIsOrderedAssignment_1_1_1_1(), "rule__MultiplicityPart__IsOrderedAssignment_1_1_1_1");
			builder.put(grammarAccess.getFeatureSpecializationAccess().getTypingsAssignment_0_1(), "rule__FeatureSpecialization__TypingsAssignment_0_1");
			builder.put(grammarAccess.getFeatureSpecializationAccess().getTypingsAssignment_0_2_1(), "rule__FeatureSpecialization__TypingsAssignment_0_2_1");
			builder.put(grammarAccess.getFeatureSpecializationAccess().getSubsettingAssignment_1_1(), "rule__FeatureSpecialization__SubsettingAssignment_1_1");
			builder.put(grammarAccess.getFeatureSpecializationAccess().getSubsettingAssignment_1_2_1(), "rule__FeatureSpecialization__SubsettingAssignment_1_2_1");
			builder.put(grammarAccess.getFeatureSpecializationAccess().getReferencesAssignment_2_1(), "rule__FeatureSpecialization__ReferencesAssignment_2_1");
			builder.put(grammarAccess.getFeatureSpecializationAccess().getReferencesAssignment_2_2_1(), "rule__FeatureSpecialization__ReferencesAssignment_2_2_1");
			builder.put(grammarAccess.getFeatureSpecializationAccess().getCrossesAssignment_3_1(), "rule__FeatureSpecialization__CrossesAssignment_3_1");
			builder.put(grammarAccess.getFeatureSpecializationAccess().getCrossesAssignment_3_2_1(), "rule__FeatureSpecialization__CrossesAssignment_3_2_1");
			builder.put(grammarAccess.getFeatureSpecializationAccess().getRedefinitionsAssignment_4_1(), "rule__FeatureSpecialization__RedefinitionsAssignment_4_1");
			builder.put(grammarAccess.getFeatureSpecializationAccess().getRedefinitionsAssignment_4_2_1(), "rule__FeatureSpecialization__RedefinitionsAssignment_4_2_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private SysMLOCGrammarAccess grammarAccess;

	@Override
	protected InternalSysMLOCParser createParser() {
		InternalSysMLOCParser result = new InternalSysMLOCParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_NOTE", "RULE_SL_NOTE" };
	}

	public SysMLOCGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SysMLOCGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
