/*
 * generated by Xtext 2.38.0
 */
package dut.control.sysmloc.ui;

import com.google.inject.Injector;
import dut.control.sysmloc.ui.internal.SysmlocActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SysMLOCExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(SysmlocActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		SysmlocActivator activator = SysmlocActivator.getInstance();
		return activator != null ? activator.getInjector(SysmlocActivator.DUT_CONTROL_SYSMLOC_SYSMLOC) : null;
	}

}
